### PR TITLE
fix(plugins): `type` and type-defining properties are now readonly

### LINKED ISSUE #8818: Some read-only properties (like `type`) are not const in per-plugin json schema
### Describe the issue

Image

This leads to no code not being able to put the input as readonly

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes #8818

### CODE REVIEW

File: core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java [hunk 1]
```diff
@@ -525,6 +526,54 @@ public CustomDefinition provideCustomSchemaDefinition(ResolvedType javaType, Sch
                     }
                 }
             });
+        } else {
+            builder.forTypesInGeneral().withTypeAttributeOverride((collectedTypeAttributes, scope, context) -> {
```
Comment (AcevedoR) [inline core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java]: maybe extract this in a named function for clarity if possible ?
or add a comment to explain? 
without this commit/issue it seems hard to understand what the code does

**Review by AcevedoR — APPROVED** [review]
