### PR TITLE
fixes issue #11352

### LINKED ISSUE #11352: Remove small shadow above the user selector
When you minimize the left menu, a small shadow appears on top of the user selector (see attached image).

This was most likely introduced in https://github.com/kestra-io/kestra/pull/11252. We just need to ensure it does not overlap the sidebar border when collapsed.

Image

### PR DESCRIPTION
**Pull request by Sehnya**
Closes https://github.com/kestra-io/kestra/issues/11352.

# Kestra Sidebar Shadow Fix

Last updated: 2025-09-17 13:11

This document describes the UI fix to remove the unwanted shadow/gradient overlay that appeared over the user section when the Kestra left sidebar was collapsed.

## Summary

- Issue: When the sidebar is collapsed, a subtle shadow/gradient from a pseudo-element overlapped the user section, creating a visual artifact.
- Fix: Added a scoped CSS override in the sidebar component to disable the `.vsm--item::after` overlay when the menu is in the collapsed state.
- Scope: Only affects the collapsed state; expanded behavior remains unchanged.

## Files Changed

- ui/src/components/layout/SideBar.vue
  - Added a CSS rule within the `#side-menu.vsm_collapsed` block to remove the overlay pseudo-element.

## Exact Change

Inside `#side-menu { &.vsm_collapsed { ... } }`, we added:

```scss
/* Remove shadow/gradient overlay when sidebar is collapsed */
.vsm--item::after {
  display: none;
}
```

Context in file (simplified):

```scss
#side-menu {
  /* ... other styles ... */
  &.vsm_collapsed {
    /* existing collapsed styles */

    /* Remove shadow/gradient overlay when sidebar is collapsed */
    .vsm--item::after {
      display: none;
    }
  }

  /* Default overlay for expanded state (kept) */
  .vsm--item {
    position: relative;

    &::after {
      content: '';
      position: absolute;
      bottom: 0;
      left: 0;
      right: 0;
      height: 1.25rem;
      z-index: 5;
      background: linear-gradient(to top, var(--ks-background-left-menu), transparent);
      opacity: 0.18;
    }
  }
}
```

## Rationale

- The overlay (`.vsm--item::after`) provides a subtle fade in the expanded menu list but becomes visually distracting when the menu collapses and items compress. Hiding it only in the collapsed state preserves the intended design in the expanded view.

## How to Test

1. Start the Kestra UI (dev or build) for the repository.
2. Navigate to a page with the left sidebar visible.
3. Collapse the sidebar using the toggle button.
4. Observe the user section (avatar/menu at the bottom):
   - Before: a faint shadow/gradient overlapped the area.
   - After: no shadow/gradient overlay; the area is clean.
5. Expand the sidebar again and scroll the menu to confirm the gradient overlay still appears as intended in expanded mode.
6. Verify in both light and dark themes.

## Rollback

- To revert, remove the `display: none;` rule for `.vsm--item::after` under the `&.vsm_collapsed` block in `SideBar.vue`.

## Notes

- This change is intentionally minimal and scoped to the collapsed state to avoid unintended visual regressions elsewhere in the menu.

### CODE REVIEW

**Comment by Sehnya** [comment]
fixes issue #11352

**Comment by MilosPaunovic** [comment]
Just a small note for the future, if you could use **GitHub Keywords** when opening PRs to connect it to the proper issue (to automate the entire process a bit more), it would be super helpful to us. You can read a bit more about it [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) (I've added closing keyword for this particular issue).

I see that you've added it as a comment down below, but GH only acknowledges it if it's added inside the issue description.

File: ui/src/components/layout/SideBar.vue [hunk 1]
```diff
@@ -356,6 +356,11 @@
                 padding: 0 5px;
             }
 
+            /* Remove shadow/gradient overlay when sidebar is collapsed */
```
Comment (MilosPaunovic) [inline ui/src/components/layout/SideBar.vue]: This is not actually what we want, the better solution would be to remove this change and to amend line `382` in this file to be `10px`.

Is that something you're willing to tackle @Sehnya?

Thanks for the efforts so far! 🚀

**Review by MilosPaunovic — CHANGES_REQUESTED** [review]

File: ui/src/components/layout/SideBar.vue (hunk 1 above)
Comment (Sehnya) [reply ui/src/components/layout/SideBar.vue]: Yes, I'll tackle this! Thanks for the guidance as well!

**Comment by MilosPaunovic** [comment]
There are also some conflicts that need to be resolved @Sehnya.

**Comment by Sehnya** [comment]
looking into this now!

**Review by MilosPaunovic — APPROVED** [review]

File: ui/src/components/layout/SideBar.vue (hunk 1 above)
Comment (MilosPaunovic) [reply ui/src/components/layout/SideBar.vue]: As we've done some refactoring in the meantime, I've applied the change and will merge this soon.
