### PR TITLE
fix(execution)*: decode and hide nested inputs of type SECRET

### LINKED ISSUE #7964: Nested inputs of type SECRET are not decrypted at runtime
### Describe the issue

When using inputs of type `SECRET` and defining them as `nested`, their values are not decrypted at runtime.

These inputs are decrypted at runtime:

```
- id: aws_access_key_id
  type: SECRET
  description: The AWS Access Key Id of the Assumed Role to authenticate to Vault
  displayName: AWS Access Key ID
- id: aws_secret_access_key
  type: SECRET
  description: The AWS Secret Access Key of the Assumed Role to authenticate to Vault
  displayName: AWS Secret Access Key
- id: aws_session_token
  type: SECRET
  description: The AWS Session Token of the Assumed Role to authenticate to Vault
  displayName: AWS Session Token
```

These inputs are not decrypted at runtime:

```
- id: aws.access.key.id
  type: SECRET
  description: The AWS Access Key Id of the Assumed Role to authenticate to Vault
  displayName: AWS Access Key ID
- id: aws.secret.access.key
  type: SECRET
  description: The AWS Secret Access Key of the Assumed Role to authenticate to Vault
  displayName: AWS Secret Access Key
- id: aws.session.token
  type: SECRET
  description: The AWS Session Token of the Assumed Role to authenticate to Vault
  displayName: AWS Session Token
```

### Environment

- Kestra Version: v0.21.7

### PR DESCRIPTION
**Pull request by loicmathieu**
Fixes #7964

### CODE REVIEW

File: core/src/main/java/io/kestra/core/runners/RunContextLogger.java [hunk 1]
```diff
@@ -233,6 +233,7 @@ protected BaseAppender(RunContextLogger runContextLogger, Logger logger) {
 
         private String replaceSecret(String data) {
             for (String s : runContextLogger.useSecrets) {
+                System.out.println(s);
```
Comment (brian-mulier-p) [inline core/src/main/java/io/kestra/core/runners/RunContextLogger.java]:
```suggestion
```

**Review by brian-mulier-p — APPROVED** [review]
LGTM

File: core/src/main/java/io/kestra/core/runners/RunContextLogger.java (hunk 1 above)
Comment (loicmathieu) [reply core/src/main/java/io/kestra/core/runners/RunContextLogger.java]: :( I'll remove that.
