### PR TITLE
fix: Filter by 'not equals' in query 

### LINKED ISSUE #13241: [Filters] Flows by label 'not equals' not shown
### Describe the issue

Applying the _Labels filter_ with the operator _Not equals_ results in an empty result set.

# Reproduction steps

1) Create a new flow with label `foo:bar`
2) Create another flow with no labels
3) Navigate to the Flows view
4) Add fIlters - Labels - Not equals - `foo:bar`
5) The flow with no labels should be shown but there is none

# Note

The filter works correctly using v1.1.5 EE Kafka/OpenSearch.

### Environment

- Kestra Version: 1.1.5

### PR DESCRIPTION
**Pull request by coder-shankar**
---

### ✨ Description
Introduces support for the not_equals filter, which was previously unimplemented in the query logic. 

### 🔗 Related Issue
Fix: https://github.com/kestra-io/kestra/issues/13241

Screen Record:

https://github.com/user-attachments/assets/205c627f-c61a-4d45-993b-c8474743a18e

### CODE REVIEW

File: core/src/test/java/io/kestra/core/repositories/AbstractFlowRepositoryTest.java [hunk 1]
```diff
@@ -179,6 +179,56 @@ void findById() {
...
+
+        FlowWithSource flowWithDifferentLabel =builder(tenant)
+            .id("flow-with-different-label")
+            .labels(Label.from(Map.of("foo", "baz")))
+            .build();
+
+        FlowWithSource flowWithDifferentLabel1 =builder(tenant)
+            .id("flow-with-different-label1")
+            .labels(Label.from(Map.of("foo", "baz")))
+            .build();
```
Comment (brian-mulier-p) [inline core/src/test/java/io/kestra/core/repositories/AbstractFlowRepositoryTest.java]:
```suggestion
```

Unused?

**Review by brian-mulier-p — APPROVED** [review]
LGTM, just remove the useless var please, I'll need to do the EE counterpart for Elastic then we may merge.
Thanks for your contribution!

**Comment by brian-mulier-p** [comment]
Just FYI I'm really busy rn so most likely this PR will wait 1 or 2 weeks before getting merged as I need to do the EE counterpart with ElasticSearch. Unless you really need that change and I'll try to slip it before. Please tell if it's ok for you.

**Review by brian-mulier-p — APPROVED** [review]
LGTM, ty for the contribution 👍
