### PR TITLE
fix(ui): save existing flow after making changes

### LINKED ISSUE #8368: [Multi-Panel editor] Cannot save the flow after making changes
### Describe the issue

To reproduce, create a first revision of some flow e.g.:

```yaml
id: hello
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

Then try to change the message and Save again e.g.:
```yaml
id: hello
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello kestra
```

You should see the error: `Invalid entity. At flow.id: Flow id already exists`

Image

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by starlightknown**
### What changes are being made and why?

closes #8368 
---

### How the changes have been QAed?

https://github.com/user-attachments/assets/f97e015a-491b-4293-85c6-32937e5e4dd5

---

### CODE REVIEW

**Comment by MilosPaunovic** [comment]
@starlightknown I'm not sure if it was by accident, but there are no changes in this PR besides comments. Could you add them back for me to be able to review it?

**Comment by starlightknown** [comment]
> @starlightknown I'm not sure if it was by accident, but there are no changes in this PR besides comments. Could you add them back for me to be able to review it?

Hi, I see two file changes still. 
image

**Comment by MilosPaunovic** [comment]
You're absolutely right, my bad, must've clicked on a wrong link. Will review this probably tomorrow. Thanks for the work so far! 🚀

**Comment by starlightknown** [comment]
> You're absolutely right, my bad, must've clicked on a wrong link. Will review this probably tomorrow. Thanks for the work so far! 🚀

I was able to replicate the issue which Anna mentioned, but now I'm not able to. :/ now its getting saved without throwing any error. Also checked if I'm on the fix branch but I'm on develop. Could you please help me confirm if the issue is still existing for you?

**Comment by MilosPaunovic** [comment]
It was existing this morning, and the problem was created by a sequence:

1. Go to flow creation
2. Save flow but stay on the page
3. Change something, like a description
4. Click on save again - problem appears

If you reload a page in between first and second save, it all works fine.

**Comment by starlightknown** [comment]
> It was existing this morning, and the problem was created by a sequence:
> 
> 1. Go to flow creation
> 2. Save flow but stay on the page
> 3. Change something, like a description
> 4. Click on save again - problem appears
> 
> If you reload a page in between first and second save, it all works fine.

Got it, I'll recheck again and see if the fix works fine

**Comment by starlightknown** [comment]
image

also a small thing, why do we have save button enabled even if there's nothing to change? Like this is the default I see. Even after doing cmd+S via keyboard to save the save button is enabled. I feel like it should be disabled

**Comment by starlightknown** [comment]
okay findings so far:

- with some of my changes, In edit mode it works fine. 
- when we create a new flow and save it initially, the save button gets disabled after initial save. When trying to go out of the flows page it says there are unsaved changes via a popup but the save button is not getting enabled.

**Comment by starlightknown** [comment]
- tried a few things but I can't make edits and save when creating a flow and saving it for the first time. Is there some restriction? If there is, then when we are saving it for the second time and it throws an error its interpreting that its a new flow and not editing existing one. Maybe we can rename save to create and disable edits?
- I see when clicking on edit there's a new field `revision: 1` added there which is not initially there when creating, is this something I should look into?

image

**Comment by MilosPaunovic** [comment]
Okay, I've got confused a bit here.

What the initial problem from the issue is that we are having error being shown while editing just saved flow. I'll attach a small video reproduction of it:

[Screencast from 2025-04-15 10-44-34.webm](https://github.com/user-attachments/assets/86896683-b7f7-4a7d-ad6e-2101fc36b73e)

I'm guessing that some property on initial save is not updated and the second save is calling the endpoint for creation instead of updating the flow.

If you can reproduce it, that is what we're aiming to solve. If not, we can take over and dig deeper to see what's going on.

**Comment by starlightknown** [comment]
I'm able to reproduce it, but I'm getting stuck when editing it. I made changes with which we don't get the error anymore but the edits don't get saved either 🥲

File: ui/src/components/flows/MultiPanelEditorView.vue [hunk 1]
```diff
@@ -33,6 +33,14 @@
     const store = useStore()
     const flow = computed(() => store.state.flow.flow)
 
+    onMounted(() => {
+        store.commit("flow/setIsCreating", false)
+    })
+
+    watch(flow, () => {
+        store.commit("flow/setIsCreating", false)
+    })
```
Comment (elevatebart) [inline ui/src/components/flows/MultiPanelEditorView.vue]: I feel this would be set more obviously in the component that edits workflows: `FlowRoot.vue`

You can add this in the onCreate hook.

File: ui/src/stores/flow.js [hunk 2]
```diff
@@ -195,7 +199,7 @@ export default {
                 }
             }
 
-            if (state.isCreating && !overrideFlow) {
+            if (state.isCreating && !overrideFlow && !isExistingFlow) {
```
Comment (elevatebart) [inline ui/src/stores/flow.js]: If we are not creating a new flow, we have to be working on an existing flow or is there a third way that I am missing?

I guess what I am asking is why this change?

**Review by elevatebart — APPROVED** [review]
I believe what you did works.
Since the logic was not obvious to me I suggested an alternative that I understood better.

Please answer if I misunderstood ;)

**Review by elevatebart — CHANGES_REQUESTED** [review]
I believe what you did works.
Since the logic was not obvious to me I suggested an alternative that I understood better.

Please answer if I misunderstood ;)

**Comment by starlightknown** [comment]
after all this I realised that its a small change. It wasn't detecting the change after the first save even if iscreating is false. Have made the changes and updated the video as well in the description

**Review by elevatebart — APPROVED** [review]
This works

**Comment by starlightknown** [comment]
Thanks for the review!

**Comment by starlightknown** [comment]
@elevatebart does it get merged automatically?

File: ui/src/components/inputs/EditorButtonsWrapper.vue [hunk 3]
```diff
@@ -12,7 +12,7 @@
             :is-read-only="isReadOnly"
             :can-delete="true"
             :is-allowed-edit="isAllowedEdit"
-            :have-change="tabs.some(t => t.dirty === true)"
+            :have-change="store.state.flow.haveChange || tabs.some(t => t.dirty === true)"
```
Comment (elevatebart) [inline ui/src/components/inputs/EditorButtonsWrapper.vue:15]: Why this change? 

I don't understand how this relate to allowing the flow to be saved after creation
