### PR TITLE
fix(core): Valid correctly conditions in triggers

### LINKED ISSUE #9204: Conditions are not validated and can be saved even if invalid
This flow can be saved: 

```
id: gorilla_535419
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
triggers:
  - id: sdf
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "* * * * *"
    withSeconds: false
    conditions:
      - sdfsdf
```

For sure, the flow is invalid, and should not be validated and save. 

It will be run on the scheduler with an error 

<details><summary>Scheduler error</summary>
<div>

```
13:46:01.340 ERROR pool-30-thread-1 flow.gorilla_535419.sdf Unable to evaluate the trigger 'sdf'
java.lang.NullPointerException: Cannot invoke "io.kestra.core.models.conditions.Condition.test(Object)" because "condition" is null
	at io.kestra.core.services.ConditionService.lambda$areValid$1(ConditionService.java:85)
	at io.kestra.core.utils.Rethrow.lambda$throwPredicate$3(Rethrow.java:79)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:708)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637)
	at io.kestra.core.services.ConditionService.areValid(ConditionService.java:85)
	at io.kestra.core.schedulers.AbstractScheduler.lambda$handle$32(AbstractScheduler.java:620)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.kestra.core.schedulers.AbstractScheduler.lambda$handle$33(AbstractScheduler.java:614)
	at io.kestra.jdbc.runner.JdbcScheduler.lambda$handleNext$3(JdbcScheduler.java:66)
	at io.kestra.jdbc.runner.JdbcSchedulerContext.lambda$doInTransaction$0(JdbcSchedulerContext.java:26)
	at org.jooq.impl.DefaultDSLContext.lambda$transaction$5(DefaultDSLContext.java:594)
	at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:532)
	at org.jooq.impl.Tools$3$1.block(Tools.java:6312)
	at java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
	at org.jooq.impl.Tools$3.get(Tools.java:6309)
	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:580)
	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:503)
	at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:593)
	at io.kestra.jdbc.JooqDSLContextWrapper.lambda$transaction$1(JooqDSLContextWrapper.java:58)
	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
	at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
	at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
	at dev.failsafe.internal.FallbackExecutor.lambda$apply$0(FallbackExecutor.java:51)
	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
	at io.kestra.core.utils.RetryUtils$Instance.wrap(RetryUtils.java:144)
	at io.kestra.core.utils.RetryUtils$Instance.runRetryIf(RetryUtils.java:103)
	at io.kestra.jdbc.JooqDSLContextWrapper.transaction(JooqDSLContextWrapper.java:55)
	at io.kestra.jdbc.runner.JdbcSchedulerContext.doInTransaction(JdbcSchedulerContext.java:23)
	at io.kestra.jdbc.runner.JdbcScheduler.handleNext(JdbcScheduler.java:63)
	at io.kestra.core.schedulers.AbstractScheduler.handle(AbstractScheduler.java:555)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:358)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

</div>
</details>

### PR DESCRIPTION
**Pull request by Skraye**
close #9204

### CODE REVIEW

File: core/src/main/java/io/kestra/core/models/triggers/AbstractTrigger.java [hunk 1]
```diff
@@ -38,12 +38,12 @@ abstract public class AbstractTrigger implements TriggerInterface {
...
     private String description;
 
-    @Valid
     @PluginProperty
     @Schema(
         title = "List of conditions in order to limit the flow trigger."
     )
-    protected List<Condition> conditions;
+    @Valid
+    protected List<@Valid @NotNull Condition> conditions;
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/models/triggers/AbstractTrigger.java:46]:
```suggestion
    protected List<@Valid @NotNull Condition> conditions;
```
I think you only need the annotation to the generic type not the List carrier type.
But anyway, it's OK for me as is.

**Review by loicmathieu — APPROVED** [review]
