### PR TITLE
fix(core): Better contrast in validation error tooltip

### LINKED ISSUE #1228: [Topology - Task Editor] Task validation tooltip is unreadable while in Light Editor / Theme
### Expected Behavior

We should be able to read tooltip even in Light theme

### Actual Behaviour

image
image

### Steps To Reproduce

Light mode editor
Go to Topology
Edit a task
Tooltip is unreadable

### Environment Information

- Kestra Version: 0.9.0-SNAPSHOT

### Example flow

_No response_

### PR DESCRIPTION
**Pull request by Skraye**
close #1228

### CODE REVIEW

File: ui/src/components/flows/ValidationError.vue [hunk 1]
```diff
@@ -1,10 +1,20 @@
 <template>
-    <el-tooltip :disabled="!error" raw-content transition="" :hide-after="0" :persistent="false">
+    <el-tooltip
+        :disabled="!error"
+        raw-content
+        transition=""
+        :hide-after="0"
+        :persistent="false"
+        :effect="theme === 'light' ? 'light' : none"
```
Comment (tchiotludo) [inline ui/src/components/flows/ValidationError.vue:8]: Tooltip are always dark even on light theme. 
Please just add some style for the text

**Review by tchiotludo — CHANGES_REQUESTED** [review]

File: ui/src/components/flows/ValidationError.vue (hunk 1 above)
Comment (Skraye) [reply ui/src/components/flows/ValidationError.vue:8]: is white font ok for both @tchiotludo  ? 
image
image

Comment (tchiotludo) [reply ui/src/components/flows/ValidationError.vue:8]: prefect :+1:

**Review by brian-mulier-p — APPROVED** [review]
