### PR TITLE
feat(core): implement backend validation for login for configs and also fixes PH event

### LINKED ISSUE #10180: Display invalid email/password error message for easier troubleshooting
Backend is done -- the error message is stored in the Settings table

@Piyush-r-bhaskar Let's add handling for use case such as when user enters invalid email address on `server.basic-auth.username` or password that doesn't match our password policy (currently, it can't be too long) -- currently, the server would simply crash. Instead, we should show an error on the login page explaining to the user what is wrong with their configuration. Quick win: add error message key and store it alongside the credentials in the Settings table `kestra.server. authentication-configuration-error` -- the frontend can display this error message along with "Make sure to update your configuration to fix this error message".

Image

### PR DESCRIPTION
**Pull request by Piyush-r-bhaskar**
Closes https://github.com/kestra-io/kestra/issues/10180

@nkwiatkowski - Could you please review for small BE changes- you may push the test required in this same branch.

Earlier, when we used to have invalid creds in config file, I was being routed to `/setup` but expectation is to go to `login` and then validation error will inform about invalid creds in config.

Now : 
- No creds in config - `setup`
- Invalid creds in config - `login` (now BE validation will show it's magic)
- valid creds in config - `login` page to use those.

**Note**: Valid/ Invalid means the BE regex respect being done or not.

Also, I had to remove `/api/v1/basicAuthValidationErrors` from tenant routing system otherwise it was not giving the messages.

**Additional**: Posthog events for Setup process was not working - I separated initialization because setup happens before authentication, And `App.vue` PostHog only initializes after authentication So, i kept it as it is..

### CODE REVIEW

File: webserver/src/main/java/io/kestra/webserver/services/BasicAuthService.java [hunk 1]
```diff
@@ -147,8 +147,16 @@ public SaltedBasicAuthConfiguration configuration() {
     }
 
     public boolean isBasicAuthInitialized(){
+
         SaltedBasicAuthConfiguration configuration = configuration();
-        return configuration != null && configuration.getUsername() != null && configuration.getPassword() != null;
+
+        if (configuration != null && configuration.getUsername() != null && configuration.getPassword() != null) {
+            return true;
+        }
```
Comment (nkwiatkowski) [inline webserver/src/main/java/io/kestra/webserver/services/BasicAuthService.java]: This condition is already in the next condition validation, so it can be removed

**Review by nkwiatkowski — CHANGES_REQUESTED** [review]

File: webserver/src/main/java/io/kestra/webserver/rooting/TenantAliasingRooter.java [hunk 2]
```diff
@@ -22,7 +22,8 @@ public class TenantAliasingRooter extends DefaultRouter {
 
     protected static final List<Pattern> EXCLUDED_ROUTES = List.of(
         Pattern.compile("/api/v1/main/.*"),
-        Pattern.compile("/api/v1/configs")
+        Pattern.compile("/api/v1/configs"),
+        Pattern.compile("/api/v1/basicAuthValidationErrors")
```
Comment (nkwiatkowski) [inline webserver/src/main/java/io/kestra/webserver/rooting/TenantAliasingRooter.java]: This should not be changed, the basic auth validation error route doesn't exist with a tenant, so the router don't route it

**Review by nkwiatkowski — CHANGES_REQUESTED** [review]

**Review by nkwiatkowski — APPROVED** [review]
LGTM

File: ui/src/components/basicauth/BasicAuthSetup.vue [hunk 3]
```diff
@@ -304,14 +304,10 @@
         try {
             const config = await miscStore.loadConfigs()
 
-            const setupCompleted = localStorage.getItem("basicAuthSetupCompleted") === "true"
-            
-            // If setup is marked as completed
-            // OR if basic auth is initialized, redirect to welcome
-            if (setupCompleted || (config && config.isBasicAuthInitialized)) {
+            if (config && config.isBasicAuthInitialized) {
```
Comment (elevatebart) [inline ui/src/components/basicauth/BasicAuthSetup.vue]:
```suggestion
            if (config?.isBasicAuthInitialized) {
```

**Comment by Piyush-r-bhaskar** [comment]
@nkwiatkowski could you please check the BE test CI or if all good we can merge 🙂
