### PR TITLE
Avoid ContentTooLongException when handling multipart request bodies

### LINKED ISSUE #13791: io.kestra.plugin.core.http.Request fails with ContentTooLongException while sending content type as multipart/form-data
### Describe the issue

io.kestra.plugin.core.http.Request fails with ContentTooLongException while sending content type as multipart/form-data

Use case:

- Use a flow with `http.Request` task

```
 id: Centric_UploadFile
   type: io.kestra.plugin.core.http.Request
   contentType: multipart/form-data
   formData:
     file:
      content: "{{ outputs.Download_from_NAS[parent.taskrun.value].to }}"
      name: "{{outputs.Download_from_NAS[parent.taskrun.value].from | substringAfterLast('/')}}"
      headers:
      cookie: "{{outputs.RequestAuthToken_RemoveDuplicates is defined ? outputs.RequestAuthToken_RemoveDuplicates.outputs.access_token : inputs.access_token}}"
      method: POST
      sslOptions:
        insecureTrustAllCertificates: true
      timeout: PT30M
      uri: "{{ render(namespace.api.plm.base_uri) }}/csi-requesthandler/api/v2/images"
```

### What is observed:

Error is reported 

```
2025-12-19 13:43:11.607java.lang.RuntimeException: org.apache.hc.core5.http.ContentTooLongException: Content length is too long: 856347
  at io.kestra.core.http.client.HttpClient.request(HttpClient.java:294)
  at io.kestra.core.http.client.HttpClient.request(HttpClient.java:222)
  at io.kestra.plugin.core.http.Request.run(Request.java:327)
  at io.kestra.plugin.core.http.Request.run(Request.java:29)
  at io.kestra.worker.WorkerTaskCallable.lambda$doCall$1(WorkerTaskCallable.java:79)
  at dev.failsafe.Functions.lambda$toCtxSupplier$9(Functions.java:228)
  at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
  at dev.failsafe.internal.TimeoutExecutor.lambda$apply$1(TimeoutExecutor.java:93)
  at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
  at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
  at dev.failsafe.FailsafeExecutor.run(FailsafeExecutor.java:220)
  at io.kestra.worker.WorkerTaskCallable.doCall(WorkerTaskCallable.java:79)
  at io.kestra.worker.AbstractWorkerCallable.call(AbstractWorkerCallable.java:64)
  at io.kestra.worker.WorkerSecurityService.callInSecurityContext(WorkerSecurityService.java:10)
  at io.kestra.worker.DefaultWorker.lambda$callJob$19(DefaultWorker.java:980)
  at io.kestra.core.trace.NoopTracer.inCurrentContext(NoopTracer.java:15)
  at io.kestra.worker.DefaultWorker.callJob(DefaultWorker.java:976)
  at io.kestra.worker.DefaultWorker.runAttempt(DefaultWorker.java:934)
  at io.kestra.worker.DefaultWorker.run(DefaultWorker.java:728)
  at io.kestra.worker.DefaultWorker.handleTask(DefaultWorker.java:379)
  at io.kestra.worker.DefaultWorker.lambda$run$8(DefaultWorker.java:294)
  at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.hc.core5.http.ContentTooLongException: Content length is too long: 856347
  at org.apache.hc.client5.http.entity.mime.MultipartFormEntity.getContent(MultipartFormEntity.java:100)
  at io.kestra.core.http.HttpRequest$RequestBody.from(HttpRequest.java:195).  <<<< Interesting line
  at io.kestra.core.http.HttpRequest.from(HttpRequest.java:62)
  at io.kestra.core.http.HttpResponse.from(HttpResponse.java:53)
  at io.kestra.core.http.client.apache.FailedResponseInterceptor.raiseError(FailedResponseInterceptor.java:51)
  at io.kestra.core.http.client.apache.FailedResponseInterceptor.process(FailedResponseInterceptor.java:33)
  at org.apache.hc.core5.http.protocol.DefaultHttpProcessor.process(DefaultHttpProcessor.java:117)
  at org.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:143)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:200)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:195)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:151)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at io.micrometer.core.instrument.binder.httpcomponents.hc5.ObservationExecChainHandler.execute(ObservationExecChainHandler.java:127)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:112)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:110)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:185)
  at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:245)
  at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188)
  at io.kestra.core.http.client.HttpClient.request(HttpClient.java:282)
```

### What is expected

No ContentTooLongException exception is thrown. 

### Workaround
Use `path` property instead of `content`

```
formData:
 file:
   path: "{{ outputs.Download_from_NAS[parent.taskrun.value].to }}"
```

### Environment

- Kestra Version: 1.1.5
- Locally can not be reproduced

Flow used:

```
id: ibis_195978
namespace: company.team

tasks:
  - id: Create_Sample_File
    type: io.kestra.plugin.core.storage.Write
    content: |
      {% for i in range(0, 100000) %}
      AAAAAAAAAA
      {% endfor %}
    extension: .txt

  - id: Centric_UploadFile
    type: io.kestra.plugin.core.http.Request
    contentType: multipart/form-data
    method: POST
    formData:
      file:
        content: "kestra:///image/Screenshot-2025-12-18-at-10.10.36.png"
        name: "Screenshot-2025-12-18-at-10.10.36.png"
    headers:
      cookie: "xxxxxx"
    options:
      ssl:
        insecureTrustAllCertificates: true
    timeout: PT5M
    uri: "https://httpbin.org/post"
```

### PR DESCRIPTION
**Pull request by bluemeaford**
### Update

This PR now avoids materializing multipart request bodies by passing the multipart `HttpEntity` through unchanged.
A focused regression test was added to ensure multipart entities are preserved when rebuilding the request.

This fixes a client-side failure when building or inspecting multipart request bodies.

For multipart/*, HttpRequest.RequestBody.from(HttpEntity) now preserves and passes through the original HttpEntity instead of reading or buffering its content.
This avoids client-side ContentTooLongException while keeping multipart requests fully functional.

A regression test is added that uploads a large file via multipart/form-data using a kestra:/// storage URI. On develop, this throws a client-side ContentTooLongException; with this change, the request reaches the server and fails with a normal HTTP 413 response.

⸻

🔗 Related Issue

Closes https://github.com/kestra-io/kestra/issues/13791

⸻

### 🛠️ Backend Checklist

- [x] Code compiles successfully and passes all checks
- [x] All unit and integration tests pass
⸻

📝 Additional Notes

The intent is to avoid client-side exceptions so multipart requests can fail normally when rejected by the server (e.g. HTTP 413).

### CODE REVIEW

**Review by loicmathieu — CHANGES_REQUESTED** [review]
I'm not sure this is what we want, with this PR this is no longer possible to do any multipart request, but multipart request should be possible.

I think the fix should mitiguates the ContentTooLongException not fail all multipart request.

**Comment by bluemeaford** [comment]
Good catch — agreed. My change is too broad and breaks normal multipart requests. I’ll narrow it so it still sends a real multipart body while skipping the content materialization that triggers the exception, and I’ll add a small multipart sanity test.

**Comment by loicmathieu** [comment]
@bluemeaford did you still work on this issue? If not let's close this PR for now.

**Comment by bluemeaford** [comment]
@loicmathieu 
Yes — I pushed an update narrowing the change and added a small multipart sanity test. It should now preserve normal multipart requests. Happy to adjust if needed.

File: core/src/main/java/io/kestra/core/http/HttpRequest.java [hunk 1]
```diff
@@ -270,6 +278,26 @@ public HttpEntity to() throws IOException {
...
+    @AllArgsConstructor
+    @SuperBuilder
+    public static class PassthroughRequestBody extends RequestBody {
+        private HttpEntity entity;
+        private String contentType;
+        private Charset charset;
+
+        @Override
+        public Object getContent() {
+            return "[omitted]";
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/http/HttpRequest.java]: This method should never be used right?
So better make it throw `UnsupportedMethodException` to be 100% sure

**Review by loicmathieu — CHANGES_REQUESTED** [review]

File: core/src/main/java/io/kestra/core/http/HttpRequest.java (hunk 1 above)
Comment (bluemeaford) [reply core/src/main/java/io/kestra/core/http/HttpRequest.java]: Good point — updated getContent() to throw UnsupportedOperationException.

**Review by loicmathieu — APPROVED** [review]
LGMT, thanks

**Comment by loicmathieu** [comment]
Backported to 1.0 and 1.3
