### PR TITLE
fix(core): properly encode filenames with spaces in URI

### LINKED ISSUE #11569: Unable to download a file whoose filename contains a space after a dot
### Describe the issue

Hi, 
When using the download plugin in order to download a file with a space after a dot such as `sample.file with weird naming.txt` an exception is thrown

I've created a repo that explains my understanding of the bug with an example file

https://github.com/PepperSniffer/kestra-download-bug

Our current workaround is to copy the Download plugin and simply change the fileExtension extraction part (proposed solution in the repo) but i feel like this only resolve one part of the problem

### Environment

- Kestra Version: 1.0.2

### PR DESCRIPTION
**Pull request by Vedant794**
### What changes are being made and why?

This PR fixes a bug where downloading files with spaces after a dot in their filename (e.g., `sample.file with weird naming.txt`) would fail with:

```
java.net.URISyntaxException: Illegal character in path ...
```

**Root cause**: the filename was concatenated into a `URI` without proper percent-encoding, leaving spaces as illegal characters.

**Change**:

* Encode filenames before resolving them into URIs with `URLEncoder.encode(...)`.
* Replace `"+"` with `"%20"` to ensure spaces are valid for path segments.

This ensures all filenames, including those containing spaces or other special characters, can be stored and downloaded without error.
Closes #11569

---

### How the changes have been QAed?

QA was done by reproducing the reported issue using a flow that downloads a file with a space after a dot in its name. With the fix applied, the file is successfully stored and downloaded without throwing a `URISyntaxException`.

```yaml
id: download-bug-test
namespace: dev

tasks:
  - id: downloadweirdfile
    type: io.kestra.plugin.core.http.Download
    uri: "https://raw.githubusercontent.com/PepperSniffer/kestra-download-bug/main/sample.file%20with%20weird%20naming.txt"
```

Before the fix:
❌ Task fails with `java.net.URISyntaxException`

After the fix:
✅ Task completes successfully, file is downloaded and processed.

---

### Setup Instructions

No additional setup required.
Run the provided flow on any Kestra instance (tested on v1.0.2) to verify the fix.

### CODE REVIEW

**Comment by loicmathieu** [comment]
The same should be done on the `putFile(InputStream, String)` in fact I think the method you update should called  `putFile(InputStream, String)` to avoid duplication.

Also it would worth a test maybe inside `DownloadFilesTest`.

**Review by loicmathieu — CHANGES_REQUESTED** [review]
Please see my previous comments (sorry I forgot to click on Request changes on the PR review)

**Comment by Vedant794** [comment]
Hi @loicmathieu, thanks for the feedback! 
Just to clarify before I make changes:
- Do you want me to refactor so that the fix lives in putFile(InputStream, String) (and the File version simply delegates to it), instead of keeping the fix inside putFile(File, String)?
- For the tests, should I extend DownloadFilesTest with a case that uses a filename like sample.file with weird naming.txt to confirm the fix?

**Comment by loicmathieu** [comment]
> Do you want me to refactor so that the fix lives in putFile(InputStream, String) (and the File version simply delegates to it), instead of keeping the fix inside putFile(File, String)?

Yes

> For the tests, should I extend DownloadFilesTest with a case that uses a filename like sample.file with weird naming.txt to confirm the fix?

You should add a new test method in it with a case that uses a filename with weird naming yes

**Comment by Vedant794** [comment]
I’ve updated the PR with the requested refactor to putFile(InputStream, String) and added a test for filenames with spaces after a dot.

File: core/src/test/java/io/kestra/plugin/core/namespace/DownloadFilesTest.java [hunk 1]
```diff
@@ -49,4 +50,36 @@ void shouldDownloadNamespaceFile() throws Exception {
...
+        namespace.putFile(
+                Path.of(weirdFileName),
+                new ByteArrayInputStream("test content".getBytes(StandardCharsets.UTF_8)));
+
+        // Run the task
+        DownloadFiles.Output output = downloadFiles.run(runContext);
+
+        // Verify the file was downloaded successfully
+        assertThat(output.getFiles()).containsKey(weirdFileName);
+        assertThat(output.getFiles().get(weirdFileName)).isNotNull();
```
Comment (loicmathieu) [inline core/src/test/java/io/kestra/plugin/core/namespace/DownloadFilesTest.java]: Please assert on the exact file name as it's deterministic

**Review by loicmathieu — CHANGES_REQUESTED** [review]
Can you remove the additional empty lines you added and switch your IDE to use continuous identation of 4 and not 8 as it's what we use in this project.

**Comment by Vedant794** [comment]
I did that formatting part if you want anything else please let me know.

**Review by loicmathieu — APPROVED** [review]
LGTM, thanks

**Comment by loicmathieu** [comment]
Hi `DownloadFilesTest` didn't compile anymore could you have a look please?

**Comment by Vedant794** [comment]
The backend CI is failing with a 403 when trying to post the test summary (Resource not accessible by integration). The tests themselves are passing successfully. Could you please check the workflow permissions?

**Comment by loicmathieu** [comment]
@Vedant794 this is a known issue, it's on our backlog to fix that.
But the previous step also fail with compilation issue:

```
/home/runner/work/kestra/kestra/core/src/test/java/io/kestra/plugin/core/namespace/DownloadFilesTest.java:74: error: cannot find symbol
        assertThat(output.getFiles()).containsKey(weirdFileName);
                                                  ^
  symbol:   variable weirdFileName
  location: class DownloadFilesTest
/home/runner/work/kestra/kestra/core/src/test/java/io/kestra/plugin/core/namespace/DownloadFilesTest.java:75: error: cannot find symbol
        assertThat(output.getFiles().get(weirdFileName)).isNotNull();
                                         ^
  symbol:   variable weirdFileName
  location: class DownloadFilesTest
```

Please take care at least that the project is building using `gradle compileTestJava` and the test is passing by for ex running it inside your IDE or using `gradle test`.

**Comment by Vedant794** [comment]
Ok, I'll fix it.

**Review by loicmathieu — APPROVED** [review]
LGTM, thanks

**Comment by loicmathieu** [comment]
@Vedant794 I had to revert your PR, sorry, test still didn't pass, I should have not merging it.
Overall I'm not sure this is the right way to do it. It may need more investiguation.
