### PR TITLE
fix(core): Doc search is more relevant

### LINKED ISSUE #6329: Add a search on the inner docs + a back button
image

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes #6329

### CODE REVIEW

File: ui/src/stores/doc.js [hunk 1]
```diff
@@ -70,13 +78,16 @@ export default {
         pageMetadata: (state) => {
             return state.pageMetadata;
         },
-        resourceUrl: (state) => (path) => {
+        resourceUrl: (state) => (path, domain = "docs") => {
```
Comment (elevatebart) [inline ui/src/stores/doc.js]: NIT: since this is the intended domain anyway why not add the /

```suggestion
        resourceUrl: (state) => (path, domain = "/docs") => {
```

**Review by elevatebart — APPROVED** [review]
Looks good. One suggestion

File: ui/src/stores/doc.js (hunk 1 above)
Comment (brian-mulier-p) [reply ui/src/stores/doc.js]: I thought about it, it's just that I wanted to showcase that you can omit it but whatever :+1:
