### PR TITLE
fix(core): limit image size for empty state

### LINKED ISSUE #12037: Editor: Adjust icon size when no panel is open
### Describe the issue

Reduce the icon size to match the standard used elsewhere.

Image

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by RutamBhagat**
closes #12037

### CODE REVIEW

**Comment by RutamBhagat** [comment]
Hi @MilosPaunovic, could I please get your feedback on this pull request?

File: ui/src/components/layout/empty/Empty.vue [hunk 1]
```diff
@@ -1,15 +1,15 @@
 <template>
-    <section class="row empty">
-        <div class="col-sm-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
-            <div class="d-flex flex-column align-items-center gap-2 px-2">
-                <img :src>
+    <section class="empty">
+        <div class="row">
```
Comment (RutamBhagat) [inline ui/src/components/layout/empty/Empty.vue]: Adding the .row class at the section level added Bootstrap’s negative horizontal margins, which visually clipped the background/gradient at small widths.

Moving .row inside preserves grid/offset behavior for the column while keeping the section background full‑bleed

File: ui/src/components/layout/empty/Empty.vue [hunk 2]
```diff
@@ -1,15 +1,15 @@
...
+            <div class="col-sm-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
+                <img :src="src" :alt="t(`empty.${props.type}.title`)" class="empty-visual">
```
Comment (RutamBhagat) [inline ui/src/components/layout/empty/Empty.vue]: Adds an explicit source prop binding and an alt derived from the title. 

The empty-visual class provides predictable sizing so the illustration doesn’t dominate the layout on large screens.

File: ui/src/components/layout/empty/Empty.vue [hunk 3]
```diff
@@ -1,15 +1,15 @@
...
 
                 <h2>{{ t(`empty.${props.type}.title`) }}</h2>
-                <p v-html="t(`empty.${props.type}.content`)" />
+                <p class="empty-description" v-html="t(`empty.${props.type}.content`)" />
```
Comment (RutamBhagat) [inline ui/src/components/layout/empty/Empty.vue]: Constrains readable width, centers text, and applies secondary color consistently with other empty states. 

Avoids relying on global p styling inside this component.

File: ui/src/components/layout/empty/Empty.vue [hunk 4]
```diff
@@ -45,12 +45,21 @@
         font-weight: 600;
     }
 
-    p {
+    .empty-visual {
+        max-width: clamp(180px, 20vw, 240px);
+        width: 100%;
+        height: auto;
+        margin: 0 auto 1rem;
+    }
```
Comment (RutamBhagat) [inline ui/src/components/layout/empty/Empty.vue]: The clamp keeps the image balanced across viewports (not too small on desktop, not overflowing on mobile) while maintaining aspect ratio. 

Centered margin matches typography above the title

File: ui/src/components/layout/empty/Empty.vue [hunk 5]
```diff
@@ -45,12 +45,21 @@
...
+
+    .empty-description {
         width: 100%;
         max-width: 553px;
         font-size: 1rem;
         color: var(--ks-content-secondary);
         line-height: 1.5rem;
+        margin: 0 auto;
+        text-align: center;
```
Comment (RutamBhagat) [inline ui/src/components/layout/empty/Empty.vue]: Mirrors existing empty state copy width, centers content, and prevents long line lengths.

**Review by Piyush-r-bhaskar — APPROVED** [review]
