### PR TITLE
fix(ui): full view height for single task logs

### LINKED ISSUE #8001: Increase height of logs when only 1 tasks
image

When we have only 1 task, we should use the max height of the browser window

### PR DESCRIPTION
**Pull request by Piyush-r-bhaskar**
Closes #8001

### CODE REVIEW

File: ui/src/components/logs/TaskRunDetails.vue [hunk 1]
```diff
@@ -44,6 +44,7 @@
                         :min-item-size="1"
                         key-field="index"
                         class="log-lines"
+                        :style="{maxHeight: currentTaskRuns.length === 1 ? 'calc(100vh - 350px)' : '50vh'}"
```
Comment (elevatebart) [inline ui/src/components/logs/TaskRunDetails.vue]: Could this be made an extra class?
It has the advantage of allowing a design to play with it in the browser dev tools.

```suggestion
                        :class="{'single-line': currentTaskRuns.length === 1}"
```

**Review by elevatebart — APPROVED** [review]
concerns fixed all good
