### PR TITLE
fix(core): use a storage prefix with executionId for triggers

### LINKED ISSUE #1176: Trigger files from internal storage cannot be retrieved from the Execution Overview
### Expected Behavior

On the execution Overview tab, if a triggre produces a file there is a link to the file on the tab that should works.

### Actual Behaviour

The link didn't works

### Steps To Reproduce

_No response_

### Environment Information

- Kestra Version: 0.9.0-SNAPSHOT
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

```
id: trigger-wikipedia
namespace: io.kestra.tests

triggers:
  - id: wikipedia
    type: io.kestra.plugin.gcp.bigquery.Trigger
    sql: |
      SELECT DATETIME(datehour) as date, title, views FROM `bigquery-public-data.wikipedia.pageviews_2023` 
      WHERE DATE(datehour) = current_date() and wiki = 'fr' and title not in ('Cookie_(informatique)', 'Wikipédia:Accueil_principal', 'Spécial:Recherche')
      ORDER BY datehour desc, views desc
      LIMIT 10
    store: true
    interval: PT1M

tasks:
  - id: write-csv
    type: io.kestra.plugin.serdes.csv.CsvWriter
    from: "{{trigger.uri}}"


```

### PR DESCRIPTION
**Pull request by loicmathieu**
Fixes #1176

### CODE REVIEW

File: core/src/main/java/io/kestra/core/runners/RunContext.java [hunk 1]
```diff
@@ -87,7 +90,8 @@ public RunContext(ApplicationContext applicationContext, Flow flow, Task task, E
     public RunContext(ApplicationContext applicationContext, Flow flow, AbstractTrigger trigger) {
         this.initBean(applicationContext);
 
-        this.storageOutputPrefix = this.storageInterface.outputPrefix(flow);
+        this.triggerExecutionId = FriendlyId.createFriendlyId();
```
Comment (tchiotludo) [inline core/src/main/java/io/kestra/core/runners/RunContext.java:93]: use IdUtils.create()

**Review by tchiotludo — CHANGES_REQUESTED** [review]
except the minor change LGTM, go for merge

**Review by tchiotludo — CHANGES_REQUESTED** [review]
except the minor change LGTM, go for merge
