### PR TITLE
fix(): improve Docker process stability on Windows OS

### LINKED ISSUE #3590: Every script execution fails with DockerTaskRunner on Windows
### Describe the issue

I try to test kestra and every single script invocation fails. It seems the script itself is not accessible from the docker runner container. Please see the

### logs
image

The same problem occurs with scripts that access namespace files.

### the flow in question
```
id: "script_in_venv"
namespace: "myteam"
tasks:
  - id: bash
    type: io.kestra.plugin.scripts.python.Commands
    inputFiles:
      main.py: |
        import requests
        from kestra import Kestra

        response = requests.get('https://google.com')
        print(response.status_code)
        Kestra.outputs({'status': response.status_code, 'text': response.text})
    beforeCommands:
      - python -m venv venv
      - . venv/bin/activate
      - pip install requests kestra > /dev/null
    commands:
      - python main.py
```

### docker-compose.yml
```
volumes:
  postgres-data:
    driver: local  
  kestra-data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  kestra:
    image: kestra/kestra:v0.16.1-full
    pull_policy: always
    # Note that this is meant for development only. Refer to the documentation for production deployments of Kestra which runs without a root user.
    user: "root"
    command: server standalone --worker-thread=128
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          plugins:
              configurations: 
              - type: io.kestra.plugin.scripts.runner.docker.DockerTaskRunner
                values: 
                  volume-enabled: true
          server:
            basic-auth:
              enabled: false
              username: "admin@kestra.io" # it must be a valid email address
              password: kestra
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: postgres
          tasks:          
            tmp-dir:
              path: /tmp/kestra-wd/tmp                    
          url: http://localhost:8080/
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_started

```

### Environment

- Kestra Version: v0.16.1-full
- Operating System (OS/Docker/Kubernetes): Docker on WSL 2
- Java Version (if you don't run kestra in Docker):

### LINKED ISSUE #3684: Flow on Windows fails with "Error looking up function 'write': The specified procedure could not be found"
### Describe the issue

Receive an error executing the following flow on 0.16.6 on windows standalone

```
id: test
namespace: blueprint

tasks:
  - id: export
    type: io.kestra.plugin.jdbc.postgresql.Query
    url: jdbc:postgresql://postgres_server:5432/postgres
    username: admin
    password: pw
    store: true
    sql: SELECT * FROM test LIMIT 10

  - id: write_to_csv
    type: io.kestra.plugin.serdes.csv.CsvWriter
    from: "{{ outputs.export.uri }}"

  - id: process_output
    type: io.kestra.plugin.scripts.python.Script
    docker:
      image: ghcr.io/kestra-io/pydata:latest
    script: |
      print("{{ outputs.export.uri }}")

```

```
Exception in thread "docker-java-stream-930316280" java.lang.NoClassDefFoundError: Could not initialize class com.github.dockerjava.transport.DomainSocket
        at com.github.dockerjava.transport.UnixSocket.get(UnixSocket.java:29)
        at com.github.dockerjava.zerodep.ApacheDockerHttpClientImpl$2.createSocket(ApacheDockerHttpClientImpl.java:154)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:125)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:409)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:164)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:174)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:135)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:172)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
        at com.github.dockerjava.zerodep.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:206)
        at com.github.dockerjava.zerodep.ZerodepDockerHttpClient.execute(ZerodepDockerHttpClient.java:8)
        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Error looking up function 'write': The specified procedure could not be found.
 [in thread "docker-java-stream--1108008968"]
        at com.sun.jna.Function.<init>(Function.java:255)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:618)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:594)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:580)
        at com.sun.jna.Native.register(Native.java:1900)
        at com.sun.jna.Native.register(Native.java:1771)
        at com.sun.jna.Native.register(Native.java:1489)
        at com.github.dockerjava.transport.DomainSocket.<clinit>(DomainSocket.java:54)
        ... 27 more
```

### Environment

- Kestra Version: 0.16.6
- Operating System: Windows Standalone JDBC backend
- Java Version `openjdk version "17.0.11" 2024-04-16`
- Installed plugins:
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          5/7/2024   4:06 PM       11825875 plugin-jdbc-postgres-0.16.1.jar
-a----          5/7/2024   4:06 PM         105692 plugin-script-powershell-0.16.1.jar
-a----          5/7/2024   4:06 PM         129964 plugin-script-python-0.16.1.jar
-a----          5/7/2024   4:06 PM       98931636 plugin-serdes-0.16.0.jar```

### PR DESCRIPTION
**Pull request by Skraye**
close #3684
close #3590

### CODE REVIEW

File: core/src/main/java/io/kestra/core/models/tasks/runners/ScriptService.java [hunk 1]
```diff
@@ -237,4 +248,23 @@ public static String jobName(RunContext runContext) {
...
+                return "\n";
+            }
+            case TargetOS.WINDOWS -> {
+                return "\r\n";
+            }
+            default -> {
+                return System.lineSeparator();
+            }
+        }
+    }
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/models/tasks/runners/ScriptService.java]: You can add the line separator as an enumeration parameter so you can remove this method and call targetOs.lineSeparator() instead.

File: core/src/main/java/io/kestra/core/models/tasks/runners/ScriptService.java [hunk 2]
```diff
@@ -237,4 +248,23 @@ public static String jobName(RunContext runContext) {
...
+
+    public enum TargetOS {
+        LINUX,
+        WINDOWS
+    }
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/models/tasks/runners/ScriptService.java]: The enumeration woluld better be in its own file in the `io.kestra.core.models.tasks.runners` package
