### PR TITLE
fix(core): topology was no longer working on new flows

### LINKED ISSUE #10354: [Playground] The topology in the Playground mode doesn't auto-update anymore
### Describe the issue

https://jam.dev/c/24c81165-9f85-40b0-a58c-8aea8ce0eb43

Image

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes #10354

### CODE REVIEW

File: ui/src/components/flows/FlowCreate.vue [hunk 1]
```diff
@@ -66,6 +66,7 @@ tasks:
 
                 this.$store.commit("flow/setFlow", {...YAML_UTILS.parse(this.flowYaml), source: this.flowYaml});
                 this.$store.dispatch("flow/initYamlSource", {});
+                this.$store.dispatch("flow/fetchGraph")
```
Comment (elevatebart) [inline ui/src/components/flows/FlowCreate.vue]: This should be happening during `initYamlSource`.
Why is it not?

Checking

**Review by elevatebart — CHANGES_REQUESTED** [review]

**Review by elevatebart — APPROVED** [review]
