### PR TITLE
fix: Fix 'Select all' functionality in Flows component

### LINKED ISSUE #11565: [Flows] unable to select all the flows using the "Select all" option
### Describe the issue

I am unable to select all the flows with the **Select all** button.

### Reproducibility / Visuals

https://jam.dev/c/7cd911f7-a0ed-4265-9123-a5a089e554cd

### Environment

- Kestra Version: develop

### LINKED ISSUE #11567: [Namespaces] unable to select all the flows using the "Select all" option
### Describe the issue

I am unable to select all the flows with the **Select all** button inside the namespace section.

### Reproducibility / Visuals

https://jam.dev/c/18115abd-2964-4ec7-9280-2fd6a32b24ea

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by AnasFaaiz**
### What changes are being made and why?

This PR fixes the "Select all" functionality for both namespace flows (#11567) and regular flows (#11565) that was throwing "Cannot read properties of undefined (reading 'getSelectionRows')" errors.

**Changes made:**
- Fixed reference path in `useSelectTableActions` composable to use `selectTableRef` instead of `dataTableRef`
- Resolved Vue warnings about extraneous non-props attributes and non-emits event listeners
- Ensured proper template ref binding in `Flows.vue`

The issue was caused by incorrect template ref usage where `dataTableRef` was being passed to `useSelectTableActions` but the actual table component was bound to `selectTableRef`.

Closes #11567
Closes #11565

### How the changes have been QAed?

- Tested "Select all" functionality on both namespace flows and regular flows pages
- Verified that selecting individual checkboxes shows the bulk actions
- Confirmed that "Select all" button works without throwing errors
- Tested bulk operations (export, delete, enable/disable) work correctly with selected items

### Setup Instructions

No special setup required - standard Kestra UI development environment.

### CODE REVIEW

**Comment by MilosPaunovic** [comment]
@toukirkhan maybe you can have the first round of review here?

File: ui/src/components/flows/Flows.vue [hunk 1]
```diff
@@ -340,6 +340,7 @@
 
     // Permission helpers
     const user = computed(() => authStore.user);
+    const namespace = computed(() => props.namespace || route.query.namespace);
```
Comment (MilosPaunovic) [inline ui/src/components/flows/Flows.vue]: Can you tell me why this change was introduced here?

File: ui/src/components/flows/Flows.vue [hunk 2]
```diff
@@ -348,8 +349,8 @@
 
     const routeInfo = computed(() => ({title: t("flows")}));
 
-    const dataTableRef = useTemplateRef<typeof DataTable>("dataTable");
-
+    // const dataTableRef = useTemplateRef<typeof DataTable>("dataTable");
```
Comment (MilosPaunovic) [inline ui/src/components/flows/Flows.vue]: It's safe to remove the commented line.

File: ui/src/components/flows/Flows.vue [hunk 3]
```diff
@@ -638,4 +639,4 @@
 :deep(.flows-table) .el-scrollbar__thumb {
     background-color: var(--ks-border-active) !important;
 }
-</style>
+</style>
```
Comment (MilosPaunovic) [inline ui/src/components/flows/Flows.vue:640]: Can you add a final empty line here, to avoid changes not relevant to the fix?

File: ui/src/composables/useSelectTableActions.ts [hunk 4]
```diff
@@ -38,4 +38,4 @@ export function useSelectTableActions({
         toggleAllSelection,
         selectionMapper
     }
-}
+}
```
Comment (MilosPaunovic) [inline ui/src/composables/useSelectTableActions.ts]: Can you add a final empty line here, to avoid changes not relevant to the fix?

**Review by MilosPaunovic — CHANGES_REQUESTED** [review]
Hey @AnasFaaiz,

Overall, very nice work, you did manage to pinpoint the problem and swiftly resolve it.

Minor things to be amended here, but all in all, great work! 🚀

File: ui/src/components/flows/Flows.vue (hunk 1 above)
Comment (AnasFaaiz) [reply ui/src/components/flows/Flows.vue]: This change ensures the namespace is properly computed from either props or route query parameters. It's needed for the useSelectTableActions composable to correctly filter and manage flow selections across different namespace contexts

Comment (MilosPaunovic) [reply ui/src/components/flows/Flows.vue]: But you're not passing it anywhere, are you?

Comment (AnasFaaiz) [reply ui/src/components/flows/Flows.vue]: You're absolutely right,  I added the namespace computed property but I'm not actually using it anywhere. I can remove this change since it wasn't needed for the fix. The main issue was just replacing dataTableRef with selectTableRef in the useSelectTableActions call. I will make the changes now.

**Comment by MilosPaunovic** [comment]
Cool, cool, cool, if you could just click the `Resolve conversation` button here in the PR for changes you've amended, that would be awesome!

**Comment by AnasFaaiz** [comment]
Done! I've resolved the conversations for the changes. Thanks for the thorough review @MilosPaunovic!

**Review by MilosPaunovic — APPROVED** [review]
LGMT! 🚀

**Comment by toukirkhan** [comment]
great PR! @AnasFaaiz 🚀
