### PR TITLE
fix(ui/no-code-editor): Style the disabled section like other items

### LINKED ISSUE #12040: No-code Editor: Style the disabled section like other items
### Feature description

Image

Description:
In the no-code editor, the disabled section isn’t displayed inside a styled block like the other items.
For consistency, it should follow the same visual structure.

Action:
Wrap the disabled section in a block, following the style shown in the attached image example.

### PR DESCRIPTION
**Pull request by akshaywritescode**
This PR fixes the styling of disabled sections in the no-code editor to make them consistent with other items.

✅ Only includes the intended UI changes for the disabled section styling.
⚠️ Previous PR #12049 included unrelated commits due to branching from a non-develop branch.

Steps taken:
- Created a new branch from `develop`.
- Cherry-picked the commit with only the style fix.

fixes #12040

### CODE REVIEW

File: ui/src/components/no-code/components/tasks/Wrapper.vue [hunk 1]
```diff
@@ -1,6 +1,6 @@
 <template>
     <slot v-if="transparent" name="tasks" />
-    <div v-else class="schema-wrapper" :class="{bordered: !merge}">
+    <div v-else class="schema-wrapper bordered" :class="{bordered: !merge}">
```
Comment (elevatebart) [inline ui/src/components/no-code/components/tasks/Wrapper.vue]:
```suggestion
    <div v-else class="schema-wrapper bordered">
```

With your change, the `merge` prop does not have any effect anymore.

Is this intended?

**Review by elevatebart — CHANGES_REQUESTED** [review]
Thank you for this PR.

It seems we would be loosing some features by merging this. can you check?

**Comment by elevatebart** [comment]
I would instead change the `NoCode.vue` component to completely avoid merging secondary fields.

`ui/src/components/no-code/NoCode.vue#L20`

remove `merged="shouldMerge(v.schema)" ` like this.

```vue
                 <Wrapper :key="v.fieldKey" v-for="(v) in fieldsFromSchemaRest" :transparent="SECTIONS_IDS.includes(v.fieldKey)">
                    <template #tasks>
                        <TaskObjectField
                            v-bind="v"
                            @update:model-value="(val) => onTaskUpdateField(v.fieldKey, val)"
                        />
                    </template>
                </Wrapper>
```

**Comment by akshaywritescode** [comment]
Thanks @MilosPaunovic and @elevatebart!
I’ve applied the suggested fixes, please let me know if any further adjustments are needed 🙏

**Review by elevatebart — APPROVED** [review]
