### PR TITLE
fix(system): force running after execution tasks even if the executio…

### LINKED ISSUE #9852: afterExecution doesn't run for killed
### Describe the issue

It seems `afterExecution` doesn't run when killing an execution.

Sample flow:
```
id: killTest
namespace: test

tasks:
  - id: sleep
    type: io.kestra.plugin.core.flow.Sleep
    duration: PT1M

afterExecution:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "State: {{execution.state}}"
```
Run the execution and kill it (within 60 seconds). On version 0.23.3 it displays
Image

### Environment

- Kestra Version: 0.23.3

### PR DESCRIPTION
**Pull request by loicmathieu**
…n is killed

Fixes #9852

### CODE REVIEW

File: core/src/main/java/io/kestra/core/models/executions/TaskRun.java [hunk 1]
```diff
@@ -62,6 +63,11 @@ public class TaskRun implements TenantInterface {
     @With
     Boolean dynamic;
 
+    // Set it to true to force execution even if the execution is killed
```
Comment (AcevedoR) [inline core/src/main/java/io/kestra/core/models/executions/TaskRun.java:66]: you could have used java doc :p

File: core/src/main/java/io/kestra/core/runners/Worker.java [hunk 2]
```diff
@@ -657,7 +657,7 @@ private WorkerTaskResult run(WorkerTask workerTask, Boolean cleanUp) {
                 ));
         }
 
-        if (killedExecution.contains(workerTask.getTaskRun().getExecutionId())) {
+        if (! Boolean.TRUE.equals(workerTask.getTaskRun().getForceExecution()) && killedExecution.contains(workerTask.getTaskRun().getExecutionId())) {
```
Comment (AcevedoR) [inline core/src/main/java/io/kestra/core/runners/Worker.java:660]:
```suggestion
        if (Boolean.FALSE.equals(workerTask.getTaskRun().getForceExecution()) && killedExecution.contains(workerTask.getTaskRun().getExecutionId())) {
```

**Review by AcevedoR — APPROVED** [review]
LGTM, minor comments

File: core/src/main/java/io/kestra/core/runners/Worker.java (hunk 2 above)
Comment (loicmathieu) [reply core/src/main/java/io/kestra/core/runners/Worker.java:660]: It's not the same as by default this is null which is not the same as FALSE...
