### PR TITLE
fix(ui): convert Pause.vue component to TypeScript

### LINKED ISSUE #11798: Convert Pause.vue component to TS
We need `kestra/ui/src/components/executions/Pause.vue` component converted to `TypeScript` with the use of `Composition API`.

```vue
<script setup lang="ts">
   // Converted code here
</script>
```

### PR DESCRIPTION
**Pull request by prayagtushar**
### What changes are being made and why?

This PR converts the `Pause.vue` component from JavaScript to **TypeScript** to enhance code reliability, maintainability, and developer experience.
The update ensures stronger type safety, better IDE support, and consistency with the ongoing migration of Kestra’s UI components to TypeScript.

Closes #11798.

---

### How the changes have been QAed?

The updated `Pause.vue` component was tested locally by running the UI and verifying that all existing pause-related functionality behaves as expected.

### CODE REVIEW

File: ui/src/components/executions/Pause.vue [hunk 1]
```diff
@@ -6,77 +6,61 @@
...
+        }
+    });
 
-                return State.isRunning(this.execution.state.current) && ! State.isPaused(this.execution.state.current);
-            }
-        },
+    const {t} = useI18n();
+    const executionsStore = useExecutionsStore();
+    const authStore = useAuthStore();
+    const toast = getCurrentInstance()?.appContext.config.globalProperties.$toast();
```
Comment (Piyush-r-bhaskar) [inline ui/src/components/executions/Pause.vue]: Can you utilize `kestra/ui/src/utils/toast.ts` for toast ?

**Review by Piyush-r-bhaskar — CHANGES_REQUESTED** [review]

**Comment by prayagtushar** [comment]
I made the changes. @Piyush-r-bhaskar

**Review by Piyush-r-bhaskar — APPROVED** [review]
LGTM 🚀
