### PR TITLE
fix(ui): remove escaped quotes from YAML JSON autocompletion

### LINKED ISSUE #14113: Autocomplete for behaviour in PurgeFiles inserts escaped JSON string
### Describe the issue

In `io.kestra.plugin.core.namespace.PurgeFiles`, when we autocomplete the behaviour field, it gets populated like this:
`behavior: {\"type\":\"version\",\"keepAmount\":1}`

### Reproducibility and Visuals
Jam: https://jam.dev/c/df0ed730-2976-420d-a5ee-60d08d4b937d

### Expected Behaviour
Autocomplete should insert the behaviour value in a clean YAML format (without escaped quotes).

### Environment

- Kestra Version: `develop` | `1.2.0-SNAPSHOT`
- Image Hash and Time: 7da4d01 `Fri, Jan 9, 2026 10:32 PM`
- Edition: Open Source/Enterprise

### PR DESCRIPTION
**Pull request by Sumitsh28**
### ✨ Description

Fixes an issue where autocompleting fields with complex `@Builder.Default` objects (like `behavior` in `PurgeFiles`) inserted escaped JSON strings instead of valid YAML/JSON.

As discussed in the previous backend PR #14304 , fixing this at the plugin schema level isn't scalable due to the widespread use of `@Builder.Default` across Kestra plugins.

This PR implements the fix on the frontend by intercepting the Monaco Editor YAML completion override in `yamlLanguageConfigurator.ts`. It sanitizes escaped quotes (`\"` and multiple escapes like `\\\"`) from the `label`, `insertText`, and `filterText`. Since YAML natively accepts JSON, this results in a clean insertion (e.g., `{"type":"version","keepAmount":1}`) without requiring complex YAML stringification logic.

### 🔗 Related Issue

Closes #14113 
Replaces PR #14304 

### 🎨 Frontend Checklist

* [x] Code builds without errors (`npm run build`)
* [x] All existing E2E tests pass (`npm run test:e2e`)
* [x] Screenshots or video recordings attached showing the `UI` changes

### Before
image

### After
image

### CODE REVIEW

File: ui/src/composables/monaco/languages/yamlLanguageConfigurator.ts [hunk 1]
```diff
@@ -194,7 +194,30 @@ export class YamlLanguageConfigurator extends AbstractLanguageConfigurator {
...
                     label: string;
                 })[]
-            )
+            )   
+                .map((s) => {
+                    const r = {...s};
+
+                    if (typeof r.label === "string") {
+                        r.label = r.label.replace(/\\+"/g, "\"");
+                    }
```
Comment (brian-mulier-p) [inline ui/src/composables/monaco/languages/yamlLanguageConfigurator.ts]: are you sure the label should also have that change? To me only the insertText is escaped no? If the label contains the \ I'm ok with it but please do a raw replace (no regex) and don't capture every \ ahead of the ", just the one immediately before

File: ui/src/composables/monaco/languages/yamlLanguageConfigurator.ts [hunk 2]
```diff
@@ -194,7 +194,30 @@ export class YamlLanguageConfigurator extends AbstractLanguageConfigurator {
...
+
+                    if (typeof r.insertText === "string") {
+                        r.insertText = r.insertText.replace(/\\+"/g, "\"");
```
Comment (brian-mulier-p) [inline ui/src/composables/monaco/languages/yamlLanguageConfigurator.ts]: please do a raw replace (no regex) and don't capture every \ ahead of the ", just the one immediately before

File: ui/src/composables/monaco/languages/yamlLanguageConfigurator.ts [hunk 3]
```diff
@@ -194,7 +194,30 @@ export class YamlLanguageConfigurator extends AbstractLanguageConfigurator {
...
+                    } else if (typeof r.insertText === "object" && r.insertText !== null) {
+                        const textObj = r.insertText as any;
+                        if (typeof textObj.value === "string") {
+                            textObj.value = textObj.value.replace(/\\+"/g, "\"");
```
Comment (brian-mulier-p) [inline ui/src/composables/monaco/languages/yamlLanguageConfigurator.ts]: please do a raw replace (no regex) and don't capture every \ ahead of the ", just the one immediately before

File: ui/src/composables/monaco/languages/yamlLanguageConfigurator.ts [hunk 4]
```diff
@@ -194,7 +194,30 @@ export class YamlLanguageConfigurator extends AbstractLanguageConfigurator {
...
+                        }
+                    }
+
+                    if (typeof r.filterText === "string") {
+                        r.filterText = r.filterText.replace(/\\+"/g, "\"");
```
Comment (brian-mulier-p) [inline ui/src/composables/monaco/languages/yamlLanguageConfigurator.ts]: please do a raw replace (no regex) and don't capture every \ ahead of the ", just the one immediately before

**Review by brian-mulier-p — CHANGES_REQUESTED** [review]
Almost LGTM 👍

File: ui/src/composables/monaco/languages/yamlLanguageConfigurator.ts (hunk 1 above)
Comment (Sumitsh28) [reply ui/src/composables/monaco/languages/yamlLanguageConfigurator.ts]: You are right! The raw label is just property name itself without any JSON. I removed the label replacement.

File: ui/src/composables/monaco/languages/yamlLanguageConfigurator.ts (hunk 2 above)
Comment (Sumitsh28) [reply ui/src/composables/monaco/languages/yamlLanguageConfigurator.ts]: Done! I've removed the regex and updated it to use a raw string replace instead.

**Comment by MilosPaunovic** [comment]
If you've addressed any of the requested changes from the PR review, @Sumitsh28, make sure to click the `Resolve conversation` button for that particular change to signal to the reviewer that you've completed what was requested.

**Review by brian-mulier-p — APPROVED** [review]
LGTM, I removed the second replace to avoid overriding unnecessary completions, if you have an example that doesn't work with it feel free to open another PR with an example but better to replace only the non-working example to avoid having too much side-effects
