### PR TITLE
fix(ui): improve responsive layout and styling of flow editor and sidebar

### LINKED ISSUE #13180: In-line documentation no longer shows on newline
### Feature description

Unsure if this was by design or a bug, but imo a regression between at least 0.22 and 1.x has been if you go onto a newline while working on a plugin the documentation goes away. As an example see the 2 images side by side, in both cases the cursor is on line 7. In 0.22 the documentation for python plugin shows, but for 1.x it does not 

Image

### PR DESCRIPTION
**Pull request by Debjyoti2004**
### ✨ Description
This PR improves the responsiveness and UI styling of the Flow Editor and Navigation Sidebar to ensure a seamless experience on tablets and smaller laptop screens.

### Key Changes:
- **Responsive Layout (`< 1200px`):** Automatically switches to an icon-only view to conserve screen space on laptops/tablets.
- **UX Improvement**: Added <`el-tooltip`> to buttons to ensure actions remain identifiable when text labels are hidden.
- **Visual Polish**: Updated tabs with rounded corners and glassmorphism-style `hover/active` states.

### 🔗 Related Issue
Closes #13180

### 🎨 Frontend Checklist

- [x] Code builds without errors (npm run build)
- [x] All existing E2E tests pass (npm run test:e2e)
- [x] Screenshots or video recordings attached showing the UI changes

### Sample View:

https://github.com/user-attachments/assets/7265748c-be2d-4ae2-b706-a9bf01b5e518

### CODE REVIEW

**Comment by elevatebart** [comment]
This change is very interresting and beautiful.
I like it a lot.
It does not seem to fix the structural bug described by paul in the linked ticket.

To reproduce the issue:
- create a task in code
- see the documentation appear
- try to add another parameter
- the documentation returns to home

Like in the video below

[DocBug.webm](https://github.com/user-attachments/assets/c05e4289-ce6b-40ae-8e92-2394cc6d0bd4)

**Comment by Debjyoti2004** [comment]
Hi @elevatebart,
Thank you so much for the feedback!

I’m glad you liked the UI improvements.

Regarding the structural bug — thanks for explaining the reproduction steps. The video is not playing on my side for some reason, but your written steps are clear enough for me to start debugging.

I’ll reproduce this behavior locally and work on fixing the documentation panel resetting back to the home screen when adding a new parameter.

I’ll update the PR with the fix shortly.
Thanks again for the detailed review!

**Review by elevatebart — APPROVED** [review]
Now I have fixed it

File: ui/src/components/MultiPanelEditorTabs.vue [hunk 1]
```diff
@@ -59,40 +66,71 @@
...
-            gap: .25rem;
-            opacity: .5;
+            transition: all 0.2s ease-in-out;
+            gap: 0.4rem;
+            opacity: 0.7;
+            cursor: pointer; 
 
             &:hover{
-                color: var(--ks-color-text-secondary);
+                background-color: rgba(255, 255, 255, 0.1);
```
Comment (elevatebart) [inline ui/src/components/MultiPanelEditorTabs.vue]: Does this work in light mode?

**Review by elevatebart — CHANGES_REQUESTED** [review]
One final nitpick: Can you check what it looks like in light mode and share a vid?

**Comment by Debjyoti2004** [comment]
Hi @elevatebart, You are right, the previous white transparency was invisible on the light background.

I have just pushed a fix that handles both modes:
- Light Mode: Now uses a dark tint `(rgba(0, 0, 0, 0.05))` so the hover effect is visible on white.
- Dark Mode: Keeps the white tint `(rgba(255, 255, 255, 0.1))` to contrast with the dark/blue background.

https://github.com/user-attachments/assets/d98d467a-f3d7-41a5-9805-fa4a97ac7374

**Review by elevatebart — APPROVED** [review]
