### PR TITLE
fix(core): proper state detection from parsed data

### LINKED ISSUE #10523: [Executions] Error popup when navigating to execution from a flow's triggered execution bar
### Describe the issue

Go to **Flows** -> select a **triggered execution bar** from a flow -> error popup appears.

https://github.com/user-attachments/assets/49de15f3-31ac-4be9-a00b-adf26554458a

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by Piyush-r-bhaskar**
Closes https://github.com/kestra-io/kestra/issues/10523

Not sure How efficient this solution would be for`validColumns` detection in `Bar.vue`. Maybe you know better & can suggest..But this will solve the issue for now and if needed we can check again to make it efficient.

### CODE REVIEW

File: ui/src/components/dashboard/composables/charts.js [hunk 1]
```diff
@@ -107,7 +121,9 @@ export function chartClick(moment, router, route, event, parsedData, elements, t
                 state = parsedData.labels[element.index];
             }
             if (state) {
-                query.state = state;
+                // Extract state
+                const extractedState = extractState(state);
+                query.state = extractedState;
```
Comment (MilosPaunovic) [inline ui/src/components/dashboard/composables/charts.js:126]: Maybe just directly use `extractState` here?

**Review by MilosPaunovic — APPROVED** [review]
I'm okay with merging this, as the whole `charts.js` component is waiting for a rework.

File: ui/src/components/dashboard/composables/charts.js (hunk 1 above)
Comment (Piyush-r-bhaskar) [reply ui/src/components/dashboard/composables/charts.js:126]: you meant ~const extractedState = extractState(state);~.  just do `query.state = extractState(state);`. ??

Comment (MilosPaunovic) [reply ui/src/components/dashboard/composables/charts.js:126]: Yup, but no matter, this works just fine, no need to change anything.
