### PR TITLE
fix(ui): fixed the multilingual switching issue

### LINKED ISSUE #7220: Multi-language switching is not working
### Describe the issue

Image

### Environment

- Kestra Version: 0.21.1

### PR DESCRIPTION
**Pull request by yaolunmao**
Relates to #7220

### CODE REVIEW

File: ui/src/translations/i18n.ts [hunk 1]
```diff
@@ -41,7 +41,7 @@ export async function loadLocaleMessages(i18n: I18n, locale: (typeof SUPPORT_LOC
   }
 
   // set locale and locale message
-  i18n.global.setLocaleMessage(locale, messages.default[locale])
```
Comment (elevatebart) [inline ui/src/translations/i18n.ts:44]: This is exactly what was missing.

File: ui/src/components/settings/BasicSettings.vue [hunk 2]
```diff
@@ -442,6 +442,8 @@
 
                         let newlang = Utils.getLang();
                         this.$moment.locale(newlang);
+                        const messages = await import(`../../translations/${newlang}.json`)
+                        this.$v_i18n.global.setLocaleMessage(newlang, messages[newlang]);
```
Comment (elevatebart) [inline ui/src/components/settings/BasicSettings.vue:446]: Can you explain this a little?

If I understand correctly, this is to load the locale when saving.
Since the change of locale is stored in `localStorage`, the change is taken.

I believe this change will result in loading the translation file twice.

File: ui/src/utils/init.js [hunk 3]
```diff
@@ -151,7 +151,7 @@ export default async (app, routes, stores, translations, additionalTranslations
         await loadLocaleMessages(i18n, locale, additionalTranslations);
         await setI18nLanguage(i18n, locale);
     }
-    
+    app.config.globalProperties.$v_i18n = i18n;
```
Comment (elevatebart) [inline ui/src/utils/init.js:154]: if you do not need the change to `BasicSettings.vue`, you don't need this one either.

**Review by MilosPaunovic — APPROVED** [review]

**Review by elevatebart — CHANGES_REQUESTED** [review]
Thank you @yaolunmao for jumping on this so quickly. It is a great help. 

I have just one wonder about the changes needed to `BasicSettings.vue`. 
I might have missed something.

We can chat on slack if you need to.

**Comment by elevatebart** [comment]
Wooops, clarification is needed here:

@yaolunmao thanks again for the fix. 
No action needed on your end. 
This is already a lot of help.
