### PR TITLE
fix/trigger-ids-uniqueness

### LINKED ISSUE #2021: Trigger ids should be unique in a flow
### Expected Behavior

_No response_

### Actual Behaviour

See https://kestra-io.slack.com/archives/C03FQKXRK3K/p1693832885758649
Missing a validation on trigger ids

### Steps To Reproduce

_No response_

### Environment Information

- Kestra Version: 0.12.0-SNAPSHOT
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

_No response_

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes #2021

### CODE REVIEW

File: core/src/main/java/io/kestra/core/validations/ValidationFactory.java [hunk 1]
```diff
@@ -183,18 +186,22 @@ ConstraintValidator<FlowValidation, Flow> flowValidation() {
...
+            List<String> triggerIds = Optional.ofNullable(value.getTriggers()).map(Collection::stream).orElse(Stream.empty())
+                .map(AbstractTrigger::getId)
                 .toList();
-            if (taskDuplicates.size() > 0) {
-                violations.add("Duplicate task id with name [" + String.join(", ", taskDuplicates) + "]");
+
+            duplicateIds.addAll(getDuplicates(triggerIds));
+
+            if (!duplicateIds.isEmpty()) {
+                violations.add("Duplicate task id with name [" + String.join(", ", duplicateIds) + "]");
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/validations/ValidationFactory.java:204]: You cannot merge tasks and triggers, they are different things.
For a trigger you expect having a message "Duplicate trigger id with name ..."

File: core/src/main/java/io/kestra/core/validations/ValidationFactory.java [hunk 2]
```diff
@@ -183,18 +186,22 @@ ConstraintValidator<FlowValidation, Flow> flowValidation() {
...
                 .map(Task::getId)
                 .toList();
-            List<String> taskDuplicates = taskIds
-                .stream()
-                .distinct()
-                .filter(entry -> Collections.frequency(taskIds, entry) > 1)
+
+            List<String> duplicateIds = getDuplicates(taskIds);
+
+            List<String> triggerIds = Optional.ofNullable(value.getTriggers()).map(Collection::stream).orElse(Stream.empty())
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/validations/ValidationFactory.java:197]: There is a `allTriggerIds()` in the Flow class.

**Review by loicmathieu — CHANGES_REQUESTED** [review]

**Review by loicmathieu — APPROVED** [review]
LGTM
