### PR TITLE
Fix(UI): Fixes button cutoffs for force-editor

### LINKED ISSUE #13775: View Change in Output File preview displays cut off buttons
### Describe the issue

Steps to reproduce (only tested with JSON file output):

1. Create flow with output file
2. Execute flow and go to Outputs tab
3. Preview output file and switch from Auto View to Enforce Editor view
4. Buttons display cutoff but interactable

https://github.com/user-attachments/assets/27be8162-ad9a-45a1-891d-d8a82acbb9c0

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by mahadevaperuka**
### ✨ Description
Fixes the editor-container height for Enforce Editor View

### 🔗 Related Issue
Closes #13775 

### 🎨 Frontend Checklist
- [x] Code builds without errors (`npm run build`)
- [x] Screenshots or video recordings attached showing the `UI` changes

Before:
image

After:
image

### CODE REVIEW

File: ui/src/components/executions/FilePreview.vue [hunk 1]
```diff
@@ -233,4 +233,9 @@
         maxPreview.value = configPreviewInitialRows();
         encoding.value = encodingOptions[0].value;
     });
-</script>
\ No newline at end of file
+</script>
+<style lang="scss">
+    .editor-container {
+        min-height: 65px !important;
```
Comment (Piyush-r-bhaskar) [inline ui/src/components/executions/FilePreview.vue]: @mahadevaperuka can you scope the style please  and test ?

**Review by Piyush-r-bhaskar — CHANGES_REQUESTED** [review]

File: ui/src/components/executions/FilePreview.vue (hunk 1 above)
Comment (mahadevaperuka) [reply ui/src/components/executions/FilePreview.vue]: Actually, I tried it with scoped first, but it didn’t work. Then, I replaced the scoped.

Comment (MilosPaunovic) [reply ui/src/components/executions/FilePreview.vue]: Use `:deep()`

Comment (mahadevaperuka) [reply ui/src/components/executions/FilePreview.vue]: Fixed.
image

**Comment by MilosPaunovic** [comment]
@mahadevaperuka Can you please provide a flow `YAML` that can be used for testing this?

**Comment by mahadevaperuka** [comment]
> @mahadevaperuka Can you please provide a flow `YAML` that can be used for testing this?

```
id: create_json_file
namespace: company.team
description: This flow creates a JSON file with a ~50-line JSON dump.

tasks:
  - id: generate_and_save_json
    type: io.kestra.plugin.scripts.powershell.Script
    outputFiles:
      - output.json
    script: |
      # Generate an array with 50 items
      $items = 1..50 | ForEach-Object {
          @{
              "id" = $_
              "name" = "item$_"
              "timestamp" = (Get-Date).ToString("o")
              "active" = ($_ % 2 -eq 0)
          }
      }

      # Build full JSON object
      $data = @{
          "status" = "success"
          "message" = "Data processed at {{ now() }}"
          "executionId" = "{{ execution.id }}"
          "count" = $items.Count
          "items" = $items
      }

      # Convert to pretty-printed JSON
      $json = $data | ConvertTo-Json -Depth 10

      # Write JSON to file
      Set-Content -Path "output.json" -Value $json

      Write-Output "File 'output.json' created with a ~50-line JSON dump."

  - id: log_json_content
    type: io.kestra.plugin.core.log.Log
    message: |
      Content of output.json:
      {{ read(outputs.generate_and_save_json.outputFiles['output.json']) }}

**Review by MilosPaunovic — APPROVED** [review]
LGTM! 🚀
