### PR TITLE
fix concurrency limit overload issue for jdbcexecutor

### LINKED ISSUE #13211: Concurrency limit is ignored when an execution is killed and other executions are queued
### Describe the issue

we found a flow concurrency bug. The issue is as follows:
When the workflow concurrency limit is set to 2:
```
id: hello-world
namespace: tutorial
tasks:
  - id: second_task
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - sleep 1m
concurrency:
  limit: 2

```
- If we kill a running execution, it will start 2 new execution, resulting in 3 running instances - exceeding the concurrency limit.

Image

- If we kill a queued execution, it will start 1 new instance without validating against the concurrency limit.

Image

### Environment

kestra/kestra:latest

### PR DESCRIPTION
**Pull request by zhengchar**
### ✨ Description

Here are the three key updates to the toExecution method：

Regarding the judgment of the queueThenKilled state, the implementation of the h.getState().onlyRunning() method should only filter executions in the running state（exclude killing state）.
Concerning the concurrency limit, when processing execution instance in the queueThenKilled state, add logic to determine whether the execution's current state is killed and not​ triggered by a workerTaskResult message.
When checking the concurrency behavior, it is necessary to add a check for concurrency limit breaches (out-of-bounds judgment).

### 🔗 Related Issue

Closes https://github.com/kestra-io/kestra/issues/13211

### CODE REVIEW

File: jdbc/src/main/java/io/kestra/jdbc/runner/AbstractJdbcConcurrencyLimitStorage.java [hunk 1]
```diff
@@ -135,6 +135,23 @@ private Optional<ConcurrencyLimit> fetchOne(DSLContext dslContext, FlowInterface
         return this.jdbcRepository.fetchOne(select.forUpdate());
     }
 
+    public ConcurrencyLimit fetchOne(FlowInterface flow) {
```
Comment (loicmathieu) [inline jdbc/src/main/java/io/kestra/jdbc/runner/AbstractJdbcConcurrencyLimitStorage.java]: This would not be safe when called concurrently

File: jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java [hunk 2]
```diff
@@ -1170,27 +1170,34 @@ private void toExecution(Executor executor, boolean ignoreFailure) {
...
-                            );
+                        var currentFlow = executor.getFlow();
+
+                        if (!(execution.getState().getCurrent() == State.Type.KILLED && executor.getFrom().contains("addWorkerTaskResult"))) {
+                            concurrencyLimitStorage.decrement(executor.getFlow());
+
+                            int currentConcurencyLimit = this.concurrencyLimitStorage.fetchOne(currentFlow).getRunning();
+
+                            if (executor.getFlow().getConcurrency().getBehavior() == Concurrency.Behavior.QUEUE
+                                && currentConcurencyLimit < currentFlow.getConcurrency().getLimit()) {
```
Comment (loicmathieu) [inline jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java]: This is not safe if called concurrently so I don't think it should be added here even if I understand the rational

File: jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java [hunk 3]
```diff
@@ -1170,27 +1170,34 @@ private void toExecution(Executor executor, boolean ignoreFailure) {
...
-                                    executionQueue.emit(newExecution);
-                                    metricRegistry.counter(MetricRegistry.METRIC_EXECUTOR_EXECUTION_POPPED_COUNT, MetricRegistry.METRIC_EXECUTOR_EXECUTION_POPPED_COUNT_DESCRIPTION, metricRegistry.tags(newExecution)).increment();
-
-                                    // process flow triggers to allow listening on RUNNING state after a QUEUED state
-                                    processFlowTriggers(newExecution);
-                                })
-                            );
+                        var currentFlow = executor.getFlow();
+
+                        if (!(execution.getState().getCurrent() == State.Type.KILLED && executor.getFrom().contains("addWorkerTaskResult"))) {
```
Comment (loicmathieu) [inline jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java]: I'm not fan of using the `from` here, we never use this anywhere like that, it has been added only for debugging purpose I would not rely on it.
The purpose of the boolean just before are to do the same kind of check but based on the states which would be better

**Review by loicmathieu — CHANGES_REQUESTED** [review]

File: jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java (hunk 2 above)
Comment (loicmathieu) [reply jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java]: One solution would be to return the limit from the decrement method as it is done inside a FOR UPDATE so it's always safe

**Review by loicmathieu — APPROVED** [review]
LGTM, however as I contribute to this PR @brian-mulier-p can you also have a quick look please?

**Review by brian-mulier-p — APPROVED** [review]
LGTM

**Comment by loicmathieu** [comment]
@zhengchar I refactor the code to use the original state istead of looking inside the from.
I also added test, if the CI pass I will integrate it inside today's release.

I remove the sagfeguard to only pop a new one if the concurrency level is under the max, I'll keep the idea for later I may add this safeguard in a followup PR: https://github.com/kestra-io/kestra/issues/13301
