### PR TITLE
fix(core): proper deletion of single and multi ns files

### LINKED ISSUE #12613: Deleting a namespace file removes all of them
### Describe the issue

Steps to reproduce:
- Import 2 files on Files page in Namespaces 
- Delete one of them
- Refresh the page
- Both files gone

https://github.com/user-attachments/assets/4e983558-3ab5-4e8f-830c-e964a8f20aac

### Environment

- Kestra Version: `develop` EE

### PR DESCRIPTION
**Pull request by Piyush-r-bhaskar**
Closes https://github.com/kestra-io/kestra/issues/12613

### CODE REVIEW

File: ui/src/components/inputs/FileExplorer.vue [hunk 1]
```diff
@@ -688,21 +688,23 @@
 
     async function removeItems() {
         if(confirmation.value.nodes === undefined) return;
-        for (const node of confirmation.value.nodes) {
+        const paths = confirmation.value.nodes.map(node => filesStore.getPath(node.id) ?? "");
+        await Promise.all(confirmation.value.nodes.map(async (node, i) => {
+            const path = paths[i];
```
Comment (elevatebart) [inline ui/src/components/inputs/FileExplorer.vue]: Why did you need to precreate the path array? 

```suggestion
            const path = filesStore.getPath(node.id) ?? "";
```

**Review by elevatebart — COMMENTED** [review]
Just a question

File: ui/src/components/inputs/FileExplorer.vue (hunk 1 above)
Comment (Piyush-r-bhaskar) [reply ui/src/components/inputs/FileExplorer.vue]: I was thinking to get  the path for every file from filesStore before any concurrent deletion. but yeah i get the part to have the path synchronously at the very start of the async.

**Review by elevatebart — APPROVED** [review]
