### PR TITLE
fix(core): avoid adding invalid keys from query parameters to filter 

### LINKED ISSUE #9364: Filter - Blueprint tags are red
### Describe the issue

https://jam.dev/c/d8663585-928d-4a37-9916-92c61ca41520

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes https://github.com/kestra-io/kestra/issues/9364

### CODE REVIEW

**Review by AcevedoR — APPROVED** [review]
LGTM, we have tests not working well, I deisabled them for now, but will fix in another PR

File: ui/src/components/filter/KestraFilter.vue [hunk 1]
```diff
@@ -448,9 +461,12 @@
         skipRouteWatcherOnce.value = true;
         router.push({
             query: {
-                sort: route.query.sort,
-                size: route.query.size,
-                page: route.query.page,
+                ...Object.fromEntries(queryParamsToKeep.value.map(key => {
```
Comment (MilosPaunovic) [inline ui/src/components/filter/KestraFilter.vue:464]: This is causing infinite loading on pages other than the first one.
