### PR TITLE
fix(core): bring dashboard selector in navbar and also keep the selected dashboard route specific

### LINKED ISSUE #12700: Applying custom dashboard on Main is applying on Flows and Namespace and vice-versa.
### Describe the issue

Applying custom dashboard on Main is applying on Flows and Namespace and vice-versa. It should be route specific. also the storing of dashboard selected should use the storage key of different route.

https://github.com/user-attachments/assets/43c045b4-c061-4a68-a867-d95c6e896680

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by Piyush-r-bhaskar**
Closes #12700
Closes https://github.com/kestra-io/kestra-ee/issues/5672

https://github.com/user-attachments/assets/68dba336-e57f-4d58-a11a-2bd7e293c507

### CODE REVIEW

File: ui/src/stores/dashboard.ts [hunk 1]
```diff
@@ -28,6 +28,7 @@ export const useDashboardStore = defineStore("dashboard", () => {
         const dashboard = ref<Dashboard>();
         const chartErrors = ref<string[]>([]);
         const isCreating = ref<boolean>(false);
+        const loadDashboard = ref<((value: any) => void) | undefined>();
```
Comment (elevatebart) [inline ui/src/stores/dashboard.ts]: Where do you assign this function/variable?

**Review by elevatebart — CHANGES_REQUESTED** [review]
Thank you @Piyush-r-bhaskar this is a good start

I have one question to start with.
Then I would have loved a little bit of explanation.

I feel that storing the active dashboardid only in localstorage is wrong because opening a new browser will have none. 

I would prefer to have it always as a URL param.

This could be another PR though

File: ui/src/stores/dashboard.ts (hunk 1 above)
Comment (Piyush-r-bhaskar) [reply ui/src/stores/dashboard.ts]: Ahh, I think i went over engineering way doing function reference in store, I was storing the local `load()`  reference. let me not keep it tightly coupled and refactor it with reactive route (though we are hiding the ID in url for `isFlow` and `isNamespace`).

**Comment by Piyush-r-bhaskar** [comment]
> I feel that storing the active dashboardid only in localstorage is wrong because opening a new browser will have none.
> 
> I would prefer to have it always as a URL param.

I would love little bit more guidance on this 🚀

**Review by elevatebart — APPROVED** [review]
