### PR TITLE
fix(core): redesign playground run task button

### LINKED ISSUE #10389: [Playground] Code Editor is not fully implemented yet as in Figma
https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=7824-77676&t=O4bkx1ZjQFoTLckj-4

Image

Next steps discussed with @brian-mulier-p:
1. Adjust the "No data" message to make it easier for the user to spot from where to Run the task: `Hover over any task in the Flow Code editor and click the "Run task" button to test your task. You can also hit the Play icon in the No-Code or Topology views.`
2. Adjust the `Run task` button (showing up for each task only on hover) in Monaco to allow running only the current task or also downstream tasks (we discussed that we won't do any state coloring in the Monaco editor for now as it introduced unnecessary complexity)

Image

3. Fix the Topology that currently doesn't auto-update but without state in progress (no time + not that huge value add)

Image

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes #10389

### CODE REVIEW

File: ui/src/components/flows/FlowPlayground.vue [hunk 1]
```diff
@@ -33,9 +33,8 @@
                 </div>
                 <div v-else class="empty-state">
                     <img :src="EmptyVisualPlayground">
-                    <p>
-                        {{ t("playground.empty") }}
-                    </p>
+                    <p>{{ t("playground.run_task_info") }}</p>
+                    <p>{{ t("playground.play_icon_info") }}</p>
```
Comment (elevatebart) [inline ui/src/components/flows/FlowPlayground.vue:37]: Good idea, though this is not in the initial ticket I think

**Review by elevatebart — APPROVED** [review]
Looks good !!

File: ui/src/components/flows/FlowPlayground.vue (hunk 1 above)
Comment (brian-mulier-p) [reply ui/src/components/flows/FlowPlayground.vue:37]: It's the point n°1 in the ticket :+1: What we've seen in huddle with Anna
