### PR TITLE
Make Enter confirm and trigger's refresh filter, Shift+Enter adds a new line

### LINKED ISSUE #9471: [Filters] Rethink Labels filter workflow/UX
### Feature description

This is a continuation of the first point mentioned in #9324 since I still find the current v0.23 UX a bit odd.

# Example

Correct me if I am wrong, but the v0.23 workflow of filtering executions by **multiple filters - a label followed by another filter(s)** - using just keyboard (important for daily users) is as follows:

1. type `la`
2. **hit Enter** to confirm the _labels.{key}_ filter selection
3. type the key of the intended label
4. **hit Enter** to confirm the _EQUALS_ operator selection
5. type the value of the intended label
6. **do not hit Enter but hit Space** to end the label value entry - **if you hit Enter instead, it adds an EOL and makes you enter a plain text filter**
7. continue with another filter(s)

IMHO this flow looks counterintuitive and would require instructing end users.

Is there a way to enter such filter sequence in a different way?

---

As a side effect,  entering a label value containing a space requires wrapping the value with quotes.

---

Ping @brian-mulier-p @Ben8t

### PR DESCRIPTION
**Pull request by prayagtushar**
closes #9471 

### What changes are being made and why?

- **Changes**:  
  - Added a custom `Enter` key command in `editorDidMount` to append a space and update the query.  
  - Implemented `onDidChangeModelContent` to handle special cases like removing commas before spaces or new lines.  

- **Why**:  
  - These changes address the layout overflow issue by ensuring the Monaco Editor handles input (e.g., **Enter** key) consistently, appending spaces for autocompletion and maintaining query updates.  
  - The dynamic height adjustment allows the editor to grow with content, avoiding manual height constraints while ensuring the UI remains functional without "screen bleeding" when new lines are added (e.g., via **Shift + Enter**), assuming the parent container or external CSS manages overflow.
  
  Demo:
  https://jam.dev/c/3a76d99d-e414-4b0b-9718-d68569c0310f

### CODE REVIEW

File: ui/src/components/filter/KestraFilter.vue [hunk 1]
```diff
@@ -445,6 +465,31 @@
...
+                ) {
+                    mountedEditor.executeEdits("", [
+                        {
+                            range: new monaco.Range(position.lineNumber, position.column, position.lineNumber, position.column),
+                            text: " ",
+                            forceMoveMarkers: true
+                        }
+                    ]);
+                }
+                updateQuery();
```
Comment (brian-mulier-p) [inline ui/src/components/filter/KestraFilter.vue:497]: Not needed, the watcher will already see the change

Comment (brian-mulier-p) [reply ui/src/components/filter/KestraFilter.vue:497]: In fact I understand why you did that but it doesn't solve the user's problem. Here you add a QOL that will allow user to use space OR enter to start a new filter and prevent a newline from being added however it will not "refresh" as the user from the issue expect. I have no strong idea for now how to handle that because we rely on changing the route parameters and the components to detect those changes and trigger the query but in case of simple refresh (without changing parameters), since we don't have manual control over refresh it will not trigger the query itself... We will have no other choice but to give a callback to KestraFilter to trigger a hard refresh I think.

**Review by brian-mulier-p — CHANGES_REQUESTED** [review]

**Comment by anna-geller** [comment]
@Prayag-09 can you address review comments? 🙏

**Comment by anna-geller** [comment]
@Prayag-09 sorry to ping again, but are you still on it? would it be easier for you if we take over?

**Comment by brian-mulier-p** [comment]
I'll take over 1 week from now if it's still stale @Prayag-09

**Comment by prayagtushar** [comment]
Sorry for the delay, getting on it now.

**Comment by prayagtushar** [comment]
My fork was outdated, so when I tried to rebase, it ended up pushing 500+ commits into this branch. I’ve since removed the extra commits, reapplied my changes, and pushed again. Sorry for the inconvenience!

**Comment by brian-mulier-p** [comment]
I made the last few steps to merge it, ty for the contribution.
FYI I replaced all addCommand to addAction because of [this Monaco bug](https://github.com/microsoft/monaco-editor/issues/2947) that is making addCommand calls global to all Monaco instance, ence your Enter override was overlapping on regular text editors so in Flow editor you couldn't use regular enter to insert new line. That's now fixed

**Review by brian-mulier-p — APPROVED** [review]
LGTM
