### PR TITLE
fix(ui): Better duplicate key management in the pair component

### LINKED ISSUE #9220: [nocode] labels are disapearing if the same than a previously filled
https://github.com/user-attachments/assets/a6dd53fe-858e-4cd9-88ef-4859dc6bc7f1

### PR DESCRIPTION
**Pull request by Skraye**
close #9220

### CODE REVIEW

File: ui/src/components/code/components/inputs/InputPair.vue [hunk 1]
```diff
@@ -1,27 +1,35 @@
...
             :gutter="10"
         >
             <el-col :span="8">
                 <InputText
-                    :model-value="key"
+                    :model-value="pair.currentKey"
                     :placeholder="t('key')"
-                    @update:model-value="(changed) => updateKey(key, changed)"
+                    @update:model-value="(changed) => handleKeyInput(pair.id, changed)"
                 />
```
Comment (elevatebart) [inline ui/src/components/code/components/inputs/InputPair.vue]: I have been beating around this bush for a while now:
It feels like we need an error state for inputs to display these kind of errors in the context we want.

In thsi case, teh 2 dupliacted keys should be highlighted somehow.

An Icon? A border-color? a background change? A shadow?

@Nico-Kestra what do you think?

Comment (Skraye) [reply ui/src/components/code/components/inputs/InputPair.vue]: Should have shared that I have added an error message, but of course the design can be changed : 
image

Comment (Skraye) [reply ui/src/components/code/components/inputs/InputPair.vue]: The current implementation doesnt handle the duplicated key as we emit an object (that can not have 2 identicals key of course), so I couldn't leverage on modifying the flow and having the validation throw an error, so I made something inside the component that raise the error by itself

Comment (elevatebart) [reply ui/src/components/code/components/inputs/InputPair.vue]: What I meant was: 
- If we have a lot of labels, it could be hard to know which two labels got duplicated
- We can help the user by having these two keys flagged visually

File: ui/src/components/code/components/inputs/InputText.vue [hunk 2]
```diff
@@ -8,15 +8,14 @@
             :placeholder
             :disabled
             :type="disabled ? '' : 'textarea'"
-            :suffix-icon="Lock"
```
Comment (elevatebart) [inline ui/src/components/code/components/inputs/InputText.vue:11]: Can you bring back this icon if the field is disabled?

Comment (Skraye) [reply ui/src/components/code/components/inputs/InputText.vue:11]: Oops :eyes:

**Review by elevatebart — APPROVED** [review]

**Review by elevatebart — CHANGES_REQUESTED** [review]
There seems to be an oops.

```
Cannot access 'alertState' before init
```

**Review by elevatebart — APPROVED** [review]
