### PR TITLE
fix: day-week-in-month-date-time-between-failures

### LINKED ISSUE #8230: Dynamic properties fail tests for DayWeekInMonth and DateTimeBetween
### Describe the issue

When migrating `String date` to `Property<String> date` for both classes `DayWeekInMonth` and `DateTimeBetween` we are experiencing failing tests issues. When debugging the rendering is done correctly but some tests are still failing.

Issue explained in details this PR : https://github.com/kestra-io/kestra/pull/8223

### Environment

- Kestra Version: develop
Checkout branch : bug/dp-fails-tests

### PR DESCRIPTION
**Pull request by hemantmm**
closes: #8230

### What changes are being made and why?

✅ Fixed dynamic property rendering for date in `DayWeekInMonth` and `DateTimeBetween` conditions.
✅ Updated usage to `.render(date).as(String.class, vars).orElseThrow()` for correct value extraction.
✅ Ensured tests pass after migration from `String date` to `Property<String> date`.

---

Fix:

Updated the rendering logic for dynamic date properties in schedule conditions:

- Migrated `date` field from `String` to `Property<String>` in both classes.
- Changed rendering from `runContext.render(date, vars)` to `runContext.render(date).as(String.class, vars).orElseThrow()`.

### CODE REVIEW

**Comment by hemantmm** [comment]
@loicmathieu, can you review this PR?

**Comment by hemantmm** [comment]
Previously, it was failing in the old PR, but now all the schedule tests passed. 
image

File: core/src/main/java/io/kestra/plugin/core/condition/DateTimeBetween.java [hunk 1]
```diff
@@ -102,18 +101,19 @@ public class DateTimeBetween extends Condition implements ScheduleCondition {
     @Override
     public boolean test(ConditionContext conditionContext) throws InternalException {
         Map<String, Object> vars = conditionContext.getVariables();
-        String render = conditionContext.getRunContext().render(date, vars);
-        ZonedDateTime currentDate = DateUtils.parseZonedDateTime(render);
+        String render = conditionContext.getRunContext().render(date).as(String.class, vars).orElseThrow();
+        
+        ZonedDateTime currentDate = (render != null) ? DateUtils.parseZonedDateTime(render) : ZonedDateTime.now();
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/plugin/core/condition/DateTimeBetween.java]:
```suggestion
        ZonedDateTime currentDate = conditionContext.getRunContext().render(date).as(String.class, vars).map(it -> DateUtils.parseZonedDateTime(it)).orElseThrow();
```

`render` cannot be null!

Thi

File: core/src/main/java/io/kestra/plugin/core/trigger/Schedule.java [hunk 2]
```diff
@@ -564,12 +564,23 @@ private Optional<ZonedDateTime> truePreviousNextDateWithCondition(ExecutionTime
...
 
+            if (!currentConditionContext.getVariables().containsKey("trigger")) {
+                currentConditionContext = currentConditionContext.withVariables(
+                    ImmutableMap.<String, Object>builder()
+                        .putAll(currentConditionContext.getVariables())
+                        .put("trigger", currentOutput.get().toMap())
+                        .build()
+                );
+            }
+
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/plugin/core/trigger/Schedule.java:521]: Can you explain this change? Why is it needed?

File: core/src/main/java/io/kestra/plugin/core/trigger/Schedule.java [hunk 3]
```diff
@@ -564,12 +564,23 @@ private Optional<ZonedDateTime> truePreviousNextDateWithCondition(ExecutionTime
...
             boolean conditionResults = this.validateScheduleCondition(currentConditionContext);
             if (conditionResults) {
                 return currentDate;
             }
 
-            toTestDate = currentDate.get();
+            toTestDate = next
+                ? currentDate.get().plusSeconds(1)
+                : currentDate.get().minusSeconds(1);
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/plugin/core/trigger/Schedule.java:529]: Can you explain this change? Why is it needed?

File: core/src/main/java/io/kestra/plugin/core/trigger/Schedule.java [hunk 4]
```diff
@@ -602,8 +613,17 @@ private Output handleMaxDelay(Output output) {
...
+            conditionContext = conditionContext.withVariables(
+                ImmutableMap.<String, Object>builder()
+                    .putAll(conditionContext.getVariables())
+                    .put("trigger", conditionContext.getVariables().get("schedule"))
+                    .build()
+            );
+        }
+
+        if (conditions != null && !conditions.isEmpty()) {
+            ConditionService conditionService = ((DefaultRunContext) conditionContext.getRunContext()).getApplicationContext().getBean(ConditionService.class);
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/plugin/core/trigger/Schedule.java]: Can you explain this change? Why is it needed?

**Review by loicmathieu — CHANGES_REQUESTED** [review]

File: core/src/main/java/io/kestra/plugin/core/trigger/Schedule.java (hunk 4 above)
Comment (hemantmm) [reply core/src/main/java/io/kestra/plugin/core/trigger/Schedule.java]: Before this change:

- Conditions evaluated for a schedule did not receive the trigger output.
- But conditions in other triggers (like webhook, flow, kafka, etc.) always receive the trigger output in the "trigger" variable.
- This inconsistency causes conditions inside ScheduleTrigger to fail because variables referenced in conditions are missing.

So the change ensures ScheduleTrigger passes variables the same way other triggers already do.

File: core/src/main/java/io/kestra/plugin/core/trigger/Schedule.java (hunk 3 above)
Comment (hemantmm) [reply core/src/main/java/io/kestra/plugin/core/trigger/Schedule.java:529]: This is required because the Cron parser only matches a timestamp exactly, not a range.

If current time === scheduled time, the next/previous check is ambiguous:

- We want “next” to test the time after the schedule → +1 sec
- We want “previous” to test the time before the schedule → -1 sec

File: core/src/main/java/io/kestra/plugin/core/trigger/Schedule.java (hunk 2 above)
Comment (hemantmm) [reply core/src/main/java/io/kestra/plugin/core/trigger/Schedule.java:521]: Without adding` trigger` to `currentConditionContext`, only the first iteration has correct variables; all subsequent iterations fail conditions due to missing trigger output.

File: core/src/main/java/io/kestra/plugin/core/condition/DateTimeBetween.java (hunk 1 above)
Comment (hemantmm) [reply core/src/main/java/io/kestra/plugin/core/condition/DateTimeBetween.java]: I am getting an API deprecated issue for the suggested code when running the test locally:

image

**Comment by fhussonnois** [comment]
Hey @hemantmm, thank you very much for you contribution. Could you rebase your PR with the `develop` as some fixed have been made on the `Schedule` and `DateTimeBetween` classes. 

Also, could you please reevaluate the changes you've made on the `Schedule#truePreviousNextDateWithCondition` method.  In fact, we found that for the `DateTimeBetween` the rendering of the `date` was cached leading to wrong evaluation of the condition.

Thanks a lot.

**Comment by hemantmm** [comment]
@loicmathieu, can you review this PR?

**Comment by loicmathieu** [comment]
@hemantmm @fhussonnois will review it as he worked on this area lately

**Comment by hemantmm** [comment]
@fhussonnois, can you review this PR?

File: core/src/main/java/io/kestra/plugin/core/condition/DateTimeBetween.java [hunk 5]
```diff
@@ -102,18 +101,24 @@ public class DateTimeBetween extends Condition implements ScheduleCondition {
     @Override
     public boolean test(ConditionContext conditionContext) throws InternalException {
         Map<String, Object> vars = conditionContext.getVariables();
-        String render = conditionContext.getRunContext().render(date, vars);
-        ZonedDateTime currentDate = DateUtils.parseZonedDateTime(render);
+        ZonedDateTime currentDate = conditionContext.getRunContext().render(date).as(String.class, vars).map(it -> {
+            try {
```
Comment (Skraye) [inline core/src/main/java/io/kestra/plugin/core/condition/DateTimeBetween.java]: Please keep the render in a another variable for readability

File: core/src/main/java/io/kestra/plugin/core/condition/DateTimeBetween.java [hunk 6]
```diff
@@ -102,18 +101,24 @@ public class DateTimeBetween extends Condition implements ScheduleCondition {
...
 
         if (beforeRendered != null && afterRendered != null) {
-            return currentDate.isAfter(afterRendered) && currentDate.isBefore(beforeRendered);
+            return !currentDate.isBefore(afterRendered) && !currentDate.isAfter(beforeRendered);
         } else if (beforeRendered != null) {
-            return currentDate.isBefore(beforeRendered);
+            return !currentDate.isAfter(beforeRendered);
         } else if (afterRendered != null) {
-            return currentDate.isAfter(afterRendered);
+            return !currentDate.isBefore(afterRendered);
```
Comment (Skraye) [inline core/src/main/java/io/kestra/plugin/core/condition/DateTimeBetween.java]: Not necessary, please revert

File: core/src/main/java/io/kestra/plugin/core/trigger/Schedule.java [hunk 7]
```diff
@@ -536,11 +536,11 @@ private Output trueOutputWithCondition(ExecutionTime executionTime, ConditionCon
...
 
-        this.truePreviousNextDateWithCondition(executionTime, conditionContext, output.getDate(), true)
-            .ifPresent(outputBuilder::next);
+        Optional<ZonedDateTime> nextWithCondition = this.truePreviousNextDateWithCondition(executionTime, conditionContext, ZonedDateTime.from(output.getDate()), true);
+        nextWithCondition.ifPresent(outputBuilder::next);
 
-        this.truePreviousNextDateWithCondition(executionTime, conditionContext, output.getDate(), false)
-            .ifPresent(outputBuilder::previous);
+        Optional<ZonedDateTime> previousWithCondition = this.truePreviousNextDateWithCondition(executionTime, conditionContext, ZonedDateTime.from(output.getDate()), false);
+        previousWithCondition.ifPresent(outputBuilder::previous);
```
Comment (Skraye) [inline core/src/main/java/io/kestra/plugin/core/trigger/Schedule.java]: Variables are created but never used, please revert as before

File: scheduler/src/test/java/io/kestra/scheduler/SchedulerConditionTest.java [hunk 8]
```diff
@@ -56,7 +56,7 @@ private static FlowWithSource createScheduleFlow() {
             .conditions(List.of(
                 DayWeekInMonth.builder()
                     .type(DayWeekInMonth.class.getName())
-                    .date("{{ trigger.date }}")
+                    .date(Property.ofValue("2021-09-06T02:00:00+01:00"))
```
Comment (Skraye) [inline scheduler/src/test/java/io/kestra/scheduler/SchedulerConditionTest.java]: Original test was using pebble and now isn't
If you want to have a test with `Property.ofValue("2021-09-06T02:00:00+01:00")` please create a new one and keep the one using pebble thanks

**Review by Skraye — CHANGES_REQUESTED** [review]

File: core/src/main/java/io/kestra/plugin/core/condition/DateTimeBetween.java (hunk 5 above)
Comment (hemantmm) [reply core/src/main/java/io/kestra/plugin/core/condition/DateTimeBetween.java]: ok

File: core/src/main/java/io/kestra/plugin/core/condition/DateTimeBetween.java (hunk 6 above)
Comment (hemantmm) [reply core/src/main/java/io/kestra/plugin/core/condition/DateTimeBetween.java]: ok

File: scheduler/src/test/java/io/kestra/scheduler/SchedulerConditionTest.java (hunk 8 above)
Comment (hemantmm) [reply scheduler/src/test/java/io/kestra/scheduler/SchedulerConditionTest.java]: Sure

File: core/src/main/java/io/kestra/plugin/core/trigger/Schedule.java (hunk 7 above)
Comment (hemantmm) [reply core/src/main/java/io/kestra/plugin/core/trigger/Schedule.java]: Ok

**Comment by hemantmm** [comment]
@fhussonnois, can you review this PR?

**Comment by loicmathieu** [comment]
@Skraye will continue the review when he'll be back

**Comment by hemantmm** [comment]
@Skraye, can you review this PR?

**Comment by MilosPaunovic** [comment]
@hemantmm Please resolve the merge conflict here.

**Comment by Skraye** [comment]
@hemantmm Can you make sure the project compile ? Thanks

**Comment by hemantmm** [comment]
@Skraye, now the project compiles. Can you have a look at it?

**Comment by loicmathieu** [comment]
@Skraye can you proceed with this PR?

**Review by Skraye — APPROVED** [review]
LGTM
