### PR TITLE
fix(core) : removed top border for the first log entry

### LINKED ISSUE #13609: Logs Page: Remove the top border
### Describe the issue

Remove the top border above the first log entry.
This line is unnecessary.

Image

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by ameen-pj**
### ✨ Description
Fixes #13609 

Uses the below CSS trick in LogLine.vue to remove the border by addding `log-0` class in the `LogLine` component for the first log entry.

```
div.line {
    /* ... */
    // hack for class containing 0
    &[class*="-0"] {
        border-top: 0; // <- Rule B: Border OFF
    }
}
```
```
  <LogLine
      v-for="(log, i) in logsStore.logs"
      :key="`${log.taskRunId}-${i}`"
      level="TRACE"
      filter=""
      :excludeMetas="isFlowEdit ? ['namespace', 'flowId'] : []"
      :log="log"
      :class="{'log-0': i === 0}"
  />
```

### 🎨 Frontend Checklist

- [x] Code builds without errors (`npm run build`)
- [x] Screenshots or video recordings attached showing the `UI` changes
image

### CODE REVIEW

File: ui/src/components/logs/LogsWrapper.vue [hunk 1]
```diff
@@ -29,6 +29,7 @@
                                 filter=""
                                 :excludeMetas="isFlowEdit ? ['namespace', 'flowId'] : []"
                                 :log="log"
+                                :style="{borderTop: i===0 ? 'none' : '1px solid var(--ks-border-primary)'}"
```
Comment (Piyush-r-bhaskar) [inline ui/src/components/logs/LogsWrapper.vue]: Could you not add inline style please ?

**Review by Piyush-r-bhaskar — CHANGES_REQUESTED** [review]

File: ui/src/components/logs/LogsWrapper.vue (hunk 1 above)
Comment (ameen-pj) [reply ui/src/components/logs/LogsWrapper.vue]: Apologies for that. I have addressed the requested changes.

**Comment by ameen-pj** [comment]
@Piyush-r-bhaskar I have made the suggested changes.

**Review by Piyush-r-bhaskar — APPROVED** [review]
I loved the simiplicity...Thanks for the contribution
