### PR TITLE
fix(ui): bring better small chart and tooltip.

### LINKED ISSUE #10686: Flow list mini charts are not displayed or badly
When I go on the flow list page, search for a flow, I got this minicharts that is really ugly and impossible to understand : 

Image

Image

The previous version was better: 

Image

- no marging for the same day 
- duration was visible 
- the rollover allow to see the details for the current day 

Refresh this page make the mini charts not visible 

I have also inside the console this error : 
```
scales.yB.ticks.stepSize: 1 would result generating up to 12001 ticks. Limiting to 1000.
```

TL;DR: Keep previous charts but with a new data endpoint (don't reuse bar chart layout where there is too much space between bars) - ping Yann in case of questions

### PR DESCRIPTION
**Pull request by Piyush-r-bhaskar**
Closes #10686

### CODE REVIEW

File: ui/src/components/dashboard/sections/Bar.vue [hunk 1]
```diff
@@ -48,7 +48,7 @@
     const DEFAULTS = {
         display: true,
         stacked: true,
-        ticks: {maxTicksLimit: 8 , stepSize: 1},
+        ticks: {maxTicksLimit: 8},
```
Comment (MilosPaunovic) [inline ui/src/components/dashboard/sections/Bar.vue:51]: This would change the looks of the bar chart globally, and we've introduced this change in https://github.com/kestra-io/kestra/issues/9415.

Can you pass that as a prop, and have the default value as `1`, and where not needed, pass `undefined`?

**Review by MilosPaunovic — CHANGES_REQUESTED** [review]

**Review by MilosPaunovic — APPROVED** [review]
