### PR TITLE
Fixed Small Flow Screen

### LINKED ISSUE #6692: [Regression] "Execute" a selected flow screen is too small
### Describe the issue

https://capture.dropbox.com/85wpCgZ1EMH6JzkQ

Screenshot by Dropbox Capture

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by rajatsingh23**
Closes #6692

### CODE REVIEW

File: ui/src/components/flows/TriggerFlow.vue [hunk 1]
```diff
@@ -42,7 +42,9 @@
                     </el-select>
                 </el-form-item>
                 <el-form-item v-if="localFlow" :label="$t('inputs')">
-                    <flow-run @execution-trigger="closeModal" :redirect="true" />
+                    <div class="inputs-container">
```
Comment (Piyush-r-bhaskar) [inline ui/src/components/flows/TriggerFlow.vue]:
```suggestion
                    <div class="w-100">
```

Comment (Piyush-r-bhaskar) [reply ui/src/components/flows/TriggerFlow.vue]: > 

BS Class will work here. You can remove the styling for inputs-container @rajatsingh23

**Review by MilosPaunovic — APPROVED** [review]
LGTM! 🚀
