### PR TITLE
fix(core, script): render map and multiple script issues

### LINKED ISSUE #7011: The data-engineering-pipeline tutorial flow throws Jackson errors
### Describe the issue

```
 Execution failed! With last error: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('b' (code 98)): was expecting comma to separate Object entries at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 23]
```

repro:
```yaml
id: data-engineering-pipeline
namespace: tutorial
description: Data Engineering Pipelines

inputs:
  - id: columns_to_keep
    type: ARRAY
    itemType: STRING
    defaults:
      - brand
      - price

tasks:
  - id: extract
    type: io.kestra.plugin.core.http.Download
    uri: https://dummyjson.com/products

  - id: transform
    type: io.kestra.plugin.scripts.python.Script
    containerImage: python:3.11-alpine
    inputFiles:
      data.json: "{{ outputs.extract.uri }}"
    outputFiles:
      - "*.json" # ⚠️ this seems to be the culprit
    env:
      COLUMNS_TO_KEEP: "{{ inputs.columns_to_keep }}"
    script: |
      import json
      import os

      columns_to_keep_str = os.getenv("COLUMNS_TO_KEEP")
      columns_to_keep = json.loads(columns_to_keep_str)

      with open("data.json", "r") as file:
          data = json.load(file)

      filtered_data = [
          {column: product.get(column, "N/A") for column in columns_to_keep}
          for product in data["products"]
      ]

      with open("products.json", "w") as file:
          json.dump(filtered_data, file, indent=4)

  - id: query
    type: io.kestra.plugin.jdbc.duckdb.Query
    inputFiles:
      products.json: "{{ outputs.transform.outputFiles['products.json'] }}"
    sql: |
      INSTALL json;
      LOAD json;
      SELECT brand, round(avg(price), 2) as avg_price
      FROM read_json_auto('{{ workingDir }}/products.json')
      GROUP BY brand
      ORDER BY avg_price DESC;
    fetchType: STORE
```

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by brian-mulier-p**
Fixes #7011
Closes #7017

All usage of `injectDefaults(DockerOptions)` must switch to `injectDefaults(RunContext, DockerOptions)`.

### CODE REVIEW

File: core/src/main/java/io/kestra/core/models/property/Property.java [hunk 1]
```diff
@@ -168,10 +171,15 @@ public static <T, I> T asList(Property<T> property, RunContext runContext, Class
      */
     public static <T, K,V> T asMap(Property<T> property, RunContext runContext, Class<K> keyClass, Class<V> valueClass) throws IllegalVariableEvaluationException {
         if (property.value == null) {
-            String rendered =  runContext.render(property.expression);
-            JavaType type = MAPPER.getTypeFactory().constructMapType(Map.class, keyClass, valueClass);
+            JavaType targetMapType = MAPPER.getTypeFactory().constructMapType(Map.class, keyClass, valueClass);
+
             try {
-                property.value = MAPPER.readValue(rendered, type);
+                if (property.expression.startsWith("{{")) {
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/models/property/Property.java]: An expression can be "in the middle" so it would be better to check if it contains `{{` and `}}`.
We should have an helper for that as I think it's already done somewhere else

Comment (loicmathieu) [reply core/src/main/java/io/kestra/core/models/property/Property.java]: And I'm not sure I understand why you did this...

File: core/src/test/java/io/kestra/core/models/property/DynamicPropertyExampleTask.java [hunk 2]
```diff
@@ -52,21 +55,21 @@ public class DynamicPropertyExampleTask extends Task implements RunnableTask<Dyn
...
         String value = String.format(
             "%s - %s - %s - %s",
-            runContext.render(string).as(String.class).orElseThrow(),
-            runContext.render(number).as(Integer.class).orElseThrow(),
-            runContext.render(withDefault).as(String.class).orElseThrow(),
-            runContext.render(someDuration).as(Duration.class).orElseThrow()
+            runContext.render(string).as(String.class).orElse(null),
+            runContext.render(number).as(Integer.class).orElse(null),
+            runContext.render(withDefault).as(String.class).orElse(null),
+            runContext.render(someDuration).as(Duration.class).orElse(null)
```
Comment (loicmathieu) [inline core/src/test/java/io/kestra/core/models/property/DynamicPropertyExampleTask.java:61]: Well, I love my orElseThrow, what's problematic with them in test code?

**Review by loicmathieu — CHANGES_REQUESTED** [review]

File: core/src/test/java/io/kestra/core/models/property/DynamicPropertyExampleTask.java (hunk 2 above)
Comment (brian-mulier-p) [reply core/src/test/java/io/kestra/core/models/property/DynamicPropertyExampleTask.java:61]: It's painful to setup unit tests because you're required to put everything even to test a single attribute

File: core/src/main/java/io/kestra/core/models/property/Property.java (hunk 1 above)
Comment (brian-mulier-p) [reply core/src/main/java/io/kestra/core/models/property/Property.java]: Because there's two cases for which you would want to render as map (obviously when the target property type is a map):
- the property itself is an expression ({{outputs.task.myMap}})
- the property is filled with a yaml map (which can itself contain expression for each value that's why checking for "contains {{" is not enough

Comment (loicmathieu) [reply core/src/main/java/io/kestra/core/models/property/Property.java]: You should at least check for start and end.
And please add a comment as it's not trivial to understand reading the code

File: core/src/test/java/io/kestra/core/models/property/DynamicPropertyExampleTask.java (hunk 2 above)
Comment (loicmathieu) [reply core/src/test/java/io/kestra/core/models/property/DynamicPropertyExampleTask.java:61]: :man_shrugging:
