### PR TITLE
fix(core): obfuscate secrets used as default inputs (#11681)

### LINKED ISSUE #11681: Defaults with secrets are rendered on UI
### Describe the issue

Defaults for inputs can now be resolved dynamically, and they can use a secret. That’s exactly what I need, but I think there might be a catch.
 Currently, the secret in the default is displayed as its actual value in the UI, rather than being masked as ****, unlike in other places (logs, outputs).
 Is this a bug, or intended behavior? Personally, I like the current behavior, and it will be cool if we can still use secrets as default, even if they will be displayed as **** on UI
```
- id: envName
    type: STRING
    defaults: "{{secret ('Environment')}}"
```

Image

Image

### Environment

- Kestra Version: 1.0.3

### PR DESCRIPTION
**Pull request by fhussonnois**
Make sure values return from pebble function are obfuscate when return from the input validation endpoints.

Changes:
* UI: Don't send default input values when creating new execution

Fixes: #11681

### CODE REVIEW

File: core/src/main/java/io/kestra/core/runners/VariableRendererFactory.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+    
+    @Inject
+    protected VariableRenderer variableRenderer;
+    
+    public VariableRenderer getDefault() {
+        return variableRenderer;
+    }
+    
+    public VariableRenderer createWithMaskedSecrets() {
+        return new VariableRenderer(applicationContext, variableConfiguration, List.of(SecretFunction.NAME));
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/runners/VariableRendererFactory.java]: This would prevent overriding the default variable renderer which is used by one of our customer.
See https://github.com/kestra-io/kestra/pull/11559 which work around the issue, the same factory should be used here.

**Review by loicmathieu — CHANGES_REQUESTED** [review]

File: core/src/main/java/io/kestra/core/runners/VariableRendererFactory.java (hunk 1 above)
Comment (fhussonnois) [reply core/src/main/java/io/kestra/core/runners/VariableRendererFactory.java]: Thanks, good catch! I'll wait for the PR to be merged to rebase this one!

**Review by loicmathieu — APPROVED** [review]
LGTM

**Review by MilosPaunovic — APPROVED** [review]
UI side looks alright! ✅
