### PR TITLE
fix(core): prevent monaco suggestion widget to update its position

### LINKED ISSUE #9116: No Code / Multi panel - Autocomplete suggestion are hidden by panels at the left of it
### Describe the issue

https://jam.dev/c/0c4d6ae9-19af-43a3-a321-5916b61670f8

### Environment

- Kestra Version: develop

Image

### PR DESCRIPTION
**Pull request by MilosPaunovic**
If the `Monaco` editor is being created from `No Code` panel, prevent it's autocomplete suggestion widget to be re-positioned.

Closes https://github.com/kestra-io/kestra/issues/9116.

### CODE REVIEW

File: ui/src/components/inputs/MonacoEditor.vue [hunk 1]
```diff
@@ -134,6 +134,7 @@
         creating?: boolean,
         suggestionsOnFocus?: boolean,
         readonly?: boolean,
+        noCode?: boolean,
```
Comment (brian-mulier-p) [inline ui/src/components/inputs/MonacoEditor.vue]: I'd advise to put a "largeSuggestions" boolean property with default value true and you put it to false for your no code to avoid linking feature here

**Review by brian-mulier-p — APPROVED** [review]
LGTM, just change the prop name please
