### PR TITLE
fix(namespaces): avoid adding 'company.team' as default ns

### LINKED ISSUE #11168: [UI] Clicking flows automatically adds a namespace filter
### Describe the issue

- select plugins
- click flows
- notice that the filter automatically adds a namespace filter. Clicking flows once again clears it

Clicking flows by default should not have any namespace filter. 

https://jam.dev/c/48466fac-c9ba-435c-9b37-74f2004bfbec

### Environment

- Kestra Version: 1.0.0 (EE)

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes #11168

### CODE REVIEW

File: ui/src/components/flows/FlowCreate.vue [hunk 1]
```diff
@@ -11,14 +11,14 @@
...
     import MultiPanelFlowEditorView from "./MultiPanelFlowEditorView.vue";
-    import {storageKeys} from "../../utils/constants";
     import {useBlueprintsStore} from "../../stores/blueprints";
     import {useCoreStore} from "../../stores/core";
     import {editorViewTypes} from "../../utils/constants";
 
     import {getRandomID} from "../../../scripts/id";
     import {useEditorStore} from "../../stores/editor";
     import {useFlowStore} from "../../stores/flow";
+    import {defaultNamespace} from "../../composables/useNamespaces.js";
```
Comment (elevatebart) [inline ui/src/components/flows/FlowCreate.vue]:
```suggestion
    import {defaultNamespace} from "../../composables/useNamespaces";
```

**Review by elevatebart — APPROVED** [review]
nothing shocking, some details

File: ui/src/components/flows/FlowCreate.vue (hunk 1 above)
Comment (brian-mulier-p) [reply ui/src/components/flows/FlowCreate.vue]: I hate that my IDE appends that...
