### PR TITLE
fix: Validate call spam when editing a task

### LINKED ISSUE #7073: No Code - Validate call is spam when editing
### Describe the issue

When editing a task, the validate endpoint is called a lot, while it should have a timeout to wait user input to be finished : 

Image

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by starlightknown**
Closes https://github.com/kestra-io/kestra/issues/7073.

### What changes are being made and why?

It adds a timeout which decreases the validation calls when editing a task

closes [#7073](https://github.com/kestra-io/kestra/issues/7073)
---

### How the changes have been QAed?

---

### CODE REVIEW

File: ui/src/components/code/segments/Task.vue [hunk 1]
```diff
@@ -50,7 +50,7 @@
     const store = useStore();
 
     const breadcrumbs = computed(() => store.state.code.breadcrumbs);
-    const lastBreadcumb = computed(() => {
+    const llastBreadcumb = computed(() => {
```
Comment (Skraye) [inline ui/src/components/code/segments/Task.vue]: Please avoid the renaming

Comment (starlightknown) [reply ui/src/components/code/segments/Task.vue]: yes yes done by mistake, reverted

**Review by MilosPaunovic — APPROVED** [review]
LGTM! 🚀
