### PR TITLE
fix(webserver): mark the execution as killing to avoid ghost execution

### LINKED ISSUE #309: Killing WorkerTask can lead to infinite Killing
There is 2 cases : 
- executor don't know the execution (remove or prune), it will do nothing (no join on KTable)
- no worker are executing the tasks, no one will respond to executor 

We need to deal this case especially the worker one that seems to be more frequent than the others. 
- Maybe all worker must respond not for me and if all is reponding I don't know, killed the execution ?
- Maybe a timeout for the worker response and force killed ? 
- Maybe all worker must send a periodic state off current task to executor that can help me detect zombie tasks

### PR DESCRIPTION
**Pull request by loicmathieu**
After some debate and internal design, we decided to set the execution to killing inside the Executor (as it lock on the execution so no races can exist).

The fix also avoids infinite killing as it no longer waits for the Worker to kill the running tasks. The execution will be set to killing and then killed without waiting for any worker task results from the Worker.
The Worker still receives killing and will effectively kill tasks and send back WorkerTaskResult that will update the execution afterward.

Fixes #309

### CODE REVIEW

**Comment by loicmathieu** [comment]
@brian-mulier-p I merged the original PR by error and open this one instead. Can you validate it?

**Review by brian-mulier-p — APPROVED** [review]
LGTM

File: core/src/main/java/io/kestra/core/runners/ExecutorService.java [hunk 1]
```diff
@@ -559,7 +565,12 @@ private Executor handleKilling(Executor executor) {
         );
 
         if (executor.getExecution().hasRunning(currentTasks) || executor.getExecution().hasCreated()) {
-            return executor;
+            // if some tasks are not killed, send a killing event to the worker
+            killQueue.emit(ExecutionKilled
```
Comment (tchiotludo) [inline core/src/main/java/io/kestra/core/runners/ExecutorService.java:569]: One things that annoy me is that you break the transaction here, you emit directly on the queue instead of returning to executor object, that will insert into with the same transaction from kafka or jdbc.

**Review by tchiotludo — COMMENTED** [review]
see comment about transaction

File: core/src/main/java/io/kestra/core/runners/ExecutorService.java (hunk 1 above)
Comment (loicmathieu) [reply core/src/main/java/io/kestra/core/runners/ExecutorService.java:569]: For JDBC everything is done inside the transaction when consuming from the execution queue, for Kafka I'm not sure.

One way to do it would be to add an `ExecutionKilled` property inside the Executor object and send the ExecutionKilled message from the Jdbc/Memory/KAfka executor instead.

Comment (tchiotludo) [reply core/src/main/java/io/kestra/core/runners/ExecutorService.java:569]: This is the goal exactly. 
The `killQueue.emit` will be outside of the transaction also on the jdbc (since we don't provide the `DSLContext`). 
(but there is a subject to have transaction globally on jdbc executor that we don't have for now)

Comment (loicmathieu) [reply core/src/main/java/io/kestra/core/runners/ExecutorService.java]: I refacto to send ExecutionKilled from the executor and not the executor service.

**Review by brian-mulier-p — APPROVED** [review]
LGTM

**Review by brian-mulier-p — CHANGES_REQUESTED** [review]
There is a regression on task display: when we kill an execution, any previously running taskrun will no longer receive status update and stay in running (if you reload the page it will be shown as killed). This is due to /execution/follow call that stops sending update as soon as the execution is considered terminated.

This "terminated" execution status is incorrectly determined. It is purely based on execution status while there can be some running taskrun behind the scene. IMO the execution should not be considered terminated unless all its taskrun are also terminated (see [this PR](https://github.com/kestra-io/kestra/pull/2703)).

Idk about the impact though :'( But there's definitely something wrong

**Review by brian-mulier-p — APPROVED** [review]
LGTM
