### PR TITLE
Fix/plugin page menu scroll

### LINKED ISSUE #14963: Plugin Page does not have an independent scroll bar for the menu
### Describe the issue

If you select a plugin further down on the list, nothing seems to appear. You need to scroll up as the menu and the page use the same scroll. They should be independent.

https://github.com/user-attachments/assets/a40a7178-6acf-4ca3-9cde-47b0b2bf3170

### Environment

- Kestra Version: `1.3.0` EE and OSS

### PR DESCRIPTION
**Pull request by sanjay78632**
### ✨ Description
The plugin page sidebar menu and main content area shared the same scroll container, causing the main content to shift down when selecting a plugin further down the list. The sidebar menu now scrolls independently from the main content.

Changes made:
- `ui/src/components/plugins/Toc.vue`: Added `overflow-y: auto` and `height: 100%` to `.plugins-list` so the sidebar scrolls independently
- `ui/src/components/docs/DocsLayout.vue`: Added `menu-slot-wrapper` class with `flex: 1` and `min-height: 0` to properly constrain the menu slot, and changed sidebar `height` to `100vh` on desktop breakpoint
- `ui/src/components/plugins/Toc.vue`: Changed `scrollIntoView` block value from `start` to `nearest` to prevent main content from shifting when a plugin is selected

### 🔗 Related Issue
Closes https://github.com/kestra-io/kestra/issues/14963

### 🎨 Frontend Checklist
- [ ] Code builds without errors (`npm run build`)
- [ ] All existing E2E tests pass (`npm run test:e2e`)
- [x] Screenshots or video recordings attached showing the `UI` changes

https://github.com/user-attachments/assets/65deb820-5226-44ae-80e8-91a9d76c3668

### CODE REVIEW

**Comment by sanjay78632** [comment]
hey @elevatebart  can you please review this  😊

File: ui/src/components/docs/DocsLayout.vue [hunk 1]
```diff
@@ -15,7 +15,7 @@
                 :aria-label="'Close menu'"
                 link
             />
-            <div v-if="!collapsed" class="d-flex flex-column gap-3">
+            <div v-if="!collapsed" class="d-flex flex-column gap-3 menu-slot-wrapper">
```
Comment (elevatebart) [inline ui/src/components/docs/DocsLayout.vue]: Why not transfer all the utility classes to the new class?

**Review by elevatebart — COMMENTED** [review]
I will test this tomorrow but the PR seems promising.

Good work!

Thank you @sanjay78632

File: ui/src/components/docs/DocsLayout.vue (hunk 1 above)
Comment (sanjay78632) [reply ui/src/components/docs/DocsLayout.vue]: Done! Moved d-flex, flex-column, and gap-3 utility classes into the 
.menu-slot-wrapper CSS class and removed them from the template.

Comment (MilosPaunovic) [reply ui/src/components/docs/DocsLayout.vue]: If you've addressed any of the requested changes from the PR review, @sanjay78632, make sure to click the `Resolve conversation` button for that particular change to signal to the reviewer that you've completed what was requested.

**Comment by sanjay78632** [comment]
Hi @elevatebart and @MilosPaunovic  just checking in on this PR. Happy to make any changes if needed. Thank you!

**Comment by MilosPaunovic** [comment]
@sanjay78632 Can you resolve the merge conflict here please?

**Comment by MilosPaunovic** [comment]
@elevatebart Could you give this a look now that the conflicts have been resolved?

**Review by elevatebart — APPROVED** [review]
lovely !!! TYTYTY
