### PR TITLE
fix(trigger): prevent scheduler crash on large duration

### LINKED ISSUE #621: S3 Interval Trigger Crashes Scheduler on Large interval — Cannot Recover Without State Cleanup
When using an `S3` trigger with an excessively large `interval` value, the **Kestra scheduler crashes** due to an uncaught SQL exception caused by an invalid `EpochDay`.

Even after correcting the interval to a valid value, **Kestra does not recover**. The only way to fix it is by **manually removing the trigger state** from the database.

---

### Flow Example

```yaml
triggers:
  - id: watch_uploads
    type: io.kestra.plugin.aws.s3.Trigger
    interval: PT99999999898989981M  # Intentionally large value

15:39:08.979 ERROR jdbc-queue-WorkerTriggerResult_0 .c.u.ThreadUncaughtExceptionHandlers Caught an exception in Thread[#61,jdbc-queue-WorkerTriggerResult_0,5,main]. Shutting down.
java.time.DateTimeException: Invalid value for EpochDay (valid values -365243219162 - 365241780471): 69444444394570
```
impact:
  - Kestra scheduler enters a crash loop and stops functioning.
  - Fixing the interval in the flow does not resolve the crash.
  - The system cannot recover automatically.
  - Recovery requires manual cleanup of the trigger state from the database.

### Environment

- **Kestra version:** 0.23.1  
- **Deployment method:** Kubernetes (Helm chart)  
- **Database:** PostgreSQL 14  
- **Cloud provider:** DigitalOcean

### PR DESCRIPTION
**Pull request by Malaydewangan09**
- closes https://github.com/kestra-io/plugin-aws/issues/621

### CODE REVIEW

File: core/src/main/java/io/kestra/core/models/triggers/PollingTriggerInterface.java [hunk 1]
```diff
@@ -30,14 +32,26 @@ public interface PollingTriggerInterface extends WorkerTriggerInterface {
      * Schedulable triggers must override this method.
      */
     default ZonedDateTime nextEvaluationDate(ConditionContext conditionContext, Optional<? extends TriggerContext> last) throws Exception {
-        return ZonedDateTime.now().plus(this.getInterval());
+        try {
+            return ZonedDateTime.now().plus(this.getInterval());
+        } catch (DateTimeException | ArithmeticException e) {
+            RunContext runContext = conditionContext.getRunContext();
+            if (runContext != null) {
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/models/triggers/PollingTriggerInterface.java]: It should never be null here.

Comment (loicmathieu) [reply core/src/main/java/io/kestra/core/models/triggers/PollingTriggerInterface.java]: I wonder if we should not default to one year instead of 60s.

File: core/src/main/java/io/kestra/core/models/triggers/PollingTriggerInterface.java [hunk 2]
```diff
@@ -30,14 +32,26 @@ public interface PollingTriggerInterface extends WorkerTriggerInterface {
...
     /**
      * Compute the next evaluation date of the trigger: by default, it uses the current date and the interval.
      * Schedulable triggers must override this method as it's used to init them when there is no evaluation date.
      */
     default ZonedDateTime nextEvaluationDate() {
-        return ZonedDateTime.now().plus(this.getInterval());
+        try {
+            return ZonedDateTime.now().plus(this.getInterval());
+        } catch (DateTimeException | ArithmeticException e) {
+            return ZonedDateTime.now().plus(Duration.ofSeconds(60));
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/models/triggers/PollingTriggerInterface.java]: I wonder if we should not default to one year, I'll raise that to the plugin tream

File: core/src/main/java/io/kestra/core/models/triggers/PollingTriggerInterface.java (hunk 1 above)
Comment (loicmathieu) [reply core/src/main/java/io/kestra/core/models/triggers/PollingTriggerInterface.java]: Moreover, are you sure an ArithmeticException can be thrown here?

**Review by fhussonnois — CHANGES_REQUESTED** [review]
Please create a single method called by both methods. If `runContext` is `null`, it is best to continue logging the exception (with the trigger type).

Based on the initial problem, it would be good to check that the defined `interval` cannot result in an invalid date with a constraint validator.

**Review by fdelbrayelle — APPROVED** [review]

File: core/src/main/java/io/kestra/core/models/triggers/PollingTriggerInterface.java [hunk 3]
```diff
@@ -30,14 +35,38 @@ public interface PollingTriggerInterface extends WorkerTriggerInterface {
...
+            logger.warn("Trigger interval '{}' for type '{}' causes date overflow: {}. Using 60 seconds fallback.", interval, this.getClass().getName(), e.getMessage());
+            return ZonedDateTime.now().plus(Duration.ofSeconds(60));
+        }
+    }
+
+    private Logger resolveLogger(@Nullable RunContext runContext) {
+        if (runContext != null) {
+            return runContext.logger();
+        }
+        return LoggerFactory.getLogger(this.getClass());
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/models/triggers/PollingTriggerInterface.java]: Please use a static final logger here to avoid re-creating it each time the method is called

**Review by loicmathieu — CHANGES_REQUESTED** [review]

**Comment by anna-geller** [comment]
@Malaydewangan09 can you address the final feedback and merge? looks like this PR got stuck

File: core/src/main/java/io/kestra/core/models/triggers/PollingTriggerInterface.java (hunk 1 above)
Comment (Malaydewangan09) [reply core/src/main/java/io/kestra/core/models/triggers/PollingTriggerInterface.java]: Yes

**Comment by Malaydewangan09** [comment]
Hey Anna, yes, as decided, I'll update this to disable the trigger if this crash happens. I need to dig up a little on how to do that in core.
I'll close this shortly!

**Comment by Malaydewangan09** [comment]
@loicmathieu, could you please have a look, if this is a correct way to go forward? 🤔

File: scheduler/src/main/java/io/kestra/scheduler/AbstractScheduler.java [hunk 4]
```diff
@@ -537,6 +554,55 @@ private List<FlowWithTriggers> computeSchedulable(List<FlowWithSource> flows, Li
...
+
+            triggerQueue.emit(disabledTrigger);
+
+            schedulableNextDate.remove(disabledTrigger.uid());
+
+            synchronized (this) {
+                schedulable = schedulable.stream()
+                    .filter(f -> !f.getTriggerContext().uid().equals(disabledTrigger.uid()))
+                    .toList();
+            }
```
Comment (loicmathieu) [inline scheduler/src/main/java/io/kestra/scheduler/AbstractScheduler.java]: You don't need to do that, triggers are always taken from the triggerState (database or kafka store) so no need to mess with the schedulableNextDate and schedulable, those would be updated automatically.

**Review by loicmathieu — CHANGES_REQUESTED** [review]
As this is non trivial it would be great to have a test that would reproduce a failingf trigger and assert it's disabled in the triggerState after that

**Comment by Malaydewangan09** [comment]
Yes, I'll add just wanted to confirm this a correct way to go ahead!

File: scheduler/src/main/java/io/kestra/scheduler/AbstractScheduler.java (hunk 4 above)
Comment (Malaydewangan09) [reply scheduler/src/main/java/io/kestra/scheduler/AbstractScheduler.java]: Alright!

**Review by fdelbrayelle — APPROVED** [review]

**Comment by Malaydewangan09** [comment]
@loicmathieu, added test for the changes!

**Review by loicmathieu — APPROVED** [review]
LGTM
