### PR TITLE
fix(core): Handling for trailing slash in the KESTRA_URL configuration

### LINKED ISSUE #6041: Add handling for trailing slash in the KESTRA_URL configuration to avoid missing or double slash
### Describe the issue

When I executed a flow using the API, I got a response with a URL to Kestra that contained two slashes when only one was needed.

Flow:
```yaml
id: hello_world
namespace: company.team

inputs:
  - id: greeting
    type: STRING
    defaults: hey

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "{{ inputs.greeting }}"
```

API Request made in the terminal:

```sh
curl -X POST http://localhost:8084/api/v1/executions/company.team/hello_world
```

Response given:

```json
{
    "id": "6gTABm82mx5li7tHkgqyNU",
    "namespace": "company.team",
    "flowId": "hello_world",
    "flowRevision": 10,
    "inputs": {
        "greeting": "hey"
    },
    "labels": [
        {
            "key": "system.correlationId",
            "value": "6gTABm82mx5li7tHkgqyNU"
        }
    ],
    "state": {
        "current": "CREATED",
        "histories": [
            {
                "state": "CREATED",
                "date": "2024-11-21T16:35:36.815338221Z"
            }
        ],
        "duration": 0.012298625,
        "startDate": "2024-11-21T16:35:36.815338221Z"
    },
    "originalId": "6gTABm82mx5li7tHkgqyNU",
    "deleted": false,
    "metadata": {
        "attemptNumber": 1,
        "originalCreatedDate": "2024-11-21T16:35:36.815378387Z"
    },
    "url": "http://localhost:8084//ui/executions/company.team/hello_world/6gTABm82mx5li7tHkgqyNU"
}
```

Specifically the bottom line `url` has two `/` after the server URL. It should be:
`"url": "http://localhost:8084/ui/executions/company.team/hello_world/6gTABm82mx5li7tHkgqyNU"`

Should be a quick fix, and doesn't stop it working - just a minor bug.

### Environment

- Kestra Version: develop OSS 78f5ff2

### PR DESCRIPTION
**Pull request by benjoEK1337**
closes #6041
### What changes are being made and why?

---

This fix covers the cases when the trailing slash is added mistakenly to the configuration. It doesn't validate the whole URL, this could be considered in the future. 

This will be the behavior after this is merged.

Input: "http://localhost:8081/" -> Output: "http://localhost:8081"
Input: "http://localhost:8081" -> Output: "http://localhost:8081"
Input: "http://localhost:8081//" -> Output: "http://localhost:8081/" (because only the last slash is removed).

### How the changes have been QAed?

---

The tests in the `ExecutionControllerTest` are passing when the trailing slash is added to the kestra.url in the application-test.yml.

### CODE REVIEW

File: webserver/src/main/java/io/kestra/webserver/controllers/api/ExecutionController.java [hunk 1]
```diff
@@ -624,7 +624,10 @@ public Publisher<ExecutionResponse> create(
     }
 
     private URI executionUrl(Execution execution) {
-        return URI.create(kestraUrl.orElse("") + "/ui" + (execution.getTenantId() != null ? "/" + execution.getTenantId(): "")
+        String regexToRemoveTheTrailingSlashAtTheEnd = "/$";
+        String trimmedUrl = kestraUrl.orElse("").replaceAll(regexToRemoveTheTrailingSlashAtTheEnd, "");
+
+        return URI.create(trimmedUrl + "/ui" + (execution.getTenantId() != null ? "/" + execution.getTenantId(): "")
```
Comment (loicmathieu) [inline webserver/src/main/java/io/kestra/webserver/controllers/api/ExecutionController.java]:
```suggestion
        String baseUrl = kestraUrl.map(url -> url.endsWith("/") ? url.substring(0, url.length() - 1) : url).orElse("");
        return URI.create(baseUrl + "/ui" + (execution.getTenantId() != null ? "/" + execution.getTenantId(): "")
```

**Review by loicmathieu — APPROVED** [review]
Thanks for looking into it.
I proposed a more simple impl, I'll commit then merged it.
