### PR TITLE
fix/triple-hyphens-in-flows

### LINKED ISSUE #1634: Triple dash in attribute value can lead to incorrect validation
### Expected Behavior

Wrong regex leading to parsing --- everywhere instead of on a new line only

### Actual Behaviour

_No response_

### Steps To Reproduce

_No response_

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

_No response_

### PR DESCRIPTION
**Pull request by brian-mulier-p**
Also added tests for Flow validate controller

closes #1634

### CODE REVIEW

File: webserver/src/main/java/io/kestra/webserver/controllers/FlowController.java [hunk 1]
```diff
@@ -445,8 +445,8 @@ public List<ValidateConstraintViolation> validateFlows(
         @Parameter(description = "A list of flows") @Body String flows
     ) {
         AtomicInteger index = new AtomicInteger(0);
-        return Stream
-            .of(flows.split("---"))
+        List<ValidateConstraintViolation> collect = Stream
```
Comment (Skraye) [inline webserver/src/main/java/io/kestra/webserver/controllers/FlowController.java:448]: Directly returns the list

however, lgtm

**Review by Skraye — APPROVED** [review]

File: webserver/src/main/java/io/kestra/webserver/controllers/FlowController.java (hunk 1 above)
Comment (brian-mulier-p) [reply webserver/src/main/java/io/kestra/webserver/controllers/FlowController.java:448]: Ups, was for testing forgot it :+1:
