### PR TITLE
fix(*): Improve log timestamp precision + allow to override timestamp…

### LINKED ISSUE #5662: Logs showing out of order in the Logs page for remote task runners
### Describe the issue

```
"::{"logs": [{"level": "WARN", "message": "2024-10-25T16:09:45.419Z - Failed to upload Tag: <HttpError 400 when requesting https://tagmanager.googleapis.com/tagmanager/v2/accounts/xxx/containers/167765859/workspaces/22/tags/292?alt=json returned \"Invalid identifier: Link Click - Finance Start - Regex URL\". Details: \"[{'message': 'Invalid identifier: Link Click - Finance Start - Regex URL', 'domain': 'global', 'reason': 'badRequest'}]\">"}]}::"
```

This log does not show up with Kestra Python logging library, it shows 100% errors on TailLogEntries as well for Batch Task Runner.

This is using Python Kestra Library latest version (logger within it).

I also notice in GCP UI that 100% of tail log fetches in the hour this process ran failed 
image

I cannot find any GCP logs on the failed requests though.

### Environment

- Kestra Version: v0.19.2
- Operating System (OS/Docker/Kubernetes): Kestra Cloud
- Java Version (if you don't run kestra in Docker): n/a
 
```[tasklist]
### Tasks
- [ ] https://github.com/kestra-io/kestra/issues/7243
- [ ] https://github.com/kestra-io/kestra/issues/5915
- [ ] https://github.com/kestra-io/kestra/issues/6773
- [ ] https://github.com/kestra-io/kestra/issues/826
- [ ] https://github.com/kestra-io/kestra/issues/7226
- [ ] https://github.com/kestra-io/plugin-scripts/issues/216
- [ ] https://github.com/kestra-io/kestra/issues/2189
```

### LINKED ISSUE #5915: Log lines are out of order when viewing live logs
### Describe the issue

When viewing logs of a running flow (clicking "Execute" then "Logs") the lines are out of order, both by timestamp and expected order (see the flow below).
image

When the job is complete and I refresh the page the log lines are in the correct order, as expected.
image

The flow I'm using:
```yaml
id: run_playbook_DEBUG
namespace: company.team
inputs:
  - id: playbook
    type: STRING
    required: true
    description: Playbook name
    defaults: server-kestra-demo.yml
  - id: server
    type: MULTISELECT
    expression: "{{ kv('servers_debug') }}"
    required: true
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
  - id: ansible
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone_repository
        type: io.kestra.plugin.git.Clone
        url: <redacted>
        branch: master
      - id: test
        type: io.kestra.plugin.scripts.shell.Script
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
        containerImage: <redacted>
        script: |
          echo "hi"
          touch foo.txt
          echo "running playbook: {{ inputs.playbook }}"
          echo "on: {{ inputs.server | join(", ") }}"
          echo "bye"
```

### Environment

- Kestra Version: v0.19.10 using the provided docker compose file

### LINKED ISSUE #7243: The order of log entries in the Kestra interface is broken
### Describe the issue

I run python scripts in a docker container and print log. 
In Kestra inferface log lines are mixed up, the order is broken. 
I tryed diifferent ways to print logs, but it doesn't matter, which loger I use

```
# Example 1
for i in range(100):
    print(f"a_{i}")

# Example 2
from kestra import Kestra
logger = Kestra.logger()
for i in range(100):
    logger.info(f"c_{i}")
```

---------------------------------

```
id: sqlCreateSandbox
namespace: example
tasks:
- id: create
  type: "io.kestra.plugin.docker.Run"
  namespaceFiles:
    enabled: true
  containerImage: ghcr.io/merkle-dach/merklecdp-kestra-core-sql:dev
  credentials:
    auth: "{{ secret('DOCKER_CREDENTIALS') }}"
  commands:
    - /home/default/app/scripts/v1/app_test_kestra_logs.py    
```

---------------------------------

Image

### Environment

Kestra Version: 0.20.7
OS: Kubernetes

### PR DESCRIPTION
**Pull request by Skraye**
… in log consumer

close #5915
close #7243
close #5662

### CODE REVIEW

**Comment by loicmathieu** [comment]
I don't understand, you change the default datetime formatter to include microseconds instead of nanoseconds, this is OK and on par with Elasticsearch that already store microseconds precision.

Then you add to the log a new field, which is an SQL Timestamp (please, use something else, it's not related to SQL at all), and add it inside the log message itself which will be a bit strange. I would instead update the date formatting to include microseconds, seems easier. If `%d{HH:mm:ss.SSSSSS}` didn't work, we may need a custom date formater instead of adding nanos after a space which seems a bit odd.

**Comment by loicmathieu** [comment]
Logback do support microlevel date formatting, see https://logback.qos.ch/manual/layouts.html#date

**Comment by Skraye** [comment]
I think there is some confusion here : 
* I did change the formatter to display up to nanoseconds instead of milliseconds as per the ISO8601, as I thought using the more precise the better (albeit discovering later that JDBC stores up to the microseconds) but I can change for the other one 

* About the new field to the log, I think you're talking about the new method of the log consumer that also take a timestamp in input, its not related to the usual logging, its used for the task runner GCP so we can use the given timestamp of GCP (this way even if logs are streamed unordered, they will be ordered in the DB)

I can replace the Timestamp to Instant

**Comment by loicmathieu** [comment]
> I can replace the Timestamp to Instant

Yes please

**Comment by loicmathieu** [comment]
> I did change the formatter to display up to nanoseconds instead of milliseconds as per the ISO8601,

You didn't change the date formatter but added a new field nano.
The best would be to change the date formatter to use microseconds which should be enough.

So instead of

```
 <property name="pattern" value="%d{ISO8601} %nanos %highlight(%-5.5level) %magenta(%-12.36thread) %cyan(%-12.36logger{36}) %msg%n" />
```

Use microsecond precision in the date

```
 <property name="pattern" value="%date{HH:mm:ss}.%ms %highlight(%-5.5level) %magenta(%-12.36thread) %cyan(%-12.36logger{36}) %msg%n" />
```

File: core/src/main/java/io/kestra/core/runners/RunContextLogger.java [hunk 1]
```diff
@@ -41,6 +41,9 @@ public class RunContextLogger implements Supplier<org.slf4j.Logger> {
     @Getter
     private File logFile;
     private OutputStream logFileOS;
+    @Setter
+    @Getter
+    private Instant customInstant;
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/runners/RunContextLogger.java]: This is not a good idea as the logger is reused for multiple event.
The timestamp must be tied to a specific log event, not to the logger.
If the logger is used concurrently, one timestamp would override another.

File: core/src/main/java/io/kestra/core/models/tasks/runners/PluginUtilsService.java [hunk 2]
```diff
@@ -186,10 +185,12 @@ public static Map<String, Object> parseOut(String line, Logger logger, RunContex
                 if (bashCommand.getLogs() != null) {
                     bashCommand.getLogs().forEach(logLine -> {
                         try {
+                            if (customInstant != null) {
+                                runContext.setRunContextLoggerTimestamp(customInstant);
+                            }
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/models/tasks/runners/PluginUtilsService.java]: This is not a good idea, the timestamp must be passed inside the event not globally inside the logger, see my other comment for explanation.
For that, we may switch to the logback API instead of the SLF4J one.

**Review by loicmathieu — CHANGES_REQUESTED** [review]

File: core/src/main/java/io/kestra/core/logs/NanoConverter.java
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/logs/NanoConverter.java:1]: This seems not used anymore?

File: core/src/main/java/io/kestra/core/runners/RunContextLogger.java [hunk 3]
```diff
@@ -277,15 +278,26 @@ protected ILoggingEvent transform(ILoggingEvent event) {
             try {
                 String message = replaceSecret(event.getMessage());
                 Object[] argumentArray = replaceSecret(event.getArgumentArray());
-
-                return new LoggingEvent(
+                AtomicReference<Instant> customTimestamp = new AtomicReference<>();
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/runners/RunContextLogger.java]: Using entry.getKeyValuePairs.entrySet().stream().anyMatch() would avoid using an AtomicReference but it's not important so you can keep it as it.

File: core/src/main/resources/logback/text.xml [hunk 4]
```diff
@@ -1,5 +1,8 @@
 <?xml version="1.0" encoding="UTF-8"?>
 <included>
+    <conversionRule conversionWord="nanos"
```
Comment (loicmathieu) [inline core/src/main/resources/logback/text.xml]: You remove it right?

**Review by loicmathieu — APPROVED** [review]
LGTM
