### PR TITLE
fix(core): properly apply the saved filter containing date range.

### LINKED ISSUE #12501: Interval isn't saved in Saved filters
### Describe the issue

please reproduce and check: you can reproduce by setting custom interval in Interval filter, saving the filter and validating that interval isn't saved in the saved filter

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by Piyush-r-bhaskar**
Closes #12501

### CODE REVIEW

File: ui/src/components/filter/composables/useSavedFilters.ts [hunk 1]
```diff
@@ -1,73 +1,68 @@
...
-
-    const setStoredFilters = (filters: SavedFilter[]) => {
-        localStorage.setItem(storageKey.value, JSON.stringify(filters));
-        savedFilters.value = filters;
-    };
-
-    const loadSavedFilters = () => {
-        savedFilters.value = getStoredFilters();
-    };
+    const savedFilters = useLocalStorage<SavedFilter[]>(storageKey, [], {
```
Comment (elevatebart) [inline ui/src/components/filter/composables/useSavedFilters.ts]: `useLocalStorage` is deprecated in favor of `useStorage` that works just the same.

**Review by elevatebart — APPROVED** [review]
Looks good!

One nitpick that you can take or not.

File: ui/src/components/filter/composables/useSavedFilters.ts (hunk 1 above)
Comment (Piyush-r-bhaskar) [reply ui/src/components/filter/composables/useSavedFilters.ts]: And you are absolutely right. Why I missed that change 🤷
