### PR TITLE
fix(ui): add checkboxes when enabling multi-selection mode in FileExplorer

### LINKED ISSUE #8423: UI: Improve multi-select design in Namespace Files
### Feature description

When I select files using the Shift key, checkboxes appear.
If I select multiple files, when I try to delete them, it should clearly say 'Delete X files'.

Image

### PR DESCRIPTION
**Pull request by ef-molina**
### ✨ Description

What does this PR change?  
Adds checkboxes when enabling multi-select mode.

Users can:
- **Shift-click** to select a contiguous range of files using an anchor
- **Ctrl/Cmd-click** to toggle individual files
- Select files by clicking **anywhere on the row** or directly on the checkbox

Once two or more files are selected, the UI enters multi-select mode:
- Checkboxes become visible
- Modifier keys are no longer required to continue selecting or deselecting files
- Right-click preserves the current selection and reflects the correct count

The behavior mirrors common desktop file explorers and VS Code’s file tree UX.

### 🔗 Related Issue

Closes #8423 

### 🎨 Frontend Checklist

- [x] Code builds without errors (`npm run build`)
- [ ] All existing E2E tests pass (`npm run test:e2e`)
- [x] Screenshots or video recordings attached showing the `UI` changes

https://github.com/user-attachments/assets/aca192f1-7dc9-42b2-ba57-dee277966f54

### 📝 Additional Notes

This implementation was inspired by PR #11974, which was closed due to divergence, but followed the same UX direction.

Also, Range selection is currently computed over a flattened tree structure.

As a result:
- Shift-selecting **downward** from a collapsed folder includes its descendants in the selection
- Shift-selecting **upward** from a collapsed folder selects only the folder row itself
- Descendants included via downward selection become visible as selected once the folder is expanded

### CODE REVIEW

File: ui/src/components/inputs/FileExplorer.vue [hunk 1]
```diff
@@ -107,14 +107,14 @@
             lazy
             :load="filesStore.loadNodes"
             :data="filesStore.fileTree"
-            highlightCurrent
+            :highlightCurrent="false"
```
Comment (elevatebart) [inline ui/src/components/inputs/FileExplorer.vue]: Since hilightCurrent defaults to false you can simply omit it

https://element-plus.org/en-US/component/tree#attributes

```suggestion
```

File: ui/src/components/inputs/FileExplorer.vue [hunk 2]
```diff
@@ -107,14 +107,14 @@
...
             :allowDrop="
                 (_: any, drop: any, dropType: string) => !drop.data?.leaf || dropType !== 'inner'
             "
             draggable
             nodeKey="id"
             v-loading="filesStore.fileTree === undefined"
-            :props="{class: nodeClass, isLeaf: 'leaf'}"
+            :props="{class: nodeClass, isLeaf: 'leaf', key: 'id'}"
```
Comment (elevatebart) [inline ui/src/components/inputs/FileExplorer.vue]: What does this change do ? I do not see anything about a key in the `props` attribut of `<el-tree>`.
https://element-plus.org/en-US/component/tree#props

If it does nothing, can you remove it please?

File: ui/src/components/inputs/FileExplorer.vue [hunk 3]
```diff
@@ -499,42 +521,140 @@
         return result.filter(i => i.path);
     }
 
-    function handleNodeClick(data: any, node: ElTreeNode, event: MouseEvent | null = null) {
+    function handleNodeClick(data: any, node: ElTreeNode, event: MouseEvent | null = null, forceToggle = false) {
         const path = filesStore.getPath(node.data.id) ?? "";
-        const flatList = flattenTree(filesStore.fileTree);
+        const flatList = flatTree.value;
```
Comment (elevatebart) [inline ui/src/components/inputs/FileExplorer.vue:525]: Thank you !!! ❤️

File: ui/src/components/inputs/FileExplorer.vue [hunk 4]
```diff
@@ -929,11 +1036,13 @@
         }
 
         .node {
-            --el-tree-node-content-height: fit-content;
+            /* --el-tree-node-content-height: fit-content; */
```
Comment (elevatebart) [inline ui/src/components/inputs/FileExplorer.vue]: When you decide code should not be used, please remove it.
Outdated comments tend to create visual noise. They make relevant code harder to find.

```suggestion
```

**Review by elevatebart — CHANGES_REQUESTED** [review]
Great work!! 🎉 thank you much.

I have one UX ask though.
When a users starts to see checkboxes, they want to be able to exit from it quickly.
To turn off the checkboxes and unselect all other files, Users expect to click on the name of a file. Then everything should deselect.

Do you think it's possible?

There are also a few nitpicks, easy fixes.

Thank you again!

File: ui/src/components/inputs/FileExplorer.vue (hunk 2 above)
Comment (ef-molina) [reply ui/src/components/inputs/FileExplorer.vue]: Yes i will remove it i thought i needed this at first, but did not end up using it.

**Comment by ef-molina** [comment]
Thanks a lot for the feedback — that makes sense.

I can update the behavior so that when multi-select mode is active, a normal click on a file row (without Shift/Ctrl and outside the checkbox) will:

1. clear the current selection

2. exit multi-select mode (hide checkboxes)

3. select only the clicked file

4. open it as usual

Please let me know if I'm misunderstanding the desired behavior. 
I will work on this soon. 

note: I accidentally requested a review.

**Review by elevatebart — CHANGES_REQUESTED** [review]
So you can tell me when you are ready to get re-reviewed

**Comment by ef-molina** [comment]
Hi @elevatebart,

I’ve addressed the requested UX change so that a normal file click exits multi-select mode and opens the file, and cleaned up the noted nits (removed unused props, comments, and params).

Let me know if you’d like any further tweaks.

**Comment by ef-molina** [comment]
@elevatebart — quick FYI: I noticed the failing Storybook interaction in CI and verified it locally (InputsForm → InputTypes); it passes without changes on my end.

**Review by elevatebart — APPROVED** [review]
very good PR thanks for the work. Some nitpixks that can be handled later
