### PR TITLE
fix/hide-unwanted-things-vs-code

### LINKED ISSUE #2336: Remove "Accounts" setting at the bottom left

### LINKED ISSUE #2338: Disable the Run + Debug (Ctrl + Shift + D) icon on the left sidebar

### LINKED ISSUE #2339: Disable the Version Control extension by default

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes #2336
closes #2338
closes #2339

### CODE REVIEW

File: ui/public/init.js [hunk 1]
```diff
@@ -77,5 +77,13 @@ window.product = {
         "workbench.colorTheme": THEME === "dark" ? "Sweet Dracula" : "Default Light Modern",
         // provide the Kestra root URL to extension
         "kestra.api.url": KESTRA_API_URL
+    },
+    profile: {
+        name: "Kestra VSCode",
+        contents: "{\"globalState\":\"{\\\"storage\\\":{" +
```
Comment (Skraye) [inline ui/public/init.js:83]: Put it in a file for more readability

**Review by Skraye — CHANGES_REQUESTED** [review]

File: ui/public/init.js (hunk 1 above)
Comment (brian-mulier-p) [reply ui/public/init.js]: I moved them to a variable

**Review by Skraye — APPROVED** [review]
LGTM
