### PR TITLE
fix: Doc generation now takes the NotNull field from interface methods

### LINKED ISSUE #1145: Required properties should be listed first in Editor doc (webapp)
### Expected Behavior

Required properties should be listed first in doc for better visibility of what I should absolutely add to my task

### Actual Behaviour

Properties are listed as in POJO I guess

### Steps To Reproduce

1. Create a task with required & non-required properties (eg. https://kestra.io/plugins/plugin-azure/tasks/batch.job/io.kestra.plugin.azure.batch.job.Create.html)
2. job is listed after some non-required properties

### Environment Information

- Kestra Version: 0.8.0-SNAPSHOT
- Operating System (OS / Docker / Kubernetes): Mac
- Java Version (If not docker): 11

### Example flow

id: a-flow
namespace: some.namespace
tasks:
  - id: taskOne
    type: io.kestra.plugin.azure.batch.job.Create

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes #1145

### CODE REVIEW

File: core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java [hunk 1]
```diff
@@ -175,6 +175,7 @@ protected <T> void build(SchemaGeneratorConfigBuilder builder, Class<? extends T
         builder
 
             .with(new JavaxValidationModule(
+                JavaxValidationOption.NOT_NULLABLE_METHOD_IS_REQUIRED,
```
Comment (tchiotludo) [inline core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java:178]: maybe a little unit test ? to validate future non regression ?

**Review by tchiotludo — CHANGES_REQUESTED** [review]

File: core/src/main/java/io/kestra/core/docs/ClassPluginDocumentation.java [hunk 2]
```diff
@@ -125,7 +125,13 @@ private static Map<String, Object> flatten(Map<String, Object> map, List<String>
 
     @SuppressWarnings("unchecked")
     private static Map<String, Object> flatten(Map<String, Object> map, List<String> required, String parentName) {
-        Map<String, Object> result = new TreeMap<>();
+        Map<String, Object> result = new TreeMap<>((key1, key2) -> {
+            boolean key1Required = required.contains(key1);
+            boolean key2Required = required.contains(key2);
+            if(key1Required == key2Required) return key1.compareTo(key2);
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/docs/ClassPluginDocumentation.java:131]: As it's boolean it's more logical to use `&&` instead of `==` but you can keep it if you want.

**Review by loicmathieu — APPROVED** [review]
LGTM
