### PR TITLE
fix(flows): make autocomplete work in pebble

### LINKED ISSUE #9321: [Autocomplete] Some Pebble expressions (flow inputs and outputFiles on Script tasks) are not correctly autocompleted in No Code
### Describe the issue

https://jam.dev/c/25cb79f5-a5be-411b-89b2-14662125a8ef

### Environment

- Kestra Version: 

Image

### PR DESCRIPTION
**Pull request by elevatebart**
closes #9321, #9098

### CODE REVIEW

File: ui/src/composables/monaco/languages/pebbleLanguageConfigurator.ts [hunk 1]
```diff
@@ -0,0 +1,163 @@
...
+import IDisposable = monaco.IDisposable;
+import IModel = monaco.editor.IModel;
+import CompletionItem = languages.CompletionItem;
+
+
+export class PebbleLanguageConfigurator extends AbstractLanguageConfigurator {
+    private readonly _autoCompletion: PebbleAutoCompletion;
+    private readonly _injectedYaml: ComputedRef<string | undefined>;
+
+    constructor(autoCompletion: PebbleAutoCompletion, injectedYaml: ComputedRef<string | undefined>) {
```
Comment (brian-mulier-p) [inline ui/src/composables/monaco/languages/pebbleLanguageConfigurator.ts]:
```suggestion
    constructor(autoCompletion: PebbleAutoCompletion, completionSource: ComputedRef<string | undefined>) {
```

File: ui/src/composables/monaco/languages/pebbleLanguageConfigurator.ts [hunk 2]
```diff
@@ -0,0 +1,163 @@
...
+                const startOfWordColumn = position.column - rootPebbleVariableMatcher.matches[1].length;
+                return {
+                    suggestions: (await (yamlAutoCompletion.rootFieldAutoCompletion()))
+                        .map(s => propertySuggestion(s, {
+                            lineNumber: position.lineNumber,
+                            startColumn: startOfWordColumn,
+                            endColumn: endOfWordColumn(position, model)
+                        }))
+                };
+            }
```
Comment (brian-mulier-p) [inline ui/src/composables/monaco/languages/pebbleLanguageConfigurator.ts]: I'd advise to put this method and the below ones in some public methods and reuse them in YamlLanguageConfigurator as it makes sense due to how related it is to the Pebble and avoid duplication.

If you don't have the will to please add a follow-up for cleaning things :+1:

**Review by brian-mulier-p — APPROVED** [review]
LGTM beside few remarks
