### PR TITLE
fix(executions): concurrency limit exceeded when restarting an execution

### LINKED ISSUE #7880: Able to bypass the concurrency limit by restarting failed executions
### Describe the issue

https://jam.dev/c/8243417f-1836-491e-b40f-82d46f594412
Concurrency limits are used to prevent too heavy loads on the workers or the services it's accessing, it shouldn't be possible to override this limit no matter what you do, restarted executions should still follow the setted rule.

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by loicmathieu**
Fixes #7880

I created a method in the State to know when an execution has been restarted from a failure to disambiguate between restarted from the UI/API and restarted from a PAUSE.
This is unfortunate that both uses the same RESTARTED state.

### CODE REVIEW

File: core/src/test/java/io/kestra/core/runners/FlowConcurrencyCaseTest.java [hunk 1]
```diff
@@ -278,6 +282,66 @@ public void flowConcurrencyWithForEachItem() throws TimeoutException, QueueExcep
...
+        assertThat(execution1.getState().isRunning()).isTrue();
+        assertThat(execution2.getState().getCurrent()).isEqualTo(State.Type.CREATED);
+
+        var executionResult1  = new AtomicReference<Execution>();
+        var executionResult2  = new AtomicReference<Execution>();
+
+        CountDownLatch latch1 = new CountDownLatch(2);
+        AtomicReference<Execution> failedExecution = new AtomicReference<>();
+        CountDownLatch latch2 = new CountDownLatch(1);
+        CountDownLatch latch3 = new CountDownLatch(1);
```
Comment (brian-mulier-p) [inline core/src/test/java/io/kestra/core/runners/FlowConcurrencyCaseTest.java:302]:
```suggestion
        CountDownLatch execution1FailedLatch = new CountDownLatch(2);
        AtomicReference<Execution> failedExecution = new AtomicReference<>();
        CountDownLatch execution2RunningLatch = new CountDownLatch(1);
        CountDownLatch execution2FailedLatch = new CountDownLatch(1);
```

File: core/src/test/java/io/kestra/core/runners/FlowConcurrencyCaseTest.java [hunk 2]
```diff
@@ -278,6 +282,66 @@ public void flowConcurrencyWithForEachItem() throws TimeoutException, QueueExcep
...
+            if (e.getLeft().getId().equals(execution2.getId())) {
+                executionResult2.set(e.getLeft());
+                if (e.getLeft().getState().getCurrent() == State.Type.RUNNING) {
+                    latch2.countDown();
+                }
+                if (e.getLeft().getState().getCurrent() == Type.FAILED) {
+                    latch3.countDown();
+                }
+            }
+        });
```
Comment (brian-mulier-p) [inline core/src/test/java/io/kestra/core/runners/FlowConcurrencyCaseTest.java:322]: To avoid introducing too much flakiness, I suggest putting that receive between line 290 & 291 to start listening asap and avoid missing something

File: core/src/test/java/io/kestra/core/runners/FlowConcurrencyCaseTest.java [hunk 3]
```diff
@@ -278,6 +282,66 @@ public void flowConcurrencyWithForEachItem() throws TimeoutException, QueueExcep
...
+        assertTrue(latch2.await(1, TimeUnit.MINUTES));
+        assertThat(failedExecution.get()).isNotNull();
+        // here the first fail and the second is now running.
+        // we restart the first one, it should be queued then fail again.
+        Execution restarted = executionService.restart(failedExecution.get(), null);
+        executionQueue.emit(restarted);
+
+        assertTrue(latch3.await(1, TimeUnit.MINUTES));
+        assertTrue(latch1.await(1, TimeUnit.MINUTES));
+        receive.blockLast();
```
Comment (brian-mulier-p) [inline core/src/test/java/io/kestra/core/runners/FlowConcurrencyCaseTest.java:333]: this doesn't ensure the concurrency limit was respected as the first execution could have been run before the second execution was failed. I suggest using a thread to wait for the latch3 in another 3 and make sure that it asserts before the first latch, in fact I think you even miss another latch for execution 1 running which would allow you to make sure you're not running execution 1 restart before the execution 2 fails

Comment (brian-mulier-p) [reply core/src/test/java/io/kestra/core/runners/FlowConcurrencyCaseTest.java:333]: I think just checking that there was a QUEUED state is not enough, we should make sure the transition from QUEUED to RUNNING is not performed before the actual ending of the execution 2. Idk if there is another test that covers that in fact. If there is, ok with the current check.

**Review by brian-mulier-p — CHANGES_REQUESTED** [review]
Small changes to the tests

File: core/src/test/java/io/kestra/core/runners/FlowConcurrencyCaseTest.java (hunk 2 above)
Comment (loicmathieu) [reply core/src/test/java/io/kestra/core/runners/FlowConcurrencyCaseTest.java:322]: Not possible as it needs the executionId of executions created just before.
There is a sleep in those tests so it should not be flaky except if the JVM make a big pause between them...

File: core/src/test/java/io/kestra/core/runners/FlowConcurrencyCaseTest.java (hunk 3 above)
Comment (loicmathieu) [reply core/src/test/java/io/kestra/core/runners/FlowConcurrencyCaseTest.java:333]: > this doesn't ensure the concurrency limit was respected as the first execution could have been run before the second execution was failed

It's not what we test here as this is covered by the standard concurrenct limit test.
WHat we test here is that restart respect concurrency limit

>  I think you even miss another latch for execution 1 running which would allow you to make sure you're not running execution 1 restart before the execution 2 fails

I wait for the execution 1 to be in running, then to the second to be in running. Then I assert that 1 fail. I think it's enough.

>  we should make sure the transition from QUEUED to RUNNING is not performed before the actual ending of the execution 2. Idk if there is another test that covers that in fact

As I previously said, this is covered by the standard test, this one only test that a restart didn't exceed the concurrency limit so asserting QUEUED is enought.

**Review by brian-mulier-p — APPROVED** [review]
