### PR TITLE
ui(fix): change namespace hover to white

### LINKED ISSUE #8821: Namespace: In light mode, the namespaces' background should be set to white.
### Describe the issue

Image

👇👇

Image

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by starlightknown**
### What changes are being made and why?

closes #8821 

https://github.com/user-attachments/assets/c85dca70-301a-4e02-b1fb-691a7b4b3bb2

---

### How the changes have been QAed?

---

### CODE REVIEW

File: ui/src/components/namespaces/Namespaces.vue [hunk 1]
```diff
@@ -209,7 +209,11 @@
         border-radius: var(--bs-border-radius-lg);
 
         &:hover {
-            background: var(--ks-background-body);
+            background: $base-white;
```
Comment (Piyush-r-bhaskar) [inline ui/src/components/namespaces/Namespaces.vue]: Keep it as it is.

**Review by Piyush-r-bhaskar — CHANGES_REQUESTED** [review]
Just add 

`background-color: var(--ks-background-card)`  under `.rounded-full`

**Comment by starlightknown** [comment]
made the change

**Review by Piyush-r-bhaskar — APPROVED** [review]
LGTM
