### PR TITLE
Fix: Concurrency limit display alignment

### LINKED ISSUE #14057: Backfill and ConcurrencyLimit are not aligned
### Describe the issue

Using the following flow and creating a backfill over many previous days gives the following behavior:
- all backfill execution enter the queue as expected
- concurrency level is respected (as seen in screenshot)

However:
- The concurrency tab doesn't show active slot being used but we can there are 3 running execution

Image

Image

```yaml
id: concurrency_level
namespace: kestra.qa
concurrency:
  behavior: QUEUE
  limit: 3
tasks:
  - id: sleep
    type: io.kestra.plugin.core.flow.Sleep
    duration: PT40S
triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "* * * * *"
    allowConcurrent: true
```

Expected behavior: the concurrenc tab should align with what have been sent by the backfill operation and display active slots accordingly

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by saifxyzyz**
Closes https://github.com/kestra-io/kestra/issues/14057.

### ✨ Description

What does this PR change?  
Fetches concurrently running executions from the api, and displays them in the concurrency tab

### 🔗 Related Issue

Which issue does this PR resolve?  
#14057 

Before: 
533296275-2eeec802-7e3e-433b-ab1c-89a8e50644b5

After:  
image

### 🎨 Frontend Checklist

_If this PR does not include any frontend changes, delete this entire section._

- [ ] Code builds without errors (`npm run build`)
- [ ] All existing E2E tests pass (`npm run test:e2e`)
- [ ] Screenshots or video recordings attached showing the `UI` changes

### 🛠️ Backend Checklist

_If this PR does not include any backend changes, delete this entire section._

- [ ] Code compiles successfully and passes all checks
- [ ] All unit and integration tests pass

### 📝 Additional Notes

Add any extra context or details reviewers should be aware of.

### CODE REVIEW

File: ui/src/components/flows/FlowConcurrency.vue [hunk 1]
```diff
@@ -20,48 +20,97 @@
                     :topbar="false"
                     :namespace="flowStore.flow?.namespace"
                     :flowId="flowStore.flow?.id"
-                    isConcurrency
```
Comment (MilosPaunovic) [inline ui/src/components/flows/FlowConcurrency.vue:23]: Why remove this property and the 2 below?

**Review by MilosPaunovic — CHANGES_REQUESTED** [review]

File: ui/src/components/flows/FlowConcurrency.vue (hunk 1 above)
Comment (saifxyzyz) [reply ui/src/components/flows/FlowConcurrency.vue:23]: Its no longer needed as the script now fetches data from the backend

**Review by MilosPaunovic — APPROVED** [review]
