### PR TITLE
fix(ui): make plugins pages responsive

### LINKED ISSUE #12752: Plugins pages is unusable on mobile
https://github.com/user-attachments/assets/50f3814d-4abe-43c4-9ca0-ea7063079fb5

### PR DESCRIPTION
**Pull request by aighita**
### What changes are being made and why?

Closes #12752.

Plugins pages mobile responsive. Sidebar is not displayed on mobile. A hamburger icon is in turn displayed on the right side, not overlapping the docs.

---

### How the changes have been QAed?

https://github.com/user-attachments/assets/4b2b622c-6601-43c5-a34f-d5d3723b3fc6

### CODE REVIEW

File: ui/src/components/plugins/PluginDocumentation.vue [hunk 1]
```diff
@@ -102,5 +102,89 @@
 </script>
 
 <style scoped lang="scss">
+    @import "@kestra-io/ui-libs/src/scss/variables";
```
Comment (Piyush-r-bhaskar) [inline ui/src/components/plugins/PluginDocumentation.vue]: remove changes from this file. We don't need this 🚀

File: ui/src/components/plugins/PluginDocumentationWrapper.vue [hunk 2]
```diff
@@ -13,18 +13,42 @@
 </script>
 
 <style scoped lang="scss">
+@import "@kestra-io/ui-libs/src/scss/variables";
```
Comment (Piyush-r-bhaskar) [inline ui/src/components/plugins/PluginDocumentationWrapper.vue]: remove changes from this file.

File: ui/src/components/plugins/PluginList.vue [hunk 3]
```diff
@@ -294,45 +294,53 @@
 </script>
 
 <style scoped lang="scss">
+@import "@kestra-io/ui-libs/src/scss/variables";
```
Comment (Piyush-r-bhaskar) [inline ui/src/components/plugins/PluginList.vue]: remove changes from this file.

File: ui/src/components/plugins/PluginUnified.vue [hunk 4]
```diff
@@ -183,13 +183,15 @@
 </script>
 
 <style scoped lang="scss">
```
Comment (Piyush-r-bhaskar) [inline ui/src/components/plugins/PluginUnified.vue:185]: remove changes from this file.

File: ui/src/components/docs/DocsLayout.vue [hunk 5]
```diff
@@ -1,15 +1,51 @@
...
-                <span class="toggle-btn text-body-tertiary">{{ $t((collapsed ? 'open' : 'close') + ' sidebar').toUpperCase() }}</span>
-            </div>
-            -->
+        <button 
+            v-if="$slots.menu" 
+            :class="['mobile-menu-toggle', {'menu-open': mobileMenuOpen}]"
+            @click="mobileMenuOpen = !mobileMenuOpen"
+            :aria-label="mobileMenuOpen ? 'Close menu' : 'Open menu'"
+        >
+            <svg
```
Comment (Piyush-r-bhaskar) [inline ui/src/components/docs/DocsLayout.vue]: No direct svg Please use icons from https://pictogrammers.com/library/mdi/

You may take reference how project is importing at other place.

**Review by Piyush-r-bhaskar — CHANGES_REQUESTED** [review]
Good work on this @aighita . Thanks You 🚀

Few points to tackle before merge and you should be looking for correct file which is `/ui/src/components/plugins/Plugin.vue`

- Handle this bg-color difference.

Image

- I would love to fix the title and hamburger and scroll should start from below that and also try to make the overflowing ellipsis.

Image

- Similar as above make the search and close button fix as header and scroll should start from below.

Image

- I see the Hamburger is appearing inside Right Context bar Doc / News..Need to remove

Image

File: ui/src/components/docs/DocsLayout.vue [hunk 6]
```diff
@@ -1,15 +1,51 @@
...
-            <!--
-            <div class="d-flex gap-2 align-items-center">
-                <el-button @click="collapsed = !collapsed">
-                    <chevron-right v-if="collapsed" />
-                    <chevron-left v-else />
-                </el-button>
-                <span class="toggle-btn text-body-tertiary">{{ $t((collapsed ? 'open' : 'close') + ' sidebar').toUpperCase() }}</span>
-            </div>
-            -->
+        <button
```
Comment (Piyush-r-bhaskar) [inline ui/src/components/docs/DocsLayout.vue]: You may use icon type `el-button`

File: ui/src/components/docs/DocsLayout.vue (hunk 5 above)
Comment (aighita) [reply ui/src/components/docs/DocsLayout.vue]: Replaced with Menu and Close. See: DocsLayout.vue

File: ui/src/components/docs/DocsLayout.vue (hunk 6 above)
Comment (aighita) [reply ui/src/components/docs/DocsLayout.vue]: Replaced button with el-button. See: DocsLayout.vue

File: ui/src/components/plugins/PluginDocumentationWrapper.vue (hunk 2 above)
Comment (aighita) [reply ui/src/components/plugins/PluginDocumentationWrapper.vue]: I need more context. Just the import or every change? I added the imports after commit https://github.com/kestra-io/kestra/pull/12829/commits/c7a859aaa7684c012593d1c7958772a73ca9529f because front-end tests failed.
Same for PluginList.vue and PluginUnified.vue?

**Comment by aighita** [comment]
* Replaced button with el-button.
* Replaced SVG with https://pictogrammers.com/library/mdi/.
* Removed changes from requested files.
* Handled bg color difference.
* Fixed title and menu icon.
* Scroll bar start from below the title and menu icon header.
* Conditionally render the hamburger menu and close buttons on plugins route as they are used in DocsLayout.vue but that component might be used in other parts too. Wasn't quite clear for me where exactly Right Context bar Doc / News.. was in the picture you provided so I see this the best fix as that menu is only used in the plugins page.

As a result of these changes desktop styles were affected too: title is now fixed on scroll on any device. Scroll bar starts under the title container.

QA

https://github.com/user-attachments/assets/73e31367-6e9f-4a7a-9271-306be3117662

File: ui/src/components/plugins/PluginDocumentation.vue (hunk 1 above)
Comment (aighita) [reply ui/src/components/plugins/PluginDocumentation.vue]: will do

**Review by Piyush-r-bhaskar — CHANGES_REQUESTED** [review]
@aighita  I see your changes are applied on large screen as well. could you inly make changes which target small screens

and keep the icon size as it is.

**Comment by aighita** [comment]
@Piyush-r-bhaskar 

Title + Release Notes shouldn't be fixed/sticky on large screen?

Icon size keep as is meaning revert to it's original size before my changes? 

Which icon are you referring to? From plugin title (ex in the video: Docker icon) or hamburger icon?

**Comment by Piyush-r-bhaskar** [comment]
Yes , should not be sticky on large screen.

and I mean Plugin icon/image beside title.

**Comment by aighita** [comment]
@Piyush-r-bhaskar

**Comment by MilosPaunovic** [comment]
Hey @Piyush-r-bhaskar, can you check this one again when you get the chance?

**Review by Piyush-r-bhaskar — APPROVED** [review]
LGTM 🚀. Thank you for your contribution @aighita  🎉
