### PR TITLE
fix(ui): Display flow triggers in overview page

### LINKED ISSUE #1461: Add the autogenerated webhook key to the Flow details page
### Expected Behavior

According to the documentation, a webhook secret key would be generated automatically based on a generated hash. 

Mimimum example:

```yaml
id: ci-cd
namespace: prod
tasks:
  - id: log
    type: io.kestra.core.tasks.log.Log
    message: test
triggers:
  - id: github-webhook
    type: io.kestra.core.models.triggers.types.Webhook
    key: "thisIsASecretKey123" # using "{{secret('WEBHOOK_KEY')}}" doesn't work atm
```

### Actual Behaviour

Currently, this doesn't happen. 

Passing the key from a secret also currently doesn't work.

image

### Steps To Reproduce

_No response_

### Environment Information

- Kestra Version: 0.9.3 develop-full image, EE also

### Example flow

_No response_

### PR DESCRIPTION
**Pull request by Skraye**
close #1461

### CODE REVIEW

File: ui/src/components/home/Home.vue [hunk 1]
```diff
@@ -32,6 +32,10 @@
 
             <home-description v-if="namespace" :description="description" class="mb-4" />
 
+            <div v-if="flow && flow.triggers">
+                <home-trigger :triggers="flow.triggers" class="mb-4" />
+            </div>
```
Comment (brian-mulier-p) [inline ui/src/components/home/Home.vue:37]:
```suggestion
            <home-trigger v-if="flow?.triggers" :triggers="flow.triggers" class="mb-4" />
```

File: ui/src/components/home/HomeTrigger.vue [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+                <el-table :data="triggers" stripe table-layout="auto">
+                    <el-table-column v-for="prop in columns" :key="prop" :prop="prop" :label="getLabel(prop)" />
+                    <el-table-column :label="$t('description')">
+                        <template #default="scope">
+                            <Markdown :source="scope.row.description" />
+                        </template>
+                    </el-table-column>
+                </el-table>
+            </div>
+        </div>
```
Comment (brian-mulier-p) [inline ui/src/components/home/HomeTrigger.vue:14]:
```suggestion
        <el-table :data="triggers" stripe table-layout="auto">
            <el-table-column v-for="prop in columns" :key="prop" :prop="prop" :label="getLabel(prop)" />
            <el-table-column :label="$t('description')">
                <template #default="scope">
                    <Markdown :source="scope.row.description" />
                </template>
            </el-table-column>
        </el-table>
```

**Review by brian-mulier-p — CHANGES_REQUESTED** [review]
Small changes

**Review by brian-mulier-p — APPROVED** [review]
LGTM
