### PR TITLE
fix(ui): open link in markdown in other tab.

### LINKED ISSUE #8213: Open links from plugin docs page in a new tab
### Describe the issue

At the moment, the links in [here](https://github.com/kestra-io/kestra/blob/develop/ui/src/assets/docs/basic.md) and probably other plugin docs that have them (not too many do), will just redirect the existing kestra page to that external page. Would be good if we can have it open a new tab, or have an option to decide the behaviour in Settings like "Open links in docs in new tab" etc.

Image

### Environment

- Kestra Version: `develop`

### PR DESCRIPTION
**Pull request by Piyush-r-bhaskar**
Closes #8213

### CODE REVIEW

File: ui/src/utils/markdown.ts [hunk 1]
```diff
@@ -39,6 +39,7 @@ export async function render(markdown: string, options: {onlyLink?: boolean, per
 
     md.use(mark)
         .use(meta)
+        .use(mila, {attrs: {target: "_blank", rel: "noopener noreferrer"}})
```
Comment (elevatebart) [inline ui/src/utils/markdown.ts]: Can we restrict these attributes to external links?

```suggestion
        .use(mila, {matcher: (href) => href.match(/^https?:\/\//), attrs: {target: "_blank", rel: "noopener noreferrer"}})
```

**Review by elevatebart — APPROVED** [review]
Good work,
A small suggestion and you can merge.
