### PR TITLE
fix(executions): make columns that are not links normal text

### LINKED ISSUE #10456: Change text of Revision and Task ID columns on Executions page to white as those show simple text, not clickable URLs
### Describe the issue

Image

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by Piyush-r-bhaskar**
Closes https://github.com/kestra-io/kestra/issues/10456

### CODE REVIEW

File: ui/src/components/executions/Executions.vue [hunk 1]
```diff
@@ -260,7 +260,7 @@
                             class-name="shrink"
                         >
                             <template #default="scope">
-                                <code>{{ scope.row.flowRevision }}</code>
+                                <span>{{ scope.row.flowRevision }}</span>
```
Comment (elevatebart) [inline ui/src/components/executions/Executions.vue]: How did you manage to keep the monospace appearance?

i understand why the purple should go but we need to keep the monospace.

Maybe the problem is that `<code>` should not be purple.

**Review by elevatebart — CHANGES_REQUESTED** [review]
Simple enough but I am weary of it as it is.

**Review by elevatebart — APPROVED** [review]
