### PR TITLE
fix(core): collapse menu automagically on route change

### LINKED ISSUE #12750: Close the left menu on mobile
https://github.com/user-attachments/assets/03b44de3-8f8e-4dd9-8ffc-ac08472e7623

We need to close the menu when the route change on mobile

### PR DESCRIPTION
**Pull request by shatrughantwt**
### What changes are being made and why?
Closes #12750  
- Added onMounted() block that listens for clicks on sidebar links.  
- When clicked on mobile screens (<768px), the sidebar automatically closes.  
- Also updates localStorage to remember the collapse state for a consistent UX.

### How the changes have been QAed?
- Opened app on mobile view.
- Clicked on sidebar links → sidebar closes automatically.
- Verified layout remains consistent on larger screens.

### CODE REVIEW

**Review by Piyush-r-bhaskar — CHANGES_REQUESTED** [review]
Hey @shatrughantwt 

Thanks for this 🚀

One more issue to fix then we are good- When I am opening the App first time on route changes I  see menu collapsing is not working. Can you fix ?

**Comment by shatrughantwt** [comment]
@Piyush-r-bhaskar, Yes. I can fix.

**Comment by shatrughantwt** [comment]
@Piyush-r-bhaskar, Done.

File: ui/src/components/layout/SideBar.vue [hunk 1]
```diff
@@ -31,99 +31,150 @@
...
+                        ]
+                    }
+                ]
+                : []),
             ...(props.menu ? disabledCurrentRoute(props.menu) : [])
         ];
     });
 
-    const collapsed = ref(localStorage.getItem("menuCollapsed") === "true")
+    function attachLinkListeners() {
```
Comment (Piyush-r-bhaskar) [inline ui/src/components/layout/SideBar.vue]: why we need this exactly ?

**Review by Piyush-r-bhaskar — APPROVED** [review]
LGTM
