### PR TITLE
fix(core): bring back radio styles.

### LINKED ISSUE #9103: Color of selected radio button is not visible, please change it
### Describe the issue

Image

use `ks-content-link` ?

Image

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by Piyush-r-bhaskar**
Closes #9103

### CODE REVIEW

File: ui/src/components/flows/tasks/TaskAnyOf.vue [hunk 1]
```diff
@@ -1,5 +1,5 @@
 <template>
-    <el-form-item :class="{'radio-wrapper':isSelectingPlugins}">
+    <el-form-item :class="{'radio-wrapper':isSelectingPlugins || true}">
```
Comment (elevatebart) [inline ui/src/components/flows/tasks/TaskAnyOf.vue]: Woops

```suggestion
    <el-form-item :class="{'radio-wrapper':!isSelectingPlugins}">
```

**Review by elevatebart — APPROVED** [review]
Apply the change and you're golden
