### PR TITLE
fix(core): amend keyboard save shortcut for both flow and namespace files

### LINKED ISSUE #9025: Cannot Save flow with Cmd + S keyboard shortcut
to reproduce, go to create flow and try to hit Cmd + S, it has no effect

Image

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by MilosPaunovic**
Closes https://github.com/kestra-io/kestra/issues/9025.

### CODE REVIEW

File: ui/src/components/inputs/EditorWrapper.vue [hunk 1]
```diff
@@ -122,6 +124,22 @@
...
+    const save = async () => {
+        const result = await store.dispatch("flow/save", {content: editorDomElement.value.$refs.monacoEditor.value})
+        if(result === "redirect_to_update"){
+            await router.push({
+                name: "flows/update",
+                params: {
+                    id: flowParsed.value.id,
+                    namespace: flowParsed.value.namespace,
+                    tab: "edit",
+                    tenant: router.currentRoute.value.params.tenant,
```
Comment (elevatebart) [inline ui/src/components/inputs/EditorWrapper.vue]: why not use `useRoute()` instead of `useRouter()` to get the route?

**Review by elevatebart — APPROVED** [review]
one nitpick/question

File: ui/src/components/inputs/EditorWrapper.vue (hunk 1 above)
Comment (MilosPaunovic) [reply ui/src/components/inputs/EditorWrapper.vue]: No other reason than copying the logic form `EditorView.vue` component. Amended now, as it totally makes sense.
