### PR TITLE
Fix(Webserver) #6225 Added check in file creation path for _flows*

### LINKED ISSUE #6225: Kestra allows Files and Folders to be created with _flows* name
**Description**

I was able to create _flows* files and directories in Kestra, even though it should, by default, prevent the creation of such files. Additionally, it should block the creation of _flows* folders. I was able to bypass these restrictions by performing the following actions:

**Steps**

- Step1:  Create a sample flow
- Step2: Edit the flow in editor and expand the file creation tab
- Step3:  Click on create file
- Step4: give the filepath as  "_flows" or "_flows2" or "_flows3/test.txt" (all of them invalid files or file paths)

image

You will notice that the file and directory are created. However, the directory (_flows3) is inaccessible due to the forbiddenPathsGuard(URI path) function, even though it has been created.

This check should be added in the file creation path as well.

OS:
Windows 11

### Environment

- Kestra Version: develop

### I have made the changes to tackle this issue and will raise the PR once this has been approved as an issue.

### PR DESCRIPTION
**Pull request by coderkill**
### What changes are being made and why?

Kestra allows the creation of files and directories with names starting with _flows*, despite the system's default restrictions intended to prevent such creations. Additionally, it fails to block the creation of folders starting with _flows*. 

### How the changes have been QAed?

I manually tested these examples:
Invalid Files and directories test cases:
image
image
image

Subfolder _flows* check:
image

Positive Test case
image

Note that this is not a replacement for unit tests but rather a way to demonstrate how the changes work in a real-life scenario, as the end-user would experience them.

closes #6225

### CODE REVIEW

**Comment by loicmathieu** [comment]
Hi,
Thanks for doing this.
I wonder if it would makes sense to only prevent files starting with `_flows` inside of containing. @brian-mulier-p WDYT?

It needs a test inside the existing NamespaceFileController test.

I also wonder if we should not do the same check in the UI to warn the user before he try to save the file. This is best practice, we usually duplicate this kind of checks in the UI and in the backend.

**Comment by coderkill** [comment]
> Hi, Thanks for doing this. I wonder if it would makes sense to only prevent files starting with `_flows` inside of containing. @brian-mulier-p WDYT?
> 
> It needs a test inside the existing NamespaceFileController test.
> 
> I also wonder if we should not do the same check in the UI to warn the user before he try to save the file. This is best practice, we usually duplicate this kind of checks in the UI and in the backend.

Hi,

I would be happy to write the test case but I am not able to run them on my local so hence wasnt able to do it:

I am getting the following error when running NamespaceFileControllerTest on local inside Intellij:
```

Bean definition [io.kestra.webserver.services.BasicAuthService] could not be loaded: Failed to inject value for parameter [dslContext] of class: io.kestra.jdbc.JooqDSLContextWrapper

Message: Multiple possible bean candidates found: [DSLContext, DSLContext]
Path Taken: new BasicAuthService() --> BasicAuthService.settingRepository --> new H2SettingRepository([H2Repository<Setting T> repository],ApplicationContext applicationContext) --> new H2Repository(JdbcTableConfig jdbcTableConfig,QueueService queueService,[JooqDSLContextWrapper dslContextWrapper]) --> new JooqDSLContextWrapper([DSLContext dslContext],RetryUtils retryUtils)
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [io.kestra.webserver.services.BasicAuthService] could not be loaded: Failed to inject value for parameter [dslContext] of class: io.kestra.jdbc.JooqDSLContextWrapper

Message: Multiple possible bean candidates found: [DSLContext, DSLContext]
Path Taken: new BasicAuthService() --> BasicAuthService.settingRepository --> new H2SettingRepository([H2Repository<Setting T> repository],ApplicationContext applicationContext) --> new H2Repository(JdbcTableConfig jdbcTableConfig,QueueService queueService,[JooqDSLContextWrapper dslContextWrapper]) --> new JooqDSLContextWrapper([DSLContext dslContext],RetryUtils retryUtils)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:2000)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:314)
	at io.micronaut.context.DefaultBeanContext.configureAndStartContext(DefaultBeanContext.java:3318)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:345)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:216)
	at io.micronaut.test.extensions.AbstractMicronautExtension.startApplicationContext(AbstractMicronautExtension.java:507)
	at io.micronaut.test.extensions.AbstractMicronautExtension.beforeClass(AbstractMicronautExtension.java:346)
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.beforeAll(MicronautJunit5Extension.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [dslContext] of class: io.kestra.jdbc.JooqDSLContextWrapper

```
Is there something I am doing wrong?

**Comment by loicmathieu** [comment]
No, I'm not sure why you have this issue, you can start a discussion on our Slack on the contributors channels so we can help troubleshoot this test run issue.

**Comment by coderkill** [comment]
I have tried posting the error on slack but to no avail, I have written the test cases but I am not able to run it due to the above error. It seems to be happening for all controller test classes.

**Comment by coderkill** [comment]
I have pushed my test case as requested

**Review by loicmathieu — COMMENTED** [review]
LGTM however I want to discuss if we should not switch to startWith and duplicate the check in the UI internally before merging it.

**Comment by brian-mulier-p** [comment]
Hello ! Makes sense to use startsWith, just mind about the leading "/" of namespace files :)

**Comment by coderkill** [comment]
I have done some analysis, The difference in using startsWith from regex is that you will be able to create subfolders with the keyword _flows using startsWith. eg: /abc/_flows is a valid path. The same applies to files. eg /abc/_flows.txt is a valid file. The previous regex logic would stop it. I have made the changes on my local and tested them out.

**Comment by coderkill** [comment]
Proof of fix:

image
image
image
image

**Comment by coderkill** [comment]
The Junit tests have passed, something else has caused the build to fail

**Comment by coderkill** [comment]
Hi,

Any update on this?

File: webserver/src/main/java/io/kestra/webserver/controllers/api/NamespaceFileController.java [hunk 1]
```diff
@@ -183,8 +181,12 @@ public synchronized int available() {
 
     private void putNamespaceFile(String tenantId, String namespace, URI path, BufferedInputStream inputStream) throws IOException {
         String filePath = path.getPath();
-        if(filePath.matches("/" + FLOWS_FOLDER + "/.*")) {
-            if(filePath.split("/").length != 3) {
+        if (filePath.startsWith(DELIMITER_SLASH)) {
+            filePath = filePath.substring(1);
+        }
+        String[] filePaths = filePath.split(DELIMITER_SLASH);
+        if (filePaths.length != 0 && filePaths[0].startsWith(FLOWS_FOLDER)) {
```
Comment (brian-mulier-p) [inline webserver/src/main/java/io/kestra/webserver/controllers/api/NamespaceFileController.java]:
```suggestion
        if (filePaths.length != 0 && filePaths[0].equals(FLOWS_FOLDER)) {
```
the startsWith was only if we compared the full path but here we should only do the import flow behaviour if the path part is actually the entire flow folder name

File: webserver/src/main/java/io/kestra/webserver/controllers/api/NamespaceFileController.java [hunk 2]
```diff
@@ -183,8 +181,12 @@ public synchronized int available() {
...
+            if(filePaths.length != 2) {
                 throw new IllegalArgumentException("Invalid flow file path: " + filePath);
```
Comment (brian-mulier-p) [inline webserver/src/main/java/io/kestra/webserver/controllers/api/NamespaceFileController.java]:
```suggestion
                throw new IllegalArgumentException("Invalid flow file path: " + filePath + ". To import a flow, the file path should follow this template: /" + FLOWS_FOLDER + "/{flowId}.yml");
```

Comment (brian-mulier-p) [reply webserver/src/main/java/io/kestra/webserver/controllers/api/NamespaceFileController.java]: If it breaks some tests please fix them

File: webserver/src/main/java/io/kestra/webserver/controllers/api/NamespaceFileController.java [hunk 3]
```diff
@@ -297,8 +298,15 @@ private void forbiddenPathsGuard(URI path) {
...
-        if (forbiddenPathPatterns.stream().anyMatch(pattern -> pattern.matcher(path.getPath()).matches())) {
+        String filePath = path.getPath();
+        if (filePath.startsWith(DELIMITER_SLASH)) {
+            filePath = filePath.substring(1);
+        }
+        String[] splitPath = filePath.split(DELIMITER_SLASH);
+        if(splitPath.length == 0) {
+            return;
+        }
+        if (splitPath[0].startsWith(FLOWS_FOLDER)) {
```
Comment (brian-mulier-p) [inline webserver/src/main/java/io/kestra/webserver/controllers/api/NamespaceFileController.java]:
```suggestion
        if (splitPath[0].equals(FLOWS_FOLDER)) {
```

File: webserver/src/test/java/io/kestra/webserver/controllers/api/NamespaceFileControllerTest.java [hunk 4]
```diff
@@ -141,6 +142,28 @@ void createDirectory() throws IOException {
...
+                        "/api/v1/namespaces/" + NAMESPACE + "/files/directory?path=/_flows",
+                        null)));
+    assertThrows(
+        HttpClientResponseException.class,
+        () ->
+            client
+                .toBlocking()
+                .exchange(
+                    HttpRequest.POST(
+                        "/api/v1/namespaces/" + NAMESPACE + "/files/directory?path=/_flows2",
```
Comment (brian-mulier-p) [inline webserver/src/test/java/io/kestra/webserver/controllers/api/NamespaceFileControllerTest.java]: To me this should be ok... No need to reserve the entire _flows{...} folders, we just need one exclusive

File: webserver/src/test/java/io/kestra/webserver/controllers/api/NamespaceFileControllerTest.java [hunk 5]
```diff
@@ -153,6 +176,24 @@ void createFile() throws IOException {
...
+        assertThrows(HttpClientResponseException.class, () -> client.toBlocking().exchange(
+            HttpRequest.POST("/api/v1/namespaces/" + NAMESPACE + "/files?path=/_flows", body)
+                .contentType(MediaType.MULTIPART_FORM_DATA_TYPE)
+        ));
+        MultipartBody body2 = MultipartBody.builder()
+            .addPart("fileContent", "_flows2", "Hello".getBytes())
+            .build();
+        assertThrows(HttpClientResponseException.class, () -> client.toBlocking().exchange(
+            HttpRequest.POST("/api/v1/namespaces/" + NAMESPACE + "/files?path=/_flows2", body2)
+                .contentType(MediaType.MULTIPART_FORM_DATA_TYPE)
```
Comment (brian-mulier-p) [inline webserver/src/test/java/io/kestra/webserver/controllers/api/NamespaceFileControllerTest.java]: Same as above, should be allowed

**Review by brian-mulier-p — CHANGES_REQUESTED** [review]
Please do the following changes and we're good

File: webserver/src/test/java/io/kestra/webserver/controllers/api/NamespaceFileControllerTest.java (hunk 4 above)
Comment (coderkill) [reply webserver/src/test/java/io/kestra/webserver/controllers/api/NamespaceFileControllerTest.java]: That means we want to allow _flows* from now on

**Comment by coderkill** [comment]
@brian-mulier-p I have made the changes. Please review

**Comment by brian-mulier-p** [comment]
After further looks I'm not sure we want to do that. The previous implementation allowed to provide multiple forbidden patterns which may be a desirable thing, now you're hardcoding every forbidden paths logic.

Looking at the original issue, I'm not sure it's a true issue, as said in comment we just want to reserve the `_flows` folder. Folders like `_flows{additional}` are ok imo. Why do you consider this worth a change?

Sorry btw I didn't spot that you removed the whole multi-pattern check this morning

**Comment by coderkill** [comment]
The main issue was that it allowed the creation of **files** with name _**_flows**_ which is reserved. 

The previous logic (the regex logic) didn’t allow entry (can’t open) into _flows* directories but allowed the user to create the directories. So I assumed that logic was intentional and built it on that.

**Comment by brian-mulier-p** [comment]
Ideally, any _flows{somethingMore} directory is accessible, _flows is not.
For files yes _flows files should be forbidden so there may be a gap that must be filled :+1:

**Comment by coderkill** [comment]
@brian-mulier-p I agree, the above logic is inline with what you have mentioned. It doesn’t allow the creation of file named _flows and it allows directories with name _flows*(including entering it). I will provide the screenshots as well after which we can confirm and merge.

**Comment by coderkill** [comment]
image
image
image

Valid paths:

**Comment by coderkill** [comment]
image
image
image

Valid paths:
image

**Comment by coderkill** [comment]
image
image
image


Valid scenarios:
image

**Comment by coderkill** [comment]
Do have a look at the above screenshots. I have outlined what the user sees when trying to create folders and files when using reserved keywords

**Comment by brian-mulier-p** [comment]
It looks correct except we should remove the error message part where there is "To import flow..." because it only makes sense for the import process. My bad again I didn't see it was wider than just the import so it can just be rolled back.

Still as said it would be great to keep the regex pattern thing because it will allow to extend the forbidden paths later on

**Comment by coderkill** [comment]
@brian-mulier-p I had previously kept the regex change which makes  _flows* as forbidden path. (That means no folder or file will be able created with that regex and any folder with that regex will not be inaccessible like _flows). Do you want me to revert my change?

**Comment by brian-mulier-p** [comment]
Regex should be adapted to work for all the cases I described above

**Comment by brian-mulier-p** [comment]
I suggest putting all the tests I said above and then put back the regex and adapt it so that it covers everything

**Comment by coderkill** [comment]
@brian-mulier-p 

private final List<Pattern> forbiddenPathPatterns = List.of(
        Pattern.compile("/" + FLOWS_FOLDER + ".*")
    );
    
This is the regex previously for forbidden path So I am a little confused as to what needs to be done. Can you please rehighlight what needs to be done so that I can work on it.

**Comment by brian-mulier-p** [comment]
The putNamespaceFiles should be left unchanged imo.
For the forbiddenPathsGuard should be left unchanged also but the pattern could be updated to:
`Pattern.compile("/" + FLOWS_FOLDER + "(/.*)?$")`

This should prevent any access to the flow folder itself or any file in it.
But please add some tests covering every cases we talked about above.

**Comment by coderkill** [comment]
I am assuming when you say "putNamespaceFiles should be left unchanged", do you mean of my latest changes?

When it comes to the forbiddenPathsGuard, My latest change will not allow opening of _flows directory, Which your regex is also  doing, If you want me to use regex instead of startsWith then I can do that. but the behavior will be same as my latest code change.

**Comment by brian-mulier-p** [comment]
As said we should keep the regex implementation as it's a list of patterns instead of an hardcoded single if, I like the ability to extend in a simple way which paths we want to forbid in the future.
For the "putNamespaceFiles should be left unchanged" I mean literally keep what was there before

**Comment by coderkill** [comment]
> As said we should keep the regex implementation as it's a list of patterns instead of an hardcoded single if, I like the ability to extend in a simple way which paths we want to forbid in the future. For the "putNamespaceFiles should be left unchanged" I mean literally keep what was there before

If we keep putNameSpaceFiles() as before then we will be able to create the file _flows which is what we want to prevent (if we keep it from the original code base, if you meant the changes I have done before please clarify).
image
The above shows _flows file. (Do ignore other files and folders as screenshot is old)
I understand the regex implementation for the forbiddenPathsGuard and will work on it.

**Comment by brian-mulier-p** [comment]
> If we keep putNameSpaceFiles() as before then we will be able to create the file _flows which is what we want to prevent (if we keep it from the original code base, if you meant the changes I have done before please clarify).

You can just add something for that

**Comment by coderkill** [comment]
Noted, making changes

**Comment by coderkill** [comment]
Valid cases
image

File creation
image

Folder creation
image


Have added the junits as requested. Do let me know if I have missed any case

**Comment by coderkill** [comment]
@brian-mulier-p Any update? Do you have any other suggestions?

**Comment by MilosPaunovic** [comment]
Brian is going to be off for the next few weeks. @loicmathieu can do the review here, but first, you need to sort the conflict you're having in `webserver/src/test/java/io/kestra/webserver/controllers/api/NamespaceFileControllerTest.java` file.

**Comment by coderkill** [comment]
> Brian is going to be off for the next few weeks. @loicmathieu can do the review here, but first, you need to sort the conflict you're having in `webserver/src/test/java/io/kestra/webserver/controllers/api/NamespaceFileControllerTest.java` file.

Done

**Comment by coderkill** [comment]
@loicmathieu do have a look at the PR and let me know if anything else needs to be done

**Comment by coderkill** [comment]
@MilosPaunovic Any update on the above?

**Comment by MilosPaunovic** [comment]
It's holiday season here, so lot's of people are on a leave. Don't worry, when someone is available, this will be reviewed.

**Comment by loicmathieu** [comment]
I prefer to wait for @brian-mulier-p as he's the one aware of the needed change.

File: webserver/src/main/java/io/kestra/webserver/controllers/api/NamespaceFileController.java [hunk 6]
```diff
@@ -258,11 +258,9 @@ public void delete(
         @Parameter(description = "The internal storage uri of the file / directory to delete") @QueryValue String path
     ) throws IOException, URISyntaxException {
         URI encodedPath = null;
-        if (!path.startsWith("/")) {
-            path = "/" + path;
+        if (path != null) {
+            encodedPath = new URI(URLEncoder.encode(path, StandardCharsets.UTF_8));
         }
```
Comment (brian-mulier-p) [inline webserver/src/main/java/io/kestra/webserver/controllers/api/NamespaceFileController.java]: The leading slash is mandatory for this to work

**Review by brian-mulier-p — CHANGES_REQUESTED** [review]
Tiny change then we're good

File: webserver/src/main/java/io/kestra/webserver/controllers/api/NamespaceFileController.java (hunk 6 above)
Comment (coderkill) [reply webserver/src/main/java/io/kestra/webserver/controllers/api/NamespaceFileController.java]: Done!

**Comment by coderkill** [comment]
@brian-mulier-p Do have a look at the PR and let me know if its good now!

**Review by brian-mulier-p — APPROVED** [review]
LGTM
