### PR TITLE
fix(core): navigating back to plugins home.

### LINKED ISSUE #8939: Plugin, changing page back to home from a plugin is not working
https://github.com/user-attachments/assets/0ccdce45-fbcb-4667-b3c8-547a3198d7a0

### PR DESCRIPTION
**Pull request by Piyush-r-bhaskar**
Closes #8939

### CODE REVIEW

File: ui/src/components/plugins/Plugin.vue [hunk 1]
```diff
@@ -112,7 +112,10 @@
         watch: {
             $route: {
                 handler(newValue, _oldValue) {
-                    if (newValue.name.startsWith("plugins/")) {
+                    if (newValue.name === "plugins/list") {
+                        this.pluginType = undefined;
+                        this.version = undefined;
+                    } else if (newValue.name.startsWith("plugins/")) {
```
Comment (elevatebart) [inline ui/src/components/plugins/Plugin.vue]: Let's keep the scroll-up when we go back to the plugins home

```suggestion
                    } 
                    if (newValue.name.startsWith("plugins/")) {
```

**Review by elevatebart — APPROVED** [review]
One nitpick but good job
