### PR TITLE
Fix/property rendering for subtypes

### LINKED ISSUE #13748: PurgeFiles is not working and not documented correctly
### Describe the issue

https://jam.dev/c/15075a74-dbe2-418b-8cea-ab2228cdb97b

- Documentation is not correct and seems to use the PurgeKV one
- Basic execution doesn't work and it not very explicit on what's wrong (see logs below)

### Reproduce

I created many namespaceFiles in the `kestra.qa` namespace, some of them with several revisions.
Then create this flow:
```
id: purge_ns
namespace: kestra.qa

tasks:
  - id: pruge
    type: io.kestra.plugin.core.namespace.PurgeFiles
    behavior:
      type: version
      keepAmount: 2
    namespaces:
      - kestra.qa
```

```
2025-12-18T11:07:16.802720Z INFO purging 1 namespaces: [kestra.qa]
2025-12-18T11:07:16.812722Z ERROR Could not resolve subtype of [simple type, class io.kestra.plugin.core.namespace.FilesPurgeBehavior]: missing type id property 'type'
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
2025-12-18T11:07:16.812722Z ERROR Could not resolve subtype of [simple type, class io.kestra.plugin.core.namespace.FilesPurgeBehavior]: missing type id property 'type'
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
2025-12-18T11:07:16.812722Z TRACE java.lang.IllegalArgumentException: Could not resolve subtype of [simple type, class io.kestra.plugin.core.namespace.FilesPurgeBehavior]: missing type id property 'type'
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4661)
	at io.kestra.core.models.property.Property.as(Property.java:177)
	at io.kestra.core.models.property.Property.as(Property.java:164)
	at io.kestra.core.runners.RunContextProperty.lambda$as$0(RunContextProperty.java:75)
	at io.kestra.core.utils.Rethrow.lambda$throwFunction$4(Rethrow.java:89)
	at java.base/java.util.Optional.map(Unknown Source)
	at io.kestra.core.runners.RunContextProperty.as(RunContextProperty.java:75)
	at io.kestra.plugin.core.namespace.PurgeFiles.run(PurgeFiles.java:91)
	at io.kestra.plugin.core.namespace.PurgeFiles.run(PurgeFiles.java:24)
	at io.kestra.worker.WorkerTaskCallable.doCall(WorkerTaskCallable.java:81)
	at io.kestra.worker.AbstractWorkerCallable.call(AbstractWorkerCallable.java:64)
	at io.kestra.worker.WorkerSecurityService.callInSecurityContext(WorkerSecurityService.java:10)
	at io.kestra.worker.DefaultWorker.lambda$callJob$19(DefaultWorker.java:976)
	at io.kestra.core.trace.NoopTracer.inCurrentContext(NoopTracer.java:15)
	at io.kestra.worker.DefaultWorker.callJob(DefaultWorker.java:972)
	at io.kestra.worker.DefaultWorker.runAttempt(DefaultWorker.java:930)
	at io.kestra.worker.DefaultWorker.run(DefaultWorker.java:724)
	at io.kestra.worker.DefaultWorker.handleTask(DefaultWorker.java:375)
	at io.kestra.worker.DefaultWorker.lambda$run$8(DefaultWorker.java:290)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve subtype of [simple type, class io.kestra.plugin.core.namespace.FilesPurgeBehavior]: missing type id property 'type'
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
	at com.fasterxml.jackson.databind.DeserializationContext.missingTypeIdException(DeserializationContext.java:2106)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingTypeId(DeserializationContext.java:1677)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleMissingTypeId(TypeDeserializerBase.java:308)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:210)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:121)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:262)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4725)
	... 23 more
```

### Environment

- Kestra Version: develop, `6935900 Wed, Dec 17, 2025 3:17 PM`

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes https://github.com/kestra-io/kestra/issues/13748

### CODE REVIEW

File: core/src/main/java/io/kestra/core/models/property/Property.java [hunk 1]
```diff
@@ -215,15 +219,15 @@ public static <T, I> T asList(Property<T> property, PropertyContext context, Cla
...
+                                return MAPPER.readValue(context.render(str, variables), itemClazz);
                             } else if (item instanceof Map map) {
                                 return MAPPER.convertValue(context.render(map, variables), itemClazz);
                             }
                             return item;
                         }))
                         .toList();
                 }
-            } catch (JsonProcessingException e) {
+            } catch (Exception e) {
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/models/property/Property.java]: Why are you changing that?
It didn't seems to be needed

**Review by loicmathieu — APPROVED** [review]
Adding a test would have been great.

**Review by loicmathieu — APPROVED** [review]
LGTM, I think it's a good move to first try to convert (which would work most of the time and is more performant) then if it fails read it.
