### PR TITLE
fix(ui): disable validation checkmark button when no action is available

### LINKED ISSUE #11382: Validation checkmark when hovered shows cursor with an action but no action available
### Describe the issue

The validation checkmark changes the cursor to a clickable hand, but there is no available action. I think the cursor should not change and remain as a regular pointer.

Image

### Possible solutions:
1. change from button to span
2. disable the button similar to the "Save" button when not available

My preference would be number 2.

### This is what it would look like with option 2

Image

### Environment

- Kestra Version: develop
- Version: `1.0.0`

### PR DESCRIPTION
**Pull request by adityajha-iitj**
Closes #11382 

### What changes are being made and why?

This PR disables the validation checkmark button on the Flow Edit page when there are no validation errors, warnings, or infos, matching the behavior of the Save button. This prevents the cursor from displaying as a pointer and avoids suggesting an unavailable action.

- The checkmark button is now conditionally disabled using the same computed logic as the Save button.
- The button is visually and functionally disabled when there is no action available, ensuring better UX and accessibility.
- No changes were necessary in parent components.

---

### How the changes have been QAed?

- Manual testing on the Flow Edit page:
  - Verified the checkmark is disabled and shows the default cursor when there are no validation messages.
  - Verified the checkmark is enabled and tooltips display correctly when errors, warnings, or infos are present.
  - Tried to click the checkmark when disabled to ensure no action occurs.
- Ran unit tests using `npm run test:unit` to confirm all relevant tests pass and there are no regressions.

---

### Setup Instructions

No special setup required; just run the UI as usual.

Adobe Express - Recording 2025-10-01 184123

### CODE REVIEW

**Comment by adityajha-iitj** [comment]
@MilosPaunovic If this looks good to you please add the hacktoberfest-accepted label. Thank you!

File: ui/src/components/flows/ValidationError.vue [hunk 1]
```diff
@@ -1,7 +1,7 @@
 <template>
     <span ref="rootContainer">
         <!-- Valid -->
-        <el-button v-if="!errors && !warnings &&!infos" v-bind="$attrs" :link="link" :size="size" type="default" class="success square">
+        <el-button v-if="!errors && !warnings &&!infos" v-bind="$attrs" :link="link" :size="size" type="default" class="success square" :disabled="isDisabled">
```
Comment (MilosPaunovic) [inline ui/src/components/flows/ValidationError.vue]: Why not just add `disabled` attribute here and that's it? This button is only shown when it's valid, and that's what we need. So, can you revert other changes and from this file and only add `disabled` prop here and we're good to go?

**Review by MilosPaunovic — CHANGES_REQUESTED** [review]
Good work so far, maybe just to simplify it a bit! 🚀

**Comment by adityajha-iitj** [comment]
@MilosPaunovic Sure! I've corrected my changes, please have a look.

**Review by MilosPaunovic — APPROVED** [review]

**Comment by adityajha-iitj** [comment]
@MilosPaunovic kindly add the hacktoberfest-accepted label. Thank you!

**Comment by MilosPaunovic** [comment]
Hello @adityajha-iitj,

We have `hacktoberfest` listed as one of the topics on this repository, and that should be enough.
