### PR TITLE
[Fix] highlight duplicate IDs in Flow code editor and remove leading colon

### LINKED ISSUE #13644: [Editor] Duplicated Task Id should be highlighted in Flow Code Editor
### Describe the issue

Image

When creating a task with a wrong Id, this is only shown in the small notification at the top, but should also be shown in the editor on the 2nd tasks with the same id.

Also it has been raised, why the exception message starts with a `:`

```yaml
id: kouprey_405190
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by saifxyzyz**
### ✨ Description
This PR removes the leading colon in the error notification box, and highlights duplicate IDs in real time in the flow code editor.

Before:  
image

After"
image

### 🔗 Related Issue
Fixes #13644

### 🎨 Frontend Checklist

_If this PR does not include any frontend changes, delete this entire section._

- [x] Code builds without errors (`npm run build`)
- [ ] All existing E2E tests pass (`npm run test:e2e`)
- [x] Screenshots or video recordings attached showing the `UI` changes

### 🛠️ Backend Checklist

_If this PR does not include any backend changes, delete this entire section._

- [x] Code compiles successfully and passes all checks
- [ ] All unit and integration tests pass

### CODE REVIEW

**Comment by saifxyzyz** [comment]
PTAL @loicmathieu , let me know if I need to add tests for this

**Comment by saifxyzyz** [comment]
hey @brian-mulier-p , please let me know if anything else needs to be done here

**Comment by saifxyzyz** [comment]
@brian-mulier-p any update on this?

**Comment by MilosPaunovic** [comment]
Hello @saifxyzyz,

This will be reviewed at our earliest convenience. There is no need to ping anyone directly.

**Comment by saifxyzyz** [comment]
Got it 👍

**Comment by MilosPaunovic** [comment]
@brian-mulier-p Can you give this a look once you get the chance?

File: ui/src/utils/yamlValidation.ts [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+                                severity: "error"
+                            });
+                        } else {
+                            seenIds.set(idValue, pos);
+                        }
+                    }
+                }
+
+                // Recursively check nested tasks (Sequential, Parallel, etc.)
+                const taskMap = task as YAMLMap;
```
Comment (brian-mulier-p) [inline ui/src/utils/yamlValidation.ts:59]: I may be wrong but it's not possible to end up here as you have ` if (!isMap(task)) continue;` which will skip that?

**Review by brian-mulier-p — CHANGES_REQUESTED** [review]
Small change, anyway I need to spin up your branch to double check

File: ui/src/utils/yamlValidation.ts (hunk 1 above)
Comment (saifxyzyz) [reply ui/src/utils/yamlValidation.ts:59]: `if (!isMap(task)) continue;` ensures that only map tasks are processed, and the lines above check for nested task lists inside the map tasks, so the code is reachable

Comment (brian-mulier-p) [reply ui/src/utils/yamlValidation.ts:59]: Ups nvm about that I misread it. I'll try to spin your PR up soon

**Review by brian-mulier-p — APPROVED** [review]
LGTM, ty for your contribution!
