### PR TITLE
fix(runner): support floating-point CPU values in Docker runner

### LINKED ISSUE #8510: docker Plugin - Improper cast of the CPU property
### Describe the issue

Should be possible to use a floating number for the "CPU: CPUS" property of the docker Plugin but the cpu property is cast to a long which prevents us to do so.

``` yaml
type: io.kestra.plugin.docker.Run
  cpu:
    cpus: "1.5" #should be possible but is not
```

Image

### Environment

- Kestra Version: 0.22.4

### PR DESCRIPTION
**Pull request by Malaydewangan09**
fixes #8510

### CODE REVIEW

File: script/src/test/java/io/kestra/plugin/scripts/runner/docker/DockerTest.java [hunk 1]
```diff
@@ -37,4 +37,29 @@ void shouldNotHaveTagInDockerPullButJustInWithTag() throws Exception {
...
+            .build();
+
+        var taskCommands = new CommandsWrapper(runContext).withCommands(Property.ofValue(List.of(
+            "/bin/sh", "-c",
+            "cat /sys/fs/cgroup/cpu.max || cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us"
+        )));
+
+        var result = docker.run(runContext, taskCommands, Collections.emptyList());
+
+        assertThat(result).isNotNull();
```
Comment (loicmathieu) [inline script/src/test/java/io/kestra/plugin/scripts/runner/docker/DockerTest.java:64]: I assume you verify with your eyes that the result is correct ;) 
Another solution would have been to create outputs so you would be able to assert on it.
Or even check the logs as you have them inside the log consumer.

I'll approve it anyway but more robust test assertions would be great.

**Review by loicmathieu — APPROVED** [review]
LGTM

File: script/src/test/java/io/kestra/plugin/scripts/runner/docker/DockerTest.java (hunk 1 above)
Comment (Malaydewangan09) [reply script/src/test/java/io/kestra/plugin/scripts/runner/docker/DockerTest.java:64]: Yes, done
Thanks!
