### PR TITLE
fix(executions): restore execution redirect & subflow logs view from parent

### LINKED ISSUE #10528: Clicking execution ID of subflow in log requires manual page refresh
### Describe the issue

- create a flow and subflow
- Run and in gaant try to access subflow by clicking execution ID

screen stays blank and will not show execution until manual refresh of page

https://jam.dev/c/b64ebac8-ff83-4f2d-a66e-4d7890d39d67

### Environment

- Kestra Version: 0.24-rc1

### LINKED ISSUE #10551: No longer possible to see subflow logs from parent execution
### Describe the issue

@brian-mulier-p is on it

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes #10528
closes #10551

### CODE REVIEW

File: ui/src/stores/executions.ts [hunk 1]
```diff
@@ -494,11 +498,13 @@ export const useExecutionsStore = defineStore("executions", () => {
         )
     }
 
-    const loadFlowForExecution = (options: { namespace: string; flowId: string; revision?: number }) => {
+    const loadFlowForExecution = (options: { namespace: string; flowId: string; revision?: number, store?: boolean }) => {
         const revision = options.revision ? `?revision=${options.revision}` : "";
         return store.$http.get(`${apiUrl(store)}/executions/flows/${options.namespace}/${options.flowId}${revision}`)
             .then(response => {
-                flow.value = response.data;
+                if (store) {
```
Comment (elevatebart) [inline ui/src/stores/executions.ts]: Oops?
```suggestion
                if (options.store) {
```

**Review by elevatebart — APPROVED** [review]
One ridicule typo but we good to go I think.

I would have loved:
- some explaination in the body of the PR
- some tests 

But time is of the essence
