### PR TITLE
fix(core): avoid multiple rendering in ForEachItem

### LINKED ISSUE #8905: ForEachItem is rendering `batch.rows` parameter for each created row
### Describe the issue

Could be painful when it comes to secret manager cost or hardlimits for eg.

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes #8905

### CODE REVIEW

File: core/src/main/java/io/kestra/core/services/StorageService.java [hunk 1]
```diff
@@ -40,8 +42,9 @@ public static List<URI> split(RunContext runContext, StorageSplitInterface stora
                 splited = StorageService.partition(runContext, extension, runContext.render(storageSplitInterface.getSeparator()).as(String.class).orElseThrow(),
                     bufferedReader, runContext.render(storageSplitInterface.getPartitions()).as(Integer.class).orElseThrow());
             } else if (storageSplitInterface.getRows() != null) {
+                Integer renderedRows = runContext.render(storageSplitInterface.getRows()).as(Integer.class).orElseThrow();
                 splited = StorageService.split(runContext, extension, runContext.render(storageSplitInterface.getSeparator()).as(String.class).orElseThrow(),
-                    bufferedReader, throwBiFunction((bytes, size) -> size >= runContext.render(storageSplitInterface.getRows()).as(Integer.class).orElseThrow()));
+                    bufferedReader, throwBiFunction((bytes, size) -> size >= renderedRows));
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/services/StorageService.java]: You should not need that throwBiFunction anymore

**Review by loicmathieu — APPROVED** [review]
LGTM
