### PR TITLE
fix(triggers): improve layout of action buttons in trigger table

### LINKED ISSUE #13642: [Triggers UI] Icons are offset when there is a locked trigger – Administration section
### Describe the issue

Image

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by Sumitsh28**
### ✨ Description

This PR fixes a visual bug in the **Administration -> Triggers** table where the action buttons (Unlock and Delete) were misaligned and wrapping onto multiple lines.

I have wrapped the action buttons in a flex container to ensure they remain aligned horizontally on the same row.

### 🔗 Related Issue

Closes #13642

### 🎨 Frontend Checklist

- [x] Code builds without errors (`npm run build`)
- [x] All existing E2E tests pass (`npm run test:e2e`)
- [x] Screenshots or video recordings attached showing the `UI` changes

#### Before
Screenshot 2025-12-13 at 2 20 06 PM

#### After
Screenshot 2025-12-13 at 2 18 24 PM

### CODE REVIEW

File: ui/src/components/admin/Triggers.vue [hunk 1]
```diff
@@ -204,24 +204,26 @@
...
-                                <el-button>
-                                    <Kicon
-                                        :tooltip="$t('delete trigger')"
-                                        placement="left"
-                                        @click="confirmDeleteTrigger(scope.row)"
-                                    >
-                                        <Delete />
-                                    </Kicon>
-                                </el-button>
+                                <div style="display: flex; align-items: center; gap: 5px;">
```
Comment (Piyush-r-bhaskar) [inline ui/src/components/admin/Triggers.vue]: Hey @Sumitsh28 

please remove the inline styles and make use of class.

**Review by Piyush-r-bhaskar — CHANGES_REQUESTED** [review]

File: ui/src/components/admin/Triggers.vue (hunk 1 above)
Comment (Sumitsh28) [reply ui/src/components/admin/Triggers.vue]: Hey @Piyush-r-bhaskar , Fixed

**Review by Piyush-r-bhaskar — APPROVED** [review]
