### PR TITLE
fix(ui): clear selection of retry form radio buttons 

### LINKED ISSUE #9258: No Code Panel: Clear Selection for Radio Buttons – Initial State and Reset Functionality
### Describe the issue

The No Code panel should handle the behavior of radio buttons as follows:

- Initial State: When the panel opens, no radio button should be selected by default. This reduces visual complexity and saves vertical space.
- Selection: When a radio button is selected, the associated properties should be displayed.
- Clear Selection: When the "Clear Selection" button is clicked, all radio buttons should be deselected, and the panel should return to its initial state with no selection active.

https://github.com/user-attachments/assets/ef6f0410-7da5-47b3-92e8-c37c63dedaf4

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by starlightknown**
closes #9258 

### What changes are being made and why?

https://github.com/user-attachments/assets/a321ffee-7917-454e-ae16-50ba1efe36fe

---

### How the changes have been QAed?

---

### CODE REVIEW

**Comment by elevatebart** [comment]
Thank you for this, I really like the consensus here. 
Having fields and not being able to have them empty is complicated.

Empty is hard to convey nicely though. We need @Nico-Kestra's input. 
- Some kind of placeholder where the fields will be? 
- A button/checkbox to enable retry/sla/labels?
- A collapsible for each of these sections that one expands to get a block in code?

I will let @Nico-Kestra decide.

connected to #9205

File: ui/src/components/flows/tasks/TaskAnyOf.vue [hunk 1]
```diff
@@ -59,14 +59,18 @@
...
-                (this.modelValue === "number" && item.value === "integer") ||
-                (Array.isArray(this.modelValue) && item.value === "array"),
-            );
+            if (this.modelValue) {
+                const schema = this.schemaOptions.find((item) =>
+                    typeof item.value === this.modelValue?.type ||
+                    (this.modelValue === "string" && item.value === "string") ||
+                    (this.modelValue === "number" && item.value === "integer") ||
+                    (Array.isArray(this.modelValue) && item.value === "array"),
+                );
```
Comment (elevatebart) [inline ui/src/components/flows/tasks/TaskAnyOf.vue]: I did not understand his change. here is my suggestion instead.

```suggestion
            const schema = this.schemaOptions.find((item) =>
                typeof item.value === this.modelValue?.type ||
                (typeof this.modelValue === "string" && item.value === "string") ||
                (typeof this.modelValue === "number" && item.value === "integer") ||
                (Array.isArray(this.modelValue) && item.value === "array"),
            );

            this.selectedSchema = schema?.value;
            
            // only default selector to required values 
            if(!this.selectedSchema && this.schemas.length > 0 && this.required) {
                this.selectedSchema = this.schemas[0].type;
            }
```

File: ui/src/components/flows/tasks/TaskAnyOf.vue [hunk 2]
```diff
@@ -124,7 +128,7 @@
                 this.onInput(value);
             },
             resetSelectType() {
-                this.selectedSchema = this.schemaOptions[0]?.value;
+                this.selectedSchema = undefined;
```
Comment (elevatebart) [inline ui/src/components/flows/tasks/TaskAnyOf.vue:136]: that's great yeah!

**Review by elevatebart — CHANGES_REQUESTED** [review]
I like where this is going. 
We just need to decide what to do with empty forms.

Screenshot 2025-06-04 at 17 34 14

**Comment by elevatebart** [comment]
Also, I found two "UI-bugs" triggered by this:
- When cleaning up retry on the root form, the data is not really cleared even if the code is now clean.
- It feels odd to leave the clear selection button when there is no value.

fixes could be:
- adding a default empty object to the init object of `Editor.vue` at retry. L157
- conditionning the `<ClearButton/>` in `TaskObjectField.vue` on `isAnyOf && modelValue && Object.keys(modelValue).length > 0`, ignoring the required flag L15

**Comment by starlightknown** [comment]
I made changes

**Review by elevatebart — APPROVED** [review]
