### PR TITLE
Fix(UI): fixed minor design adjustments on NEWS panel (#12032)

### LINKED ISSUE #12032: Panel NEWS: Review minor design details
### Feature description

Several small design adjustments are needed in the NEWS panel.

Tasks:

- [x] 1. Add 8px border-radius to images.
- [x] 2. In the main news item, reduce spacing between the date and the content.
- [x] 3. The tooltip on the date seems unnecessary — consider removing it.
- [x] 4. Reduce the spacing between a separator and the start of a news item to 32px.
- [x] 5. Change the date color to use the variable `-ks-content-secondary`.

Image

### PR DESCRIPTION
**Pull request by pallapothu30**
Fixes #12032 

## Description
This PR implements several small design improvements for the NEWS panel as mentioned in the issue.

**Note:** Inline comments marking “fixes” are still present in the code for review purposes and will be removed once changes are approved.

## Changes

1. **Border-radius for images**  
   - Added `8px` border-radius to news images.

2. **Reduced spacing between date and content**  
   - Removed `mt-3` from the feed content (Markdown component) to reduce vertical space between the date/title and the description.

3. **Removed tooltip on date**  
   - Removed the hover tooltip from the `DateAgo` component while keeping the date visible on screen.
   
4. **Padding adjustments**  
   - Updated `.post` padding to `1rem 1rem 0 1rem` to remove extra bottom space while preserving top and side padding.
   
5. **Date color adjustment**  
   - Updated the date color to use the `--ks-content-secondary` CSS variable for consistent theme styling.

## Notes
- Changes have been tested locally and maintain responsive behavior.  
- This PR only affects the NEWS panel layout and styling; no functional changes to feed data were made.

### CODE REVIEW

**Comment by pallapothu30** [comment]
Hi team,

I’ve implemented the requested UI/design fixes for the NEWS panel. I’ve left inline comments in the code pointing to where each fix was applied for easier review. Once the changes are approved, I will remove all these comments.

Please review when you get a chance. Thanks!

File: ui/src/components/layout/DateAgo.vue [hunk 1]
```diff
@@ -1,19 +1,11 @@
 <template>
-    <el-tooltip
```
Comment (MilosPaunovic) [inline ui/src/components/layout/DateAgo.vue:2]: Why did you remove the tooltip here? This component is used in many different places, so just removing things is not okay.

File: ui/src/components/layout/ContextNews.vue [hunk 2]
```diff
@@ -16,10 +16,11 @@
                 <h5>
                     {{ feed.title }}
                 </h5>
+                <!-- fix 3 consider removign tooltip wrapper in DateAgo comp seperate file -->
```
Comment (MilosPaunovic) [inline ui/src/components/layout/ContextNews.vue]: If you're planning to use `AI` for all the work, at least remove the generated comments of this sort, otherwise, next time, the PR will be automatically closed.

File: ui/src/components/layout/ContextNews.vue [hunk 3]
```diff
@@ -16,10 +16,11 @@
...
                 <DateAgo className="news-date small" :inverted="true" :date="feed.publicationDate" format="LL" />
             </div>
-
-            <Markdown class="markdown-tooltip mt-3 postParagraph" :source="feed.description" />
+            <!-- fix 2 remove mt-3 -->
```
Comment (MilosPaunovic) [inline ui/src/components/layout/ContextNews.vue]: If you're planning to use `AI` for all the work, at least remove the generated comments of this sort, otherwise, next time, the PR will be automatically closed.

File: ui/src/components/layout/ContextNews.vue [hunk 4]
```diff
@@ -74,8 +75,9 @@
 </script>
 
 <style scoped lang="scss">
+
     .post {
-        padding: 1rem;
+        padding: 1rem 1rem 0rem 1rem; //fix 4 - extra padding in between divider and image without disturbing others
```
Comment (MilosPaunovic) [inline ui/src/components/layout/ContextNews.vue]: If you're planning to use `AI` for all the work, at least remove the generated comments of this sort, otherwise, next time, the PR will be automatically closed.

**Review by MilosPaunovic — CHANGES_REQUESTED** [review]

**Comment by pallapothu30** [comment]
Hi @MilosPaunovic,

Thanks for the feedback! Since the issue mentioned `consider removing the tooltip`, I thought removing it would simplify the NEWS panel. sorry about that.
 I will revert it back.
 
 I did use AI to understand parts of the code, but all the inline comments were manually added by me to keep track of the changes I made. I thought they would help with the review, my apologies for that. I’ve will remove the comments.
 
 For fix 3 `(tooltip removal)`, I haven’t made any changes yet. I’m thinking of adding a `noTooltip`  prop (default false) in DateAgo.vue and setting it true in the NEWS panel, so the tooltip stays elsewhere. Let me know your thoughts.

**Comment by MilosPaunovic** [comment]
Yes, `noTooltip` prop does sound like a good approach, go with it! 🚀

**Comment by MilosPaunovic** [comment]
Is this now ready to be reviewed?

**Comment by pallapothu30** [comment]
Yeah , it's ready please review

**Review by MilosPaunovic — APPROVED** [review]
