### PR TITLE
Fix(UI) Backfill trigger auto fill 

### LINKED ISSUE #6458: Explore how to fill the default input value in Backfills by the input value set within a schedule
### Feature description

Repro:
```yaml
id: backfill_test
namespace: company.team

inputs:
  - id: taxi
    type: SELECT
    displayName: Select taxi type
    values: [yellow, green]
    defaults: green

variables:
  file: yellow_tripdata_{{trigger.date ?? execution.startDate | date("yyyy-MM")}}.parquet

tasks:
  - id: label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      file: "{{render(vars.file)}}"
      
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: file https://d37ci6vzurychx.cloudfront.net/trip-data/{{render(vars.file)}}

triggers:
  - id: green_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 1 * *"
    inputs:
      taxi: green

  - id: yellow_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 17 1 * *"
    inputs:
      taxi: yellow
```

For now, backfill for the yellow_schedule will have the default value to be green - would be cool to make it "yellow" as defined by the trigger input.

image

### PR DESCRIPTION
**Pull request by satvik2131**
Closes #6458 
What I have done ? 
- used selectedTrigger when opening the modal for providing the taxi input.

working sample , please have a look and let me know if it's ok .
https://github.com/user-attachments/assets/191c8851-f5ea-4188-abad-fe47e6d0d680

### CODE REVIEW

File: ui/src/components/filter/KestraFilter.vue [hunk 1]
```diff
@@ -1122,4 +1122,4 @@ $properties: v-bind('props.propertiesWidth + "px"');
         }
     }
 }
-</style>
+</style>
```
Comment (MilosPaunovic) [inline ui/src/components/filter/KestraFilter.vue]: This change is not needed, please revert back to original state.

File: ui/src/components/inputs/InputsForm.vue [hunk 2]
```diff
@@ -261,7 +266,8 @@
                 inputsValidation: [],
                 multiSelectInputs: {},
                 inputsValidated: new Set(),
-                debouncedValidation: () => {}
+                debouncedValidation: () => {},
+                selTrigger: toRaw(this.selectedTrigger.inputs.taxi)
```
Comment (MilosPaunovic) [inline ui/src/components/inputs/InputsForm.vue]: Would this mean that this would work only if the input ID is `taxi`? If so, than it's no good.

**Review by MilosPaunovic — CHANGES_REQUESTED** [review]

**Comment by MilosPaunovic** [comment]
Also, there seem to be some merge conflicts which need to be resolved.

File: ui/src/components/inputs/InputsForm.vue (hunk 2 above)
Comment (satvik2131) [reply ui/src/components/inputs/InputsForm.vue]: Yeah I got it , I have made it dynamic .

**Comment by satvik2131** [comment]
Hi @MilosPaunovic , done with changes , please have a look and let me know if I miss anything . Thanks :)

**Comment by anna-geller** [comment]
@MilosPaunovic looks like some final touches before we can merge?

**Review by MilosPaunovic — APPROVED** [review]
LGTM! 🚀
