### PR TITLE
fix(ui): log navigation not working in temporal view

### LINKED ISSUE #5215: New Log navigation don't work on temporal view
[Screencast_20240930_095540.webm](https://github.com/user-attachments/assets/48ea5295-28b6-40b5-ab9d-05a26543e271)

### PR DESCRIPTION
**Pull request by sachinks07**
- This PR solves the issue #5215

- Added the implementation for temporal Log Navigation

https://github.com/user-attachments/assets/f46ebd9b-cc7d-4728-ba75-dfc3538c71c3

closes #5215

### CODE REVIEW

**Comment by MilosPaunovic** [comment]
It might be better for @brian-mulier-p to take a look at this one, as he's much more familiar with the topic than I am.

File: ui/src/components/executions/Logs.vue [hunk 1]
```diff
@@ -66,20 +67,44 @@
...
+        <el-card v-else class="attempt-wrapper">
+            <DynamicScroller
+                ref="logScroller"
+                :items="temporalLogs"
+                :min-item-size="getTemporalLogsSize()"
+                key-field="uniqueId"
+                class="log-lines"
+                :buffer="200"
+                :prerender="20"
+                :key="filterUpdateCount"
```
Comment (sachinks07) [inline ui/src/components/executions/Logs.vue:85]: The key filterUpdateCount is used to re-render DynamicScroller when filter(Search) changes. Because when the filter changes we filter out the temporalLogs based on the filter. This update logs weren't reflected in the view.

File: ui/src/components/executions/Logs.vue [hunk 2]
```diff
@@ -169,18 +255,34 @@
...
                 this.$refs.logs.toggleExpandCollapseAll();
             },
             setRawView() {
                 this.raw_view = !this.raw_view;
-                if(this.raw_view) {
-                    this.$store.dispatch("execution/loadLogs", {
-                        executionId: this.execution.id,
-                        minLevel: this.level
-                    })
+                if(this.raw_view && this.temporalCursor!==undefined)
```
Comment (sachinks07) [inline ui/src/components/executions/Logs.vue:265]: This is used when we switch from temporal to default view or vice versa  scroll to previous temporal cursor or log cursor

File: ui/src/components/executions/Logs.vue [hunk 3]
```diff
@@ -119,17 +148,64 @@
...
+                    return log.message?.toLowerCase().includes(this.filter.toLowerCase());
+                });
+
+                return filtered.map((logLine, index) => ({
+                    ...logLine,
+                    index,
+                    uniqueId: `${logLine.timestamp || ""}-${logLine.taskId || ""}-${index}`
+                }));
+            },
+            temporalLogIndicesByLevel()
```
Comment (sachinks07) [inline ui/src/components/executions/Logs.vue:194]: This property is used to group logs indices by level {
     "ERROR": ["1"],
     "WARN": [],
     "INFO": ["0", "2"],
     "DEBUG": [],
     "TRACE": []
}

**Comment by brian-mulier-p** [comment]
LGTM, works great, congrats for figuring out the way it was built and thank's a lot for the contribution !

**Review by brian-mulier-p — APPROVED** [review]

**Comment by brian-mulier-p** [comment]
@sachinks07 FYI I just [fixed it](https://github.com/kestra-io/kestra/commit/9d809e8b533741a23808a252877f00f07114e7aa) but there was a bug introduced that was leading to logs no longer being fetched in Gantt & Topology view. Basically I made it so that if `logs` prop is sent to TaskRunDetails it means that the parent handles the whole log fetching logic (so we just send an event) otherwise we fetch logs directly from the component itself

**Comment by sachinks07** [comment]
Sorry I didn't check this properly. I was only concentrated on the Logs page. Thanks for fixing this issue

**Comment by brian-mulier-p** [comment]
No worries, in the end I had to go for a [larger refactoring](https://github.com/kestra-io/kestra/commit/e969425dba442ec9edf655d41a833c1f72f269f0) to combine the log nav mechanism for both temporal and taskrun view to avoid maintainance issues
