### PR TITLE
fix(execution): prevent NPE in SetVariables when variables are null

### LINKED ISSUE #13756: Flow Variables are not set in Webhook-triggered Executions (NullPointerException)
## Error

I am getting a `NullPointerException` in the task `SetVariables`  with `overwrite: false` when triggered via Webhook (not, when triggered manually). (Stacktrace see below)

Version: 1.1.10 (docker)

The code that crashes:

https://github.com/kestra-io/kestra/blob/22f0b3ffdf5b297bbbeefb69d01f8a60e7031af2/core/src/main/java/io/kestra/plugin/core/execution/SetVariables.java#L62-L71

## Reproduce

When triggered with Webhook, this flow will crash in the `set_input_vars` Task. The same exception does not occur when I manually execute the flow from the Kestra Web UI, or when I set `overwrite: true` in the task. 

Interestingly, `printContext()` shows me that the variables exist as expected in each case (manual and Webhook trigger).

```yaml
id: flow_name
namespace: name.space

variables: # these aren't set when run via Webhook!
  first_variable: ASDF

tasks:
  - id: log_context
    type: io.kestra.plugin.core.log.Log
    level: DEBUG
    message: "{{ printContext() }}" # reliably includes "vars": { "first_variable": "ASDF" }
  - id: set_input_vars
    type: io.kestra.plugin.core.execution.SetVariables
    variables:
      second_variable: "{{ 'second breakfast' }}"
    overwrite: false

triggers:
  - id: jenkins
    type: io.kestra.plugin.core.trigger.Webhook
    key: myKey
```

## Stacktrace
```log
kestra-1             | 09:20:53.239 INFO  default-nioEventLoopGroup-1-6 io.kestra.webserver.access 2025-12-18T09:20:53.189Z | POST /kestra/api/v1/main/executions/webhook/name.space/flow_name/myKey HTTP/1.1 | status: 200 | ip: XXX | length: 1113 | duration: 9
kestra-1             | 09:20:53.860 INFO  jdbc-execution-executor_2413 flow_name [tenant: main] [namespace: name.space] [flow: flow_name] [execution: 1XUXOGGjPRoM5zSzBNacXj] Flow started
kestra-1             | 09:20:53.195 WARN  jdbc-execution-executor_2412 i.k.core.models.executions.Execution [namespace: name.space] [flow: flow_name] [execution: 1XUXOGGjPRoM5zSzBNacXj] Flow failed from executor in 00:00:00.240 with exception 'Cannot invoke "java.util.Map.containsKey(Object)" because the return value of "io.kestra.core.models.executions.Execution.getVariables()" is null'
kestra-1             | java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because the return value of "io.kestra.core.models.executions.Execution.getVariables()" is null
kestra-1             |  at io.kestra.plugin.core.execution.SetVariables.lambda$update$0(SetVariables.java:67)
kestra-1             |  at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
kestra-1             |  at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
kestra-1             |  at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
kestra-1             |  at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
kestra-1             |  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
kestra-1             |  at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
kestra-1             |  at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
kestra-1             |  at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
kestra-1             |  at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
kestra-1             |  at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
kestra-1             |  at io.kestra.plugin.core.execution.SetVariables.update(SetVariables.java:67)
kestra-1             |  at io.kestra.executor.ExecutorService.lambda$handleExecutionUpdatingTask$28(ExecutorService.java:1098)
kestra-1             |  at java.base/java.util.ArrayList.removeIf(Unknown Source)
kestra-1             |  at java.base/java.util.ArrayList.removeIf(Unknown Source)
kestra-1             |  at io.kestra.executor.ExecutorService.handleExecutionUpdatingTask(ExecutorService.java:1075)
kestra-1             |  at io.kestra.executor.ExecutorService.process(ExecutorService.java:184)
kestra-1             |  at io.kestra.jdbc.runner.JdbcExecutor.lambda$executionQueue$26(JdbcExecutor.java:628)
kestra-1             |  at io.kestra.core.trace.NoopTracer.inCurrentContext(NoopTracer.java:20)
kestra-1             |  at io.kestra.jdbc.runner.JdbcExecutor.lambda$executionQueue$27(JdbcExecutor.java:552)
kestra-1             |  at io.kestra.jdbc.repository.AbstractJdbcExecutionRepository.lambda$lock$33(AbstractJdbcExecutionRepository.java:1001)
kestra-1             |  at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:533)
kestra-1             |  at org.jooq.impl.Tools$3$1.block(Tools.java:6393)
kestra-1             |  at java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
kestra-1             |  at java.base/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
kestra-1             |  at org.jooq.impl.Tools$3.get(Tools.java:6390)
kestra-1             |  at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:581)
kestra-1             |  at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:504)
kestra-1             |  at io.kestra.jdbc.JooqDSLContextWrapper.lambda$transactionResult$2(JooqDSLContextWrapper.java:67)
kestra-1             |  at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
kestra-1             |  at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
kestra-1             |  at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
kestra-1             |  at dev.failsafe.internal.FallbackExecutor.lambda$apply$0(FallbackExecutor.java:51)
kestra-1             |  at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
kestra-1             |  at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
kestra-1             |  at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
kestra-1             |  at io.kestra.core.utils.RetryUtils$Instance.wrap(RetryUtils.java:144)
kestra-1             |  at io.kestra.core.utils.RetryUtils$Instance.runRetryIf(RetryUtils.java:103)
kestra-1             |  at io.kestra.jdbc.JooqDSLContextWrapper.transactionResult(JooqDSLContextWrapper.java:65)
kestra-1             |  at io.kestra.jdbc.repository.AbstractJdbcExecutionRepository.lock(AbstractJdbcExecutionRepository.java:983)
kestra-1             |  at io.kestra.jdbc.runner.JdbcExecutor.executionQueue(JdbcExecutor.java:548)
kestra-1             |  at io.kestra.jdbc.runner.JdbcExecutor.lambda$run$3(JdbcExecutor.java:301)
kestra-1             |  at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
kestra-1             |  at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
kestra-1             |  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
kestra-1             |  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
kestra-1             |  at java.base/java.lang.Thread.run(Unknown Source)
kestra-1             | 09:20:53.337 INFO  jdbc-execution-executor_2414 flow_name [tenant: main] [namespace: name.space] [flow: flow_name] [execution: 1XUXOGGjPRoM5zSzBNacXj] Flow completed with state FAILED in 00:00:00.266
```

## Potential cause

I found a closed, variable related issue in #11891. If I understand correctly, part of the fix was this line added in the `Execution.builder()`:
https://github.com/kestra-io/kestra/blob/004a85f701e8989d0f0c65bd124d499a1bdb9061/core/src/main/java/io/kestra/core/models/triggers/TriggerService.java#L124

This got me to check out the WebHook code and it seems like that might be missing the variable injection in the Execution builder:
https://github.com/kestra-io/kestra/blob/24e61c81c00f294d46fe87c5876de6ceccc8607f/core/src/main/java/io/kestra/plugin/core/trigger/Webhook.java#L179-L197

### PR DESCRIPTION
**Pull request by Hritikraj8804**
### ✨ Description

This PR fixes a NullPointerException in the `SetVariables` task when execution variables are not initialized.

When `overwrite: false` is used, the task assumed `execution.getVariables()` was non-null and attempted to call `containsKey(...)`, which caused a crash for webhook-triggered executions (and some manual executions).

The fix defensively initializes a local variables map before performing duplicate checks and merges, preserving existing behavior while preventing the NPE.

### 🔗 Related Issue

Closes https://github.com/kestra-io/kestra/issues/13756

### 🛠️ Backend Checklist

- [x] Code compiles successfully
- [x] Bug reproduced locally (manual + webhook execution)
- [x] Fix verified locally

### 📝 Additional Notes

The issue author mentioned that webhook-triggered executions may not initialize variables at creation time.  
This fix makes `SetVariables` resilient to that case without changing execution semantics.

### CODE REVIEW

**Comment by loicmathieu** [comment]
I wonder if the correct fix should not be to add flow variables to the execution when we trigger an execution from a Webhook.

**Comment by Hritikraj8804** [comment]
Thanks for the insight that makes sense 👍

My intention with this PR was to provide a minimal and defensive fix at the task level, since `execution.getVariables()` is not guaranteed to be initialized in all execution paths (as seen with webhook-triggered executions). This avoids the NPE without changing execution creation semantics.

That said, I agree that initializing flow variables when creating the execution from a webhook could be a more correct and consistent fix, especially since other triggers already do this. If you think that’s the preferred approach, I’m happy to adjust the PR to initialize variables at execution creation time instead (or complement this fix accordingly).

Let me know which direction you’d prefer.

**Comment by loicmathieu** [comment]
I'm OK to keep a defensive code in this place as it would prevent other source of bugs (a NPE is always a bug), but we should also fix missing flow variable for Webhook to align with other kind of triggers.

**Comment by Hritikraj8804** [comment]
I’ve added initialization of execution variables in the Webhook trigger using flow.getVariables(), aligning webhook executions with other triggers while keeping the defensive fix in SetVariables.

Let me know if anything else should be adjusted.

File: core/src/main/java/io/kestra/plugin/core/execution/SetVariables.java [hunk 1]
```diff
@@ -60,16 +61,31 @@ public class SetVariables extends Task implements ExecutionUpdatableTask {
...
-        Map<String, Object> renderedVars = runContext.render(this.variables).asMap(String.class, Object.class);
-        boolean renderedOverwrite = runContext.render(overwrite).as(Boolean.class).orElseThrow();
+        Map<String, Object> renderedVars =
+            runContext.render(this.variables).asMap(String.class, Object.class);
+
+        boolean renderedOverwrite =
+            runContext.render(overwrite).as(Boolean.class).orElseThrow();
+
+        Map<String, Object> currentVariables =
+            execution.getVariables() == null ? new HashMap<>() : execution.getVariables();
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/plugin/core/execution/SetVariables.java]:
```suggestion
            execution.getVariables() == null ? Collections.emptyMap() : execution.getVariables();
```

**Review by loicmathieu — CHANGES_REQUESTED** [review]
can you also revert most of your code format change (line lenght) to keep only real changes in the PR as  it will be easier to follow.

**Comment by Hritikraj8804** [comment]
Done 👍
Reverted formatting-only changes and replaced `new HashMap<>()` with `Collections.emptyMap()` as suggested.

File: core/src/main/java/io/kestra/plugin/core/execution/SetVariables.java (hunk 1 above)
Comment (MilosPaunovic) [reply core/src/main/java/io/kestra/plugin/core/execution/SetVariables.java]: If you've addressed any of the requested changes from the PR review, @Hritikraj8804, make sure to click the `Resolve conversation` button for that particular change to signal to the reviewer that you've completed what was requested.

**Review by loicmathieu — APPROVED** [review]
LGTM, thanks

**Comment by loicmathieu** [comment]
Backported to 1.0 and 1.1
