### PR TITLE
fix(ui): Executions > outputs is now responsive

### LINKED ISSUE #12737: Useless output page on mobile
Image

Don't have crazy idea here, TBD or Brainstorm

### PR DESCRIPTION
**Pull request by mahadevaperuka**
### ✨ Description

What does this PR change?  
Executions > Outputs page is now responsive with some basic ideas. Can be enhanced with any new ideas in the future.

### 🔗 Related Issue

Closes #12737 

### 🎨 Frontend Checklist

- [x] Screenshots or video recordings attached showing the `UI` changes

For Mobiles
image<br/>

For Tablets
image

For Laptops
image

### 📝 Additional Notes
Top Nav bar may need a padding fix.

### CODE REVIEW

File: ui/src/components/executions/outputs/Wrapper.vue [hunk 1]
```diff
@@ -432,6 +432,23 @@
...
+        const handler = (e: MediaQueryListEvent) => {
+            isMobile.value = e.matches;
+        };
+
+        mediaQuery.addEventListener("change", handler);
+
+        onUnmounted(() => {
+            mediaQuery.removeEventListener("change", handler);
+        });
+    });
```
Comment (elevatebart) [inline ui/src/components/executions/outputs/Wrapper.vue]: All composables should be used at the top of the setup function.

```suggestion
    });
    
     onUnmounted(() => {
          mediaQuery.removeEventListener("change", handler);
      });
```

This being said, I would prefer you use the `useMediaQuery()` of [vueuse](https://vueuse.org/core/useMediaQuery/) that will do all of that for you and more.

**Review by elevatebart — CHANGES_REQUESTED** [review]
Thanks for this, the mobile experience on Kestra is really improved with this.

One small nitpick with regards to the media query in Vue.

File: ui/src/components/executions/outputs/Wrapper.vue (hunk 1 above)
Comment (mahadevaperuka) [reply ui/src/components/executions/outputs/Wrapper.vue]: I have made the required changes.

**Review by elevatebart — APPROVED** [review]
LGTM !!
