### PR TITLE
fix(flows): properly delete task from topology to reflect everywhere

### LINKED ISSUE #10923: Deleting the task from Topology flow graph is not working.
### Describe the issue

https://github.com/user-attachments/assets/13b950ad-0ebe-453a-80dc-33344e8cec58

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by Piyush-r-bhaskar**
Closes https://github.com/kestra-io/kestra/issues/10923

### CODE REVIEW

File: ui/src/components/inputs/LowCodeEditorWrapper.vue [hunk 1]
```diff
@@ -85,13 +85,23 @@
...
+        const result = await flowStore.onEdit({
             source,
             currentIsFlow,
             editorViewType: "YAML",
         })
+        
+        if (currentIsFlow && source) {
+            await flowStore.loadGraphFromSource({
+                flow: source,
+            }).catch(() => {
```
Comment (MilosPaunovic) [inline ui/src/components/inputs/LowCodeEditorWrapper.vue]: Let's maybe log error to console, at least with `console.error()`?

**Review by MilosPaunovic — CHANGES_REQUESTED** [review]

**Review by MilosPaunovic — APPROVED** [review]
LGTM! 🚀
