### PR TITLE
fix(core): Dag task with error handler now terminate correctly

### LINKED ISSUE #2111: Failing task with error handler in a DAG will hang forever leading to zombie execution
### Expected Behavior

_No response_

### Actual Behaviour

See https://demo.kestra.io/ui/executions/io.kestra.bmu/dag-test-error/2lJMuZsJdIvt7GqobvxeQR/gantt
It only happens if we add an error handler, without it a failing task will stop the execution properly

### Steps To Reproduce

_No response_

### Environment Information

- Kestra Version: 0.12.0-SNAPSHOT
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

```
id: dag-test-error
namespace: io.kestra.bmu
tasks:
- id: dag
  type: io.kestra.core.tasks.flows.Dag
  tasks:
  - task:
      id: Log
      type: io.kestra.core.tasks.log.Log
      message: Some log
    dependsOn:
    - failing
  - task:
      id: failing
      type: io.kestra.core.tasks.executions.Fail
  errors:
  - id: error
    type: io.kestra.core.tasks.log.Log
    message: error handler
```

### PR DESCRIPTION
**Pull request by Skraye**
close #2111

### CODE REVIEW

File: core/src/main/java/io/kestra/core/runners/FlowableUtils.java [hunk 1]
```diff
@@ -166,22 +165,26 @@ public static List<NextTaskRun> resolveDagNexts(
...
                         .stream()
                         .filter(taskDepend -> taskDepend
                             .getTask()
                             .getId()
                             .equals(task.getId())
                         )
-                        .findFirst()
-                        .get()
-                        .getDependsOn();
+                        .findFirst();
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/runners/FlowableUtils.java:182]: You can use `.map(...).orElse()` it would be more compact

Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/runners/FlowableUtils.java:182]: You can use `.map(...).orElse()` it would be more compact

**Review by loicmathieu — CHANGES_REQUESTED** [review]

**Review by loicmathieu — APPROVED** [review]
LGTM
