### PR TITLE
fix(core): handle subflow retries

### LINKED ISSUE #4823: Parent flow with `retry` does not retry when Subflow fails and `transmitFailed` set to true
### Describe the issue

This parent flow will call a Subflow which will fail. `transmitFailed` is set to true meaning that the parent flow fails too. However, the parent flow does not retry despite being defined.

Parent flow:
```yaml
id: retry_flow
namespace: kestra.sandbox

retry:
  maxAttempt: 2
  behavior: CREATE_NEW_EXECUTION
  type: constant
  interval: PT2S

tasks:
  - id: call_subflow
    type: io.kestra.plugin.core.flow.Subflow
    namespace: "{{ flow.namespace }}"
    flowId: fail_flow
    wait: true
    transmitFailed: true
```
Subflow:
```yaml
id: fail_flow
namespace: kestra.sandbox

tasks:
  - id: fail
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - exit 1
```
What happened:
Screenshot 2024-09-04 at 13 36 39

What should happen (parent flow is forced to fail separately to subflow to generate expected result):
Screenshot 2024-09-04 at 13 37 11

### Environment

- Kestra Version: 0.19 Snapshot as well as 0.18.4
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes #4823

### CODE REVIEW

File: jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java [hunk 1]
```diff
@@ -917,18 +917,22 @@ private boolean deduplicateWorkerTask(Execution execution, ExecutorState executo
 
     private boolean deduplicateSubflowExecution(Execution execution, ExecutorState executorState, TaskRun taskRun) {
         // There can be multiple executions for the same task, so we need to deduplicated with the worker task execution iteration
-        String deduplicationKey = taskRun.getId() + (taskRun.getIteration() == null ? "" : "-" + taskRun.getIteration());
+        String deduplicationKey = deduplicationKey(taskRun);
         State.Type current = executorState.getSubflowExecutionDeduplication().get(deduplicationKey);
 
         if (current == taskRun.getState().getCurrent()) {
-            log.trace("Duplicate SubflowExecution on execution '{}' for taskRun '{}', value '{}, taskId '{}'", execution.getId(), taskRun.getId(), taskRun.getValue(), taskRun.getTaskId());
+            log.info("Duplicate SubflowExecution on execution '{}' for taskRun '{}', value '{}', taskId '{}', attempt '{}'", execution.getId(), taskRun.getId(), taskRun.getValue(), taskRun.getTaskId(), taskRun.getAttempts().size() + 1);
```
Comment (loicmathieu) [inline jdbc/src/main/java/io/kestra/jdbc/runner/JdbcExecutor.java]:
```suggestion
            log.trace("Duplicate SubflowExecution on execution '{}' for taskRun '{}', value '{}', taskId '{}', attempt '{}'", execution.getId(), taskRun.getId(), taskRun.getValue(), taskRun.getTaskId(), taskRun.getAttempts().size() + 1);
```
Please stay with trace level for this log

**Review by loicmathieu — APPROVED** [review]
Please move back the log level to info before merging
