### PR TITLE
fix(ui): Add form for anyOf type

### LINKED ISSUE #1383: Retry not handle as an object and can't be edited in task editor
### Expected Behavior

Should be able to edit retry

### Actual Behaviour

If a retry exists, it will not be displayed as an object. Also, it cannot be edited.
image

### Steps To Reproduce

_No response_

### Environment Information

- Kestra Version: 0.9.0

### Example flow

_No response_

### PR DESCRIPTION
**Pull request by Skraye**
close #1383

* See comment around code

### CODE REVIEW

File: core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java [hunk 1]
```diff
@@ -42,7 +46,11 @@ protected AbstractClassDocumentation(JsonSchemaGenerator jsonSchemaGenerator, Cl
             .filter(entry -> !entry.getKey().equals("io.kestra.core.models.tasks.Task"))
             .map(entry -> {
                 Map<String, Object> value = (Map<String, Object>) entry.getValue();
-                value.put("properties", flatten(properties(value), required(value)));
+                try {
+                    value.put("properties", flatten(properties(value), required(value), AbstractRetry.class.isAssignableFrom(Class.forName(entry.getKey()))));
```
Comment (Skraye) [inline core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java:50]: Required for class like Retry where they have a "type" property that we want to keep

File: ui/src/components/flows/tasks/TaskAnyOf.vue [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+            };
+        },
+        created() {
+            this.schemas = this.schema?.anyOf ?? []
+        },
+        methods: {
+            onSelect(value) {
+                this.selectedSchema = value
+                // Set up default values
+                if (this.currentSchema.properties && this.modelValue === undefined) {
```
Comment (Skraye) [inline ui/src/components/flows/tasks/TaskAnyOf.vue:87]: It is a bit tricky here, we must force default value if the property is required because, however, even if the property is visually filled in the input, it will not be in the javascript object that represents the task

File: core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java [hunk 3]
```diff
@@ -80,7 +88,14 @@ protected AbstractClassDocumentation(JsonSchemaGenerator jsonSchemaGenerator, Cl
...
         map.remove("type");
-        return flatten(map, required, null);
+        return flatten(map, required, (String) null);
+    }
+
+    protected static Map<String, Object> flatten(Map<String, Object> map, List<String> required, Boolean keepType) {
+        if (!keepType) {
+            map.remove("type");
+        }
+        return flatten(map, required, (String) null);
```
Comment (Skraye) [inline core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java:98]: Cast is necessary because we have now two `flatten` method with 3 params that could works with a null as a 3rd parameter

File: core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java (hunk 1 above)
Comment (loicmathieu) [reply core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java:50]: There may be multiple `type` that we will need to keep, better to extract that in a dedicated method like `isTypeToKeep(entry.getKey)` I also think that if there is a class related exception we should just goes with the default (so returning null)

File: ui/src/components/flows/tasks/TaskObject.vue [hunk 4]
```diff
@@ -40,6 +40,7 @@
             :root="root"
             :schema="schema"
             :definitions="definitions"
+            @update:model-value="onInput"
```
Comment (loicmathieu) [inline ui/src/components/flows/tasks/TaskObject.vue:43]: The `onInput` method has been removed, are you sure it's correct here?

File: core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java:1]: This class is for the documentation but the validation should occurs on the JsonSchema so I have mixed feelings here ...

**Review by loicmathieu — CHANGES_REQUESTED** [review]

File: ui/src/components/flows/tasks/TaskObject.vue (hunk 4 above)
Comment (Skraye) [reply ui/src/components/flows/tasks/TaskObject.vue:43]: Yes because we use the mixins Task that already have the `onInput` method which is the good one for this component, the  `onInput` on this component was overriding the other one.

File: core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java [hunk 5]
```diff
@@ -114,6 +127,24 @@ protected static Map<String, Object> flatten(Map<String, Object> map, List<Strin
         return result;
     }
 
+    // Some task can have the `type` property but not to represent the task
+    // so we cant to keep it in the doc
+    private Boolean isTypeToKeep(String key){
+        List<Class<?>> typesToKeep = List.of(
+            AbstractRetry.class
+        );
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java:135]: Well, I just ask to be extracted to a method, not need to create a list with one element this seems overcomplicated ;)

File: core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java
Comment (loicmathieu) [reply core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java:1]: @Skraye can you explain why it is in the documentation part and not on the jsonschema?

**Review by loicmathieu — CHANGES_REQUESTED** [review]
This didn't seems to work.

I have a retry configured
image

When I try to edit it, the type is not prefilled with the existing properties.
If I select the correct type, then the form is prefilled with the properties.

File: core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java (hunk 5 above)
Comment (Skraye) [reply core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java:135]: Well, if we face another issue similar with a type property, we just need to add `Class.class` and its done

**Comment by Skraye** [comment]
@loicmathieu 
> When I try to edit it, the type is not prefilled with the existing properties.
If I select the correct type, then the form is prefilled with the properties.

This is the correct behavior, I have no way to match the class of your object
Remember that the issue mention the retry, but in fact its related to every property that are `anyOf`

About why its in the documentation and not in the json Schema is because the form is based on the endpoints  `api/v1/plugins/{cls}` which does return the documentation
 In a way, it also fixed an issue where the retry documentation was missing its `type` property

**Comment by loicmathieu** [comment]
> This is the correct behavior, I have no way to match the class of your object

This is a bit unfortunate but if it's the best we can do so OK.

File: core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java (hunk 5 above)
Comment (loicmathieu) [reply core/src/main/java/io/kestra/core/docs/AbstractClassDocumentation.java:135]: If we face another issue we just nee to switch to a list and iterate over it.
KISS, don't optimize for a potential future that will never happen

**Review by loicmathieu — APPROVED** [review]
I approve it but I politely ask you to update the `isTypeToKeep()` method to avoid the un-needed list and loop for code clarity before merging.
Not need for another round of review
