### PR TITLE
fix(core): label check to add as filter and routerlink

### LINKED ISSUE #15401: Clicking on labels tag not adding filter.
### Describe the issue

Clicking on `labels` tag not adding filter and it just open the particular id in one click.

- single-click anywhere on the row navigates away
- No "Open in new tab" or copy the URL or `cmd/ctrl + click`

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by Piyush-r-bhaskar**
Closes https://github.com/kestra-io/kestra/issues/15401

### CODE REVIEW

**Review by MilosPaunovic — CHANGES_REQUESTED** [review]
Hey, double click was removed in https://github.com/kestra-io/kestra/pull/15268.

Can you add `.prevent.stop` to the label click to sort the problem here?

**Comment by Piyush-r-bhaskar** [comment]
Ahh sure, but still we have an issue with not able to open the id in new tab ?

**Comment by MilosPaunovic** [comment]
Ooh, yes, that's true, so you should add back the router link on `id` field, absolutely right.

**Comment by Piyush-r-bhaskar** [comment]
yeah, and I am going to remove `dblclick` and use the `.prevent.stop`

File: ui/src/components/executions/Executions.vue [hunk 1]
```diff
@@ -1089,7 +1100,7 @@
     color: var(--ks-content-primary);
 }
 
-:deep(.executions-table) .el-table__row {
```
Comment (MilosPaunovic) [inline ui/src/components/executions/Executions.vue:1092]: We'd also want to keep cursor pointer on the whole row, as now it's clickable,

**Review by MilosPaunovic — CHANGES_REQUESTED** [review]

File: ui/src/components/executions/Executions.vue (hunk 1 above)
Comment (Piyush-r-bhaskar) [reply ui/src/components/executions/Executions.vue:1092]: Absolutely right 🤩

**Review by MilosPaunovic — APPROVED** [review]
Perfect now! ✅
