### PR TITLE
fix(core): wrong @NotNull import leading to key not being marked as required

### LINKED ISSUE #9287: KVstore delete task - missclassified properties
### Describe the issue

io.kestra.plugin.core.kv.Delete

Image

should at least provide a key and a namespace

### Environment

- Kestra Version: 

Image

### PR DESCRIPTION
**Pull request by brian-mulier-p**
Also fix an issue due to temporary list of required props not being trimmed as we find & trim properties that have default values

closes https://github.com/kestra-io/kestra/issues/9287

### CODE REVIEW

File: core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java [hunk 1]
```diff
@@ -122,12 +122,13 @@ private void removeRequiredOnPropsWithDefaults(ObjectNode objectNode) {
...
                 List<String> requiredFieldValues = StreamSupport.stream(requiredPropsNode.spliterator(), false)
                     .map(JsonNode::asText)
-                    .toList();
+                    .collect(Collectors.toList());
 
                 properties.fields().forEachRemaining(e -> {
                     int indexInRequiredArray = requiredFieldValues.indexOf(e.getKey());
                     if (indexInRequiredArray != -1 && e.getValue() instanceof ObjectNode valueNode && valueNode.has("default")) {
                         requiredPropsNode.remove(indexInRequiredArray);
+                        requiredFieldValues.remove(indexInRequiredArray);
```
Comment (brian-mulier-p) [inline core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java:131]: as we weren't updating that tmp list at the same time as the node, the indices were totally out of sync if there was more than 1 required prop that has default

**Review by fhussonnois — APPROVED** [review]
LGTM!
