### PR TITLE
fix(): correct next execution date when updating trigger from ui/source

### LINKED ISSUE #3067: Disabled a date calculate the wrong next date
- Before 
image
- I click on disabled 
- After
image

THe date is not relevant based on this schedule: 
```yaml
triggers: 
  - type: io.kestra.core.models.triggers.types.Schedule
    id: schedule
    cron: "0 0 * * *"
```

### LINKED ISSUE #3073: Removing a condition on a trigger didn't recompute the next execution date
### Describe the issue

For example with the following flow:

```
id: hello-schedule-condition-bug
namespace: company.team

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "* * * * *"
    scheduleConditions:
     -  type: io.kestra.core.models.conditions.types.DayWeekInMonthCondition
        date: "{{ trigger.date }}"
        dayOfWeek: "MONDAY"
        dayInMonth: "FIRST"

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Schedule with condition
```

Due to the condition, the next evaluation date will be, for ex 2024-03-04 (as we are the 2024-02-15) and not in a minute.
Removing the condition didn't update the next evaluation date.

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

### PR DESCRIPTION
**Pull request by Skraye**
close #3073 
close #3067

### CODE REVIEW

File: core/src/main/java/io/kestra/core/models/triggers/Trigger.java [hunk 1]
```diff
@@ -214,11 +217,11 @@ public static Trigger of(Flow flow, AbstractTrigger abstractTrigger, ConditionCo
             .nextExecutionDate(((PollingTriggerInterface) abstractTrigger).nextEvaluationDate(conditionContext, Optional.empty()))
             .stopAfter(abstractTrigger.getStopAfter())
             .disabled(lastTrigger.map(TriggerContext::getDisabled).orElse(Boolean.FALSE))
-            .backfill(lastTrigger.map(TriggerContext::getBackfill).orElse(null))
+            .backfill(null)
             .build();
     }
 
-    public static Trigger update(Trigger currentTrigger, Trigger newTrigger) {
+    public static Trigger update(Trigger currentTrigger, Trigger newTrigger, AbstractTrigger abstractTrigger, ConditionContext conditionContext) throws Exception {
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/models/triggers/Trigger.java:224]: I think it's better to calculate the next date out of this method so any exception can be handled easily.
Those methods inside the Trigger object are designed to be builders/mappers.

**Review by loicmathieu — CHANGES_REQUESTED** [review]
