### PR TITLE
fix(ui): faster log display

### LINKED ISSUE #1557: Gantt chart logs are slower
### Expected Behavior

_No response_

### Actual Behaviour

Since #360 it seems the display of logs in the Gantt view is slower

### Steps To Reproduce

_No response_

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

_No response_

### PR DESCRIPTION
**Pull request by Skraye**
close #1557

### CODE REVIEW

File: ui/src/components/logs/LogList.vue [hunk 1]
```diff
@@ -317,13 +316,26 @@
...
+                    }
+                });
+            },
             scrollToBottomFailedTask() {
-                if (this.execution.state.current === State.FAILED || this.execution.state.current === State.RUNNING) {
+                if (this.logsToOpen.includes(this.execution.state.current)) {
                     this.currentTaskRuns.forEach((taskRun) => {
                         if (taskRun.state.current === State.FAILED || taskRun.state.current === State.RUNNING) {
-                            const attemptNumber = taskRun.attempts ? taskRun.attempts.length - 1 : 0
+                            const attemptNumber = taskRun.attempts ? taskRun.attempts.length - 1 : this.attempt ? this.attempt : 0
```
Comment (brian-mulier-p) [inline ui/src/components/logs/LogList.vue:334]:
```suggestion
                            const attemptNumber = taskRun.attempts ? taskRun.attempts.length - 1 : (this.attempt ?? 0)
```
should work

**Review by brian-mulier-p — CHANGES_REQUESTED** [review]
Few changes
