### PR TITLE
Fix: add padding around user image in sidebar

### LINKED ISSUE #10549: Sidebar, user icon padding
In the left sidebar, there is a user related component with a picker, which does look a bit cramped now.

I propose that we introduce a little padding around the image which should make it look a lot better, IMO.

Image

### PR DESCRIPTION
**Pull request by VanshikaKumar1910**
Closes https://github.com/kestra-io/kestra/issues/10549.

### What changes are being made and why?

This PR introduces a small but important UI fix to improve the visual appearance of the sidebar.

- **fix(ui): add padding around user image in sidebar**
- The user-related component in the sidebar previously had no padding, causing the profile image to appear cramped.
- Adding consistent padding ensures better alignment, improves visual clarity, and aligns with the overall design system.
- This change is purely cosmetic and does not impact functionality.

---

### CODE REVIEW

**Comment by MilosPaunovic** [comment]
Just a small note for the future, if you could use **GitHub Keywords** when opening PRs to connect it to the proper issue (to automate the entire process a bit more), it would be super helpful to us. You can read a bit more about it [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) (I've added closing keyword for this particular issue).

File: ui/src/override/components/auth/Auth.vue [hunk 1]
```diff
@@ -130,4 +130,10 @@ html.menu-collapsed {
         display: none;
     }
 }
+
+.user-avatar {
+    padding: 4px;
```
Comment (MilosPaunovic) [inline ui/src/override/components/auth/Auth.vue:135]: Can we change both `padding` and `border-radius` to `0.25rem`?

**Review by MilosPaunovic — CHANGES_REQUESTED** [review]
Small change to be done and we're good to merge!

**Review by MilosPaunovic — APPROVED** [review]
