### PR TITLE
fix: added closing option in playground horizontal panel

### LINKED ISSUE #10660: [Playground] Closing the horizontal panel
When using the `Playground`, I expect the horizontal panel to have the same options as the vertical one - so the button to close the panel and the more options button on the far right. Maybe even consider moving `Logs`, `Gantt`, `Outputs` and `Metrics` as tabs of that panel, to keep consistency.

Also, we should add a tooltip note somewhere that if the user switches the Playground toggle off, and then back on, all the information would still be there (considering the page is not left).

Image

### PR DESCRIPTION
**Pull request by bishalbera**
closes #10660 
Screenshot 2025-08-19 at 10 18 13 AM

### CODE REVIEW

File: ui/src/components/flows/FlowPlayground.vue [hunk 1]
```diff
@@ -23,6 +23,26 @@
...
+                            class="tab-icon"
+                            @click="playgroundStore.enabled = false"
+                            :title="t('close')"
+                        />
+                        <el-dropdown trigger="click" placement="bottom-end">
+                            <el-button :icon="DotsVertical" link class="tab-icon" />
+                            <template #dropdown>
+                                <el-dropdown-menu class="m-2">
+                                    <el-dropdown-item @click="playgroundStore.clearExecutions()">
+                                        <span class="small-text">{{ t('clear') }} {{ t('history').toLowerCase() }}</span>
```
Comment (elevatebart) [inline ui/src/components/flows/FlowPlayground.vue]: Can you create a separate constant for this. Ideally it woudl be a subkey in the playground object?

This will pose a problem in any language not exactly structured as English: Verb can be after or before the noun, sometimes its is a single word or more.

```suggestion
                                        <span class="small-text">{{ t('playground.clear_history') }}</span>
```

File: ui/src/components/inputs/FlowPlaygroundToggle.vue [hunk 2]
```diff
@@ -1,5 +1,7 @@
 <template>
-    <el-switch v-model="playgroundStore.enabled" :active-text="t('playground.toggle')" class="toggle" :class="{'is-active': playgroundStore.enabled}" />
+    <el-tooltip placement="bottom" :content="t('playground.tooltip_persistence')">
+        <el-switch v-model="playgroundStore.enabled" :active-text="t('playground.toggle')" class="toggle" :class="{'is-active': playgroundStore.enabled}" />
+    </el-tooltip>
```
Comment (elevatebart) [inline ui/src/components/inputs/FlowPlaygroundToggle.vue:4]: Great job on this one though!! ❤️

**Review by elevatebart — CHANGES_REQUESTED** [review]
Great PR!
Super small changes before merging.

**Comment by bishalbera** [comment]
hey @elevatebart can you please review it now

**Review by elevatebart — APPROVED** [review]

**Review by MilosPaunovic — CHANGES_REQUESTED** [review]
Hey @bishalbera,

This is behaving absolutely as expected, so great job on that!

Before merging, could we tackle two small issues first:

1. Add missing translation key for clearing history:
image

2. Change the location of tabs to the top line, in the circled area:
image

**Comment by bishalbera** [comment]
> Hey @bishalbera,
> 
> This is behaving absolutely as expected, so great job on that!
> 
> Before merging, could we tackle two small issues first:
> 
> 1. Add missing translation key for clearing history:
> 
> image
> 2. Change the location of tabs to the top line, in the circled area:
> 
> image

ok I'll do that.  One question by tabs do you mean the the three dots and closing button that I created? @MilosPaunovic

**Comment by MilosPaunovic** [comment]
Yeah, sorry, I did not express my mind well enough, that's exactly what I though of.

**Comment by bishalbera** [comment]
> Yeah, sorry, I did not express my mind well enough, that's exactly what I though of.

No worries on it. In the mean time can you review [this](https://github.com/kestra-io/kestra/pull/10789) please.

**Comment by MilosPaunovic** [comment]
Will be reviewed sometime this week, don't worry.

**Comment by bishalbera** [comment]
please check now @MilosPaunovic

**Review by MilosPaunovic — APPROVED** [review]
LGTM! 🚀
