### PR TITLE
fix(core): decrypt outputs for tasks within WorkingDirectory

### LINKED ISSUE #4000: Unable to authenticate to private image repo if GetAuthToken is inside working dir
### Describe the issue

If the GetAuthToken task is executed within a working directory, then the subsequent task that authenticates to a private image repo will fail. For example

**this fails**
```yaml
id: ecr_test
namespace: demo
description: check user creds

tasks:
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
    - id: auth
      type: io.kestra.plugin.aws.ecr.GetAuthToken
      accessKeyId: "{{secret('AWS_ACCESS_KEY_ID')}}"
      secretKeyId: "{{secret('AWS_SECRET_ACCESS_KEY')}}"
      region: "eu-west-3"
    - id: image_test
      type: io.kestra.plugin.scripts.shell.Commands
      runner: DOCKER
      docker:
        credentials:
          password: "{{outputs.auth.token.value)}}"
          username: AWS
        image: "account_id.dkr.ecr.eu-west-3.amazonaws.com/shell:latest"
  
        pullPolicy: ALWAYS
      commands:
        - echo abc
```

Fails with error message
```log
2024-06-11 16:12:10.306Status 404: {"message":"pull access denied for account_id.dkr.ecr.eu-west-3.amazonaws.com/shell, repository does not exist or may require 'docker login': denied: Your Authorization Token is invalid."}

```

**This works**
```yaml
id: ecr_test
namespace: demo
description: check user creds

tasks:
  - id: auth
    type: io.kestra.plugin.aws.ecr.GetAuthToken
    accessKeyId: "{{secret('AWS_ACCESS_KEY_ID')}}"
    secretKeyId: "{{secret('AWS_SECRET_ACCESS_KEY')}}"
    region: "eu-west-3"
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
    - id: image_test
      type: io.kestra.plugin.scripts.shell.Commands
      runner: DOCKER
      docker:
        credentials:
          password: "{{outputs.auth.token.value)}}"
          username: AWS
        image: "account_id.dkr.ecr.eu-west-3.amazonaws.com/shell:latest"
  
        pullPolicy: ALWAYS
      commands:
        - echo abc
```
```

### Environment

- Kestra Version: 0.17.2
- Operating System Docker

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes #4000

### CODE REVIEW

File: core/src/main/java/io/kestra/core/runners/Worker.java [hunk 1]
```diff
@@ -291,7 +291,7 @@ private void handleTask(WorkerTask workerTask) {
                     );
 
                     // all tasks will be handled immediately by the worker
-                    WorkerTaskResult workerTaskResult = this.run(currentWorkerTask, false);
+                    WorkerTaskResult workerTaskResult = this.run(currentWorkerTask.withRunContext(runContext.forWorkingDirectoryTask()), false);
```
Comment (fhussonnois) [inline core/src/main/java/io/kestra/core/runners/Worker.java]: I don't think you need to add the `@With` on the `WorkerTask`. Maybe you can just pass the runContext returned from the `forWorkingDirectoryTask` method directly when initializing the `currentWorkerTask` variable on line 287.

File: core/src/main/java/io/kestra/core/runners/RunContext.java [hunk 2]
```diff
@@ -583,6 +593,19 @@ public RunContext forWorkingDirectory(ApplicationContext applicationContext, Wor
         return newContext;
     }
 
+    public RunContext forWorkingDirectoryTask() {
+        Map<String, Object> decryptedVariables = new HashMap<>();
```
Comment (fhussonnois) [inline core/src/main/java/io/kestra/core/runners/RunContext.java]: You can directly init the decryptedVariables map with  this.variables, and only update the `outputs` entry instead of iterating over all entries.

**Review by fhussonnois — CHANGES_REQUESTED** [review]

File: core/src/main/java/io/kestra/core/runners/Worker.java (hunk 1 above)
Comment (brian-mulier-p) [reply core/src/main/java/io/kestra/core/runners/Worker.java]: Oups didn't see that it was built right above my bad :+1:
