### PR TITLE
fix(plugins): resolve subtypes in low code editor

### LINKED ISSUE #8903: Schema generation is not working properly for Task Runners
There is a problem with generated schema for `taskRunners`.

Example URL:
`plugins/io.kestra.plugin.scripts.python.Script?cls=io.kestra.plugin.scripts.python.Script&all=true`

Will produce (among others) this label: `io.kestra.core.models.tasks.runners.TaskRunner_java.lang.Object_` with this object value:

```js
{
  type: "object",
  properties: {
    version: {
      type: "string",
      title: "The version of the plugin to use.",
      pattern: "\\d+\\.\\d+\\.\\d+(-[a-zA-Z0-9-]+)?|([a-zA-Z0-9]+)",
      $required: false
    }
  },
  required: ["type"]
}
```

Type is required but it's nowhere to be found in the properties object.

See this Slack thread for more details:
https://kestra-io.slack.com/archives/C04HTFM3VL6/p1747830845056679

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes #8903

### CODE REVIEW

File: core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java [hunk 1]
```diff
@@ -238,16 +239,12 @@ protected void build(SchemaGeneratorConfigBuilder builder, boolean draft7) {
             .with(new Swagger2Module())
             .with(Option.DEFINITIONS_FOR_ALL_OBJECTS)
             .with(Option.DEFINITION_FOR_MAIN_SCHEMA)
-            .with(Option.PLAIN_DEFINITION_KEYS)
-            .with(Option.ALLOF_CLEANUP_AT_THE_END);
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java:242]: Can you explain why you remove this option?

File: core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java [hunk 2]
```diff
@@ -56,6 +56,7 @@
 @Singleton
 public class JsonSchemaGenerator {
     private static final List<Class<?>> TYPES_RESOLVED_AS_STRING = List.of(Duration.class, LocalTime.class, LocalDate.class, LocalDateTime.class, ZonedDateTime.class, OffsetDateTime.class, OffsetTime.class);
+    private static final List<Class<?>> SUBTYPE_RESOLUTION_EXCLUSION_FOR_PLUGIN_SCHEMA = List.of(Task.class, AbstractTrigger.class);
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java:59]: Maybe also `Chart` if I understand correctly what you did

File: core/src/test/java/io/kestra/core/docs/ClassPluginDocumentationTest.java [hunk 3]
```diff
@@ -103,7 +103,7 @@ void trigger() throws URISyntaxException {
             PluginClassAndMetadata<AbstractTrigger> metadata = PluginClassAndMetadata.create(scan, Schedule.class, AbstractTrigger.class, null);
             ClassPluginDocumentation<? extends AbstractTrigger> doc = ClassPluginDocumentation.of(jsonSchemaGenerator, metadata, true);
 
-            assertThat(doc.getDefs().size()).isEqualTo(1);
```
Comment (loicmathieu) [inline core/src/test/java/io/kestra/core/docs/ClassPluginDocumentationTest.java:106]: This is concerning now there is a lot of def in the Schedule.
I guess all conditions...

**Review by loicmathieu — APPROVED** [review]
As I understand, you added subtype for all abstract types inside plugin JSON schema (it was previously added only to the Flow).

What still concern me is that it will add a lot of definitions in some plugin like triggers (for conditions) and Script/Commad (for task runner).

We may want to fix that in another way as it's more a documentation issue than a JSON schema issue.

File: core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java (hunk 1 above)
Comment (brian-mulier-p) [reply core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java:242]: fail

File: core/src/test/java/io/kestra/core/docs/ClassPluginDocumentationTest.java (hunk 3 above)
Comment (brian-mulier-p) [reply core/src/test/java/io/kestra/core/docs/ClassPluginDocumentationTest.java:106]: I can remove them but imo it makes sense that they are in it.

File: core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java (hunk 2 above)
Comment (brian-mulier-p) [reply core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java:59]: We can but in any case it should not have any impact as they are referenced nowhere (except if someone uses them in Custom plugins?) and there is really not a lot of them.

Comment (brian-mulier-p) [reply core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java:59]: but again it's opiniated. A more robust way would be to check if a class has a @Plugin then we don't resolve subtypes and let the frontend handle it with a PluginSelector but it's a step further

**Comment by elevatebart** [comment]
Good to go ?

**Comment by brian-mulier-p** [comment]
Just saw the tests passed :+1:
