### PR TITLE
fix(controller): return 404 when flow not found in follow API

### LINKED ISSUE #1299: Follow an execution led to 500 errors if the flow is not found
When a flow is not found (I know, this should not happen), the follow from execution will throw a 500 error, it should return a proper response to the use.

### PR DESCRIPTION
**Pull request by Skraye**
To reproduce it, create a flow with a task that will log, execute it and then delete it from the database (not from the UI!)
Go to the execution logs page/query the `/follow` endpoint, error is now 404. 

closes #1299

### CODE REVIEW

File: core/src/main/java/io/kestra/core/repositories/FlowRepositoryInterface.java [hunk 1]
```diff
@@ -38,6 +38,15 @@ default Flow findByExecution(Execution execution) {
         }
     }
 
+    default Optional<Flow> findOptionalByExecution(Execution execution) {
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/repositories/FlowRepositoryInterface.java:41]: Not a fan of the name of the method.
You can either update findByExecution to return an optional (and impact all usage) or use the findById() in the only place that needs this method. But adding a method in the interface each time you need something slightly different is a code smell.

File: webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java [hunk 2]
```diff
@@ -1095,7 +1096,7 @@ private boolean isStopFollow(Flow flow, Execution execution) {
     @ExecuteOn(TaskExecutors.IO)
     @Get(uri = "/{executionId}/follow", produces = MediaType.TEXT_EVENT_STREAM)
     @Operation(tags = {"Executions"}, summary = "Follow an execution")
-    public Flux<Event<Execution>> follow(
+    public Flux<?> follow(
```
Comment (loicmathieu) [inline webserver/src/main/java/io/kestra/webserver/controllers/ExecutionController.java:1099]: Is it realy needed?
If so, EE should be updated accordingly.

**Review by loicmathieu — CHANGES_REQUESTED** [review]

**Review by loicmathieu — APPROVED** [review]
LGTM
