### PR TITLE
fix/disable-recursive-rendering

### LINKED ISSUE #2740: Disable Pebble rendering on webhook trigger variables (keep rendering secrets/env vars on key, but don't parse the trigger body)
## Problem 

Take the following flow as example:

```yaml
id: github_to_notion
namespace: product

concurrency:
  behavior: QUEUE
  limit: 1

inputs:
  - name: github_url
    type: STRING
    defaults: https://github.com/kestra-io/docs/issues/678

variables:
  github_url: "{{ trigger.body.pull_request.html_url ?? trigger.body.issue.html_url ?? inputs.github_url }}"

tasks:
  - id: github_to_notion
    type: io.kestra.plugin.scripts.python.Commands
    warningOnStdErr: false
    env:
      GITHUB_TOKEN: "{{ secret('GITHUB_TOKEN') }}"
      NOTION_TOKEN: "{{ secret('NOTION_TOKEN') }}"
      DATABASE_ID: "81a8f4c0b1af4f3481da3b9bcab5537b"
    beforeCommands:
      - pip install requests markdown2 beautifulsoup4 --no-warn-script-location
    runner: PROCESS
    namespaceFiles:
      enabled: true
    commands:
      - python scripts/github_to_notion.py "{{ vars.github_url }}"

triggers:
  - id: github
    type: io.kestra.core.models.triggers.types.Webhook
    key: "mykey"
```

It takes a GitHub issue URL and loads it to Notion.  

The execution triggered by a webhook fails with error:

```
Missing variable: 'secrets' on 'Hi, I've set-up a github action as per readme.
...
Root attribute [secrets] does not exist or can not be accessed and strict variables is set to true.
```

## Suggested solution

Disable Pebble rendering on webhook trigger variables. 

image

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes #2740

### CODE REVIEW

File: core/src/main/java/io/kestra/core/runners/VariableRenderer.java [hunk 1]
```diff
@@ -34,9 +35,10 @@
 @Singleton
 public class VariableRenderer {
     private static final Pattern RAW_PATTERN = Pattern.compile("\\{%[-]*\\s*raw\\s*[-]*%\\}(.*?)\\{%[-]*\\s*endraw\\s*[-]*%\\}");
+    public static final int MAX_RENDERING_AMOUNT = 100;
 
-    private Handlebars handlebars;
-    private final PebbleEngine pebbleEngine;
+    public static Handlebars handlebars;
+    public static PebbleEngine pebbleEngine;
```
Comment (brian-mulier-p) [inline core/src/main/java/io/kestra/core/runners/VariableRenderer.java:41]: I had no choice but to put them as static since I need to access them in the new static `renderOnce` & `renderRecursively` methods which are also called from RenderFunction (and in such Pebble functions you don't have access to Micronaut context or the whole PebbleEngine)

Comment (loicmathieu) [reply core/src/main/java/io/kestra/core/runners/VariableRenderer.java:41]: No, your function can themself be CDI beans, this is what we do already for some of them.
Look inside `io.kestra.core.runners.pebble.Extension`

File: core/src/main/java/io/kestra/core/runners/VariableRenderer.java [hunk 2]
```diff
@@ -102,75 +117,76 @@ public String recursiveRender(String inline, Map<String, Object> variables) thro
...
+
+        return result;
+    }
+
+    public static String renderOnce(String inline, Map<String, Object> variables) throws IllegalVariableEvaluationException {
         // pre-process raw tags
         Matcher rawMatcher = RAW_PATTERN.matcher(inline);
         Map<String, String> replacers = new HashMap<>((int) Math.ceil(rawMatcher.groupCount() / 0.75));
-        String currentTemplate = rawMatcher.replaceAll(result -> {
+        inline = rawMatcher.replaceAll(result -> {
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/runners/VariableRenderer.java:135]: Not great to override a parameter

File: core/src/main/java/io/kestra/core/runners/pebble/functions/RenderFunction.java [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+        Boolean recursive = (Boolean) recursiveArg;
+
+        EvaluationContextImpl evaluationContext = (EvaluationContextImpl) context;
+        Map<String, Object> variables = evaluationContext.getScopeChain().getGlobalScopes().stream()
+            .flatMap(scope -> scope.getKeys().stream())
+            .distinct()
+            .collect(HashMap::new, (m, v) -> m.put(v, context.getVariable(v)), HashMap::putAll);
+        try {
+            return recursive
+                ? VariableRenderer.renderRecursively(1, template, variables)
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/runners/pebble/functions/RenderFunction.java:52]: This is strange that it takes an integer argument, I think this should be an implementation detail.

File: core/src/main/java/io/kestra/core/runners/pebble/functions/RenderFunction.java [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+        }
+
+        if (!(args.get("template") instanceof String)) {
+            throw new PebbleException(null, "The 'render' function expects an argument 'template' with type string.", lineNumber, self.getName());
+        }
+        String template = (String) args.get("template");
+
+        Object recursiveArg = args.get("recursive");
+        if (recursiveArg == null) {
+            recursiveArg = true;
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/runners/pebble/functions/RenderFunction.java:37]: I thought we want to discourage recursiveness, in this case shouldn't it be false by default?

**Review by loicmathieu — CHANGES_REQUESTED** [review]

File: core/src/main/java/io/kestra/core/runners/pebble/functions/RenderFunction.java (hunk 4 above)
Comment (anna-geller) [reply core/src/main/java/io/kestra/core/runners/pebble/functions/RenderFunction.java:37]: good catch. By default, we don't render recursively. If you use the render function you opt-in to render (recursively if needed)  explicitly. 

recursive=False is an edge case to render only once as for trigger payload

I'll add a draft PR to docs to show based on examples 👍

**Review by anna-geller — APPROVED** [review]
Works (I only haven't tested the global configuration to keep recursiveness)

<details><summary>here are use cases tested</summary>


1) Where the `render()` function is not needed

```yaml
id: parse_input_and_trigger_expressions
namespace: qa

inputs:
  - name: myinput
    type: STRING
    defaults: hello

tasks:
  - id: parse_date
    type: io.kestra.core.tasks.debugs.Return
    format: "{{ trigger.date ?? execution.startDate | date('yyyy-MM-dd') }}"

  - id: parse_input
    type: io.kestra.core.tasks.debugs.Return
    format: "{{ inputs.myinput }}"

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "* * * * *"
```

2) Where the new `render()` function is needed

```yaml
id: hello
namespace: dev

variables:
  trigger_var: "{{ trigger.date ?? execution.startDate | date('yyyy-MM-dd') }}"

tasks:
  - id: parse_date
    type: io.kestra.core.tasks.debugs.Return
    format: "{{ render(vars.trigger_var) }}" # this will print the recusrively-rendered expression

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "* * * * *"
```

3) Using expressions in namespace variables

```yaml
id: namespaces_variable
namespace: qa

tasks:
  - id: print_variable
    type: io.kestra.core.tasks.debugs.Return
    format: "{{ render(namespace.myvar) }}"
```

4) String concatenation

```yaml
id: pebble_string_concatenation
namespace: qa

inputs:
  - name: date
    type: DATETIME
    defaults: 2024-02-24T22:00:00.000Z

  - name: user
    type: STRING
    defaults: Rick

variables:
  day_of_week: "{{ trigger.date ?? inputs.date | date('EEEE') }}"
  full_date: "{{ vars.day_of_week }}, the {{ trigger.date ?? inputs.date | date('yyyy-MM-dd') }}"
  full_date_tilda: "{{ vars.day_of_week ~ ', the ' ~ (trigger.date ?? inputs.date | date('yyyy-MM-dd')) }}"
  greeting_tilda: "{{'Hello, ' ~ inputs.user ~ ' on ' ~ vars.full_date }}"
  greeting_brackets: "Hello, {{ inputs.user }} on {{ vars.full_date }}"

tasks:
  - id: not-rendered 
    type: io.kestra.core.tasks.log.Log
    message: |
     Tilda: {{ vars.greeting_tilda }}
     Brackets: {{ vars.greeting_brackets }}
     Full date: {{ vars.full_date }}
     Full date tilda: {{ vars.full_date_tilda }}

  - id: rendered-recursively
    type: io.kestra.core.tasks.log.Log
    message: |
     Tilda: {{ render(vars.greeting_tilda) }}
     Brackets: {{ render(vars.greeting_brackets) }}
     Full date: {{ render(vars.full_date) }}
     Full date tilda: {{ render(vars.full_date_tilda) }}

  - id: rendered-once
    type: io.kestra.core.tasks.log.Log
    message: |
     Tilda: {{ render(vars.greeting_tilda, recursive=false) }}
     Brackets: {{ render(vars.greeting_brackets, recursive=false) }}
     Full date: {{ render(vars.full_date, recursive=false) }}
     Full date tilda: {{ render(vars.full_date_tilda, recursive=false) }}

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "* * * * *"
```

5) Webhook trigger 

```yaml
id: pebble_in_webhook
namespace: qa

inputs:
  - name: github_url
    type: STRING
    defaults: https://github.com/kestra-io/kestra/issues/2740

  - name: body
    type: JSON
    defaults: |
      {
        "pull_request": {
            "html_url": "https://github.com/kestra-io/kestra/issues/2740",
            "body": "This PR replaces the ${{ env.GITHUB_TOKEN }} with a more secure ${{ secrets.GITHUB_TOKEN }}"
        }
      }

variables:
  github_url: "{{ trigger.body.pull_request.html_url ?? trigger.body.issue.html_url ?? inputs.github_url }}"
  body: "{{ trigger.body.pull_request.body ?? trigger.body.issue.body ?? inputs.body }}"

tasks:
  - id: render_once
    type: io.kestra.core.tasks.log.Log
    message: "{{ render(vars.body, recursive=false) }}"

  - id: not-recursive
    type: io.kestra.core.tasks.log.Log
    message: "{{ vars.body }}"

  - id: recursive
    type: io.kestra.core.tasks.log.Log
    message: "{{ render(vars.body) }}"
    allowFailure: true # this task will fail because it will try to render the webhook's payload

triggers:
  - id: webhook
    type: io.kestra.core.models.triggers.types.Webhook
    key: test1234
```

triggered by 

```shell
curl -i -X POST -H "Content-Type: application/json" \
  -d '{ "pull_request": {"html_url": "https://github.com/kestra-io/kestra/issues/2740", "body": "This PR replaces the ${{ env.GITHUB_TOKEN }} with a more secure ${{ secrets.GITHUB_TOKEN }}"} }' \
  http://localhost:8080/api/v1/executions/webhook/qa/pebble_in_webhook/test1234
```

</details>

File: core/src/main/java/io/kestra/core/runners/VariableRenderer.java (hunk 1 above)
Comment (brian-mulier-p) [reply core/src/main/java/io/kestra/core/runners/VariableRenderer.java:41]: That's true my bad

File: core/src/main/java/io/kestra/core/runners/pebble/functions/RenderFunction.java (hunk 4 above)
Comment (anna-geller) [reply core/src/main/java/io/kestra/core/runners/pebble/functions/RenderFunction.java:37]: https://github.com/kestra-io/docs/pull/776

File: core/src/main/java/io/kestra/core/runners/pebble/functions/RenderFunction.java [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+        }
+        Boolean recursive = (Boolean) recursiveArg;
+
+        EvaluationContextImpl evaluationContext = (EvaluationContextImpl) context;
+        Map<String, Object> variables = evaluationContext.getScopeChain().getGlobalScopes().stream()
+            .flatMap(scope -> scope.getKeys().stream())
+            .distinct()
+            .collect(HashMap::new, (m, v) -> m.put(v, context.getVariable(v)), HashMap::putAll);
+
+        VariableRenderer variableRenderer = applicationContext.getBean(VariableRenderer.class);
```
Comment (brian-mulier-p) [inline core/src/main/java/io/kestra/core/runners/pebble/functions/RenderFunction.java:57]: I had to move the VariableRenderer bean injection to a runtime one as it's a circular dependency otherwise (VariableRenderer spawns the Pebble extension which spawns this function which needs VariableRenderer) so fetching it a runtime will work

File: core/src/main/java/io/kestra/core/runners/VariableRenderer.java [hunk 6]
```diff
@@ -102,75 +119,79 @@ public String recursiveRender(String inline, Map<String, Object> variables) thro
...
-                "Missing variable: '" + current.getAttributeName() +
-                    "' on '" + current.getFileName() +
-                    "' at line " + current.getLineNumber(),
-                e
-            );
+    public String renderRecursively(String inline, Map<String, Object> variables) throws IllegalVariableEvaluationException {
+        return this.renderRecursively(0, inline, variables);
+    }
+
+    public String renderRecursively(int renderingCount, String inline, Map<String, Object> variables) throws IllegalVariableEvaluationException {
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/runners/VariableRenderer.java:182]:
```suggestion
    rivate String renderRecursively(int renderingCount, String inline, Map<String, Object> variables) throws IllegalVariableEvaluationException {
```

File: core/src/main/java/io/kestra/core/runners/pebble/Extension.java [hunk 7]
```diff
@@ -29,6 +31,10 @@ public class Extension extends AbstractExtension {
     @Inject
     private ReadFileFunction readFileFunction;
 
+    @Inject
+    @Nullable
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/runners/pebble/Extension.java:35]: Why is it nullable?

File: core/src/main/java/io/kestra/core/runners/pebble/functions/RenderFunction.java (hunk 5 above)
Comment (loicmathieu) [reply core/src/main/java/io/kestra/core/runners/pebble/functions/RenderFunction.java:57]: I think you can do it at postConstruct time instead of doing it each time

File: core/src/main/java/io/kestra/core/runners/VariableRenderer.java [hunk 8]
```diff
@@ -34,9 +35,12 @@
 @Singleton
 public class VariableRenderer {
     private static final Pattern RAW_PATTERN = Pattern.compile("\\{%[-]*\\s*raw\\s*[-]*%\\}(.*?)\\{%[-]*\\s*endraw\\s*[-]*%\\}");
+    public static final int MAX_RENDERING_AMOUNT = 100;
 
+    @Getter
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/runners/VariableRenderer.java:40]: Is it really needed? This looks like a bad idea (same for the other getter)

**Review by loicmathieu — CHANGES_REQUESTED** [review]

File: core/src/main/java/io/kestra/core/runners/pebble/Extension.java (hunk 7 above)
Comment (brian-mulier-p) [reply core/src/main/java/io/kestra/core/runners/pebble/Extension.java:35]: Because the function isn't created only if the recursive settings is set to true

Comment (loicmathieu) [reply core/src/main/java/io/kestra/core/runners/pebble/Extension.java:35]: Oh god!
Maybe it would be better to create it and throw, with this we would be able to display a better error message.
Anyway, OK.

File: core/src/main/java/io/kestra/core/runners/VariableRenderer.java (hunk 8 above)
Comment (brian-mulier-p) [reply core/src/main/java/io/kestra/core/runners/VariableRenderer.java:40]: I forgot to remove it

File: core/src/main/java/io/kestra/core/runners/pebble/Extension.java (hunk 7 above)
Comment (brian-mulier-p) [reply core/src/main/java/io/kestra/core/runners/pebble/Extension.java:35]: Ludo advised not to inject the function and let Pebble say that this function doesn't exist, it will be documented that render function cannot be used with recursive setting

**Comment by brian-mulier-p** [comment]
Sorry I forgot to handle complex objects, fortunately CI went red.
Please have a look at these commits:
https://github.com/kestra-io/kestra/pull/2834/commits/4e33653de5188741f7bbf90506cde0513107f902
https://github.com/kestra-io/kestra/pull/2834/commits/becb500dc220a95a97db7978d59f104c72e5af60
https://github.com/kestra-io/kestra/pull/2834/commits/0399fd1dd334e4a826e3f2b9a0bf12db2c58f7ff

**Review by loicmathieu — APPROVED** [review]
