### PR TITLE
fix(core): adjust date property of PublicHoliday condition

### LINKED ISSUE #11586: `io.kestra.plugin.core.condition.PublicHoliday` is not working as intended
### Describe the issue

We were running the below flow config on sanity checks. Instead of getting triggered "11 AM (UTC) on Public Holiday in France", it's running every day and failing sometimes too.

```yaml
id: schedule-condition-publicholiday
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Demo for PublicHoliday condition 

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 11 * * *"
    conditions:
      - type: io.kestra.plugin.core.condition.PublicHoliday
        country: FR
```

Image

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by MTarek165**
Closes: #11586

Description:

Problem:
the issue was caused by not passing the variables map when rendering trigger.date, I found that after investigating some similar condition classes.

Solution:
include  conditionContext.getVariables() in conditionContext.getRunContext().render(date)

### CODE REVIEW

**Comment by loicmathieu** [comment]
Hi,
I wonder if it is the good fix, as a Schedule trigger should always have a `trigger.date` output.
Polling trigger, however, should not.

I need to check the issue and discuss internally to see if it's the good fix as it's a change in behavior.

**Comment by MTarek165** [comment]
@loicmathieu Is there any updates for this PR and its related issue?

**Comment by loicmathieu** [comment]
@MTarek165 `trigger.date` should always be present so the default on the `PublicHoliday` should be OK.
I wonder what's happeneded here.
first step would be to reproduce the issue via a unit test

**Comment by MTarek165** [comment]
Hi @loicmathieu, the issue was caused by not passing the variables map coming from condition context when rendering trigger.date, I found that after investigating some similar condition classes. We missed using conditionContext.getVariables() in conditionContext.getRunContext().render(date). I've fixed it now — you can have a look.

**Comment by MTarek165** [comment]
Hi @loicmathieu, the true issue was caused by not passing the variables map coming from condition context when rendering date property, I found that after investigating some similar condition classes. We missed using conditionContext.getVariables() (which contains the actual value of trigger.date) in conditionContext.getRunContext().render(date). I've fixed it now, It works fine — you can have a look.

**Review by loicmathieu — CHANGES_REQUESTED** [review]
This looks good but could you add a test that reproduce the issue?

**Comment by MTarek165** [comment]
@loicmathieu I added two unit tests , the existing tests in PublicHolidayTest was testing the condition itself on static date . I needed to test dynamic render itself so I included variables map with the condition context and since the default on date is to be rendered at pebble expression so I don't set in tests when reaching test() method it is rendered successfully. By the way the added valid() method is good if we want to test similar cases for other conditions.

File: core/src/main/java/io/kestra/core/services/ConditionService.java [hunk 1]
```diff
@@ -45,7 +47,18 @@ public boolean isValid(Condition condition, FlowInterface flow, @Nullable Execut
     }
 
     public boolean isValid(Condition condition, FlowInterface flow, @Nullable Execution execution) {
-        return this.isValid(condition, flow, execution, null);
+        return this.isValid(condition, flow, execution, (MultipleConditionStorageInterface) null);
+    }
+    @VisibleForTesting
+    public boolean isValid(Condition condition,FlowInterface flow,@Nullable Execution execution,Map<String,Object>variables){
```
Comment (loicmathieu) [inline core/src/main/java/io/kestra/core/services/ConditionService.java]: Please remove this method and any changes to this class.
It's not needed as you can use one of the method taht takes a condition context as a parameter and creates the condition context in the test

File: core/src/test/java/io/kestra/plugin/core/condition/PublicHolidayTest.java [hunk 2]
```diff
@@ -54,6 +56,42 @@ void invalid() {
             .build();
         assertThat(conditionService.isValid(publicHoliday, flow, execution)).isFalse();
     }
+    @Test
```
Comment (loicmathieu) [inline core/src/test/java/io/kestra/plugin/core/condition/PublicHolidayTest.java]:
```suggestion

    @Test
```

File: core/src/test/java/io/kestra/plugin/core/condition/PublicHolidayTest.java [hunk 3]
```diff
@@ -54,6 +56,42 @@ void invalid() {
...
+        Execution execution = TestsUtils.mockExecution(flow, variables);
+
+        PublicHoliday publicHoliday = PublicHoliday.builder()
+            .country(Property.ofValue("FR"))
+            .build();
+
+
+        assertThat(conditionService.isValid(publicHoliday, flow, execution, variables)).isTrue();
+    }
+    @Test
```
Comment (loicmathieu) [inline core/src/test/java/io/kestra/plugin/core/condition/PublicHolidayTest.java]:
```suggestion

    @Test
```

File: core/src/main/java/io/kestra/core/services/ConditionService.java (hunk 1 above)
Comment (loicmathieu) [reply core/src/main/java/io/kestra/core/services/ConditionService.java]: We try to avoid adding test related code in non-test sources

**Review by loicmathieu — CHANGES_REQUESTED** [review]

File: core/src/main/java/io/kestra/core/services/ConditionService.java (hunk 1 above)
Comment (MTarek165) [reply core/src/main/java/io/kestra/core/services/ConditionService.java]: @loicmathieu ok but this would requere me to inject RunContextFactory in the test class . Is it ok ?

**Review by loicmathieu — APPROVED** [review]
LGTM, thanks
