### PR TITLE
fix: always load the right version of plugin docs

### LINKED ISSUE #13180: In-line documentation no longer shows on newline
### Feature description

Unsure if this was by design or a bug, but imo a regression between at least 0.22 and 1.x has been if you go onto a newline while working on a plugin the documentation goes away. As an example see the 2 images side by side, in both cases the cursor is on line 7. In 0.22 the documentation for python plugin shows, but for 1.x it does not 

Image

### PR DESCRIPTION
**Pull request by elevatebart**
closes #13180

### CODE REVIEW

**Review by Piyush-r-bhaskar — APPROVED** [review]
one nitpick otherwise Looks good 🚀

Unable to open any plugin from `/plugins` though its adding in url

Image

File: ui/src/components/inputs/EditorWrapper.vue [hunk 1]
```diff
@@ -279,34 +274,10 @@
...
-                        !closest || getRangeSize(current.range) < getRangeSize(closest.range)
-                            ? current
-                            : closest
-                    , null as any);
-
-        let result = selectedElement ? getElementFromRange(selectedElement) : undefined;
-        result = {...result, hash: hash.value, forceRefresh: true};
-        pluginsStore.updateDocumentation(result as Parameters<typeof pluginsStore.updateDocumentation>[0]);
+    function updatePluginDocumentation(event: {position: monaco.Position, model: monaco.editor.ITextModel}) {
+        const cls = YAML_UTILS.getTypeAtPosition(source.value, event.position, pluginsStore.allTypes);
```
Comment (Piyush-r-bhaskar) [inline ui/src/components/inputs/EditorWrapper.vue:278]: Thanks for this 🤩
